Disk Access changes
Azure/azure-powershell pull request #12673
Opened 2020-08-14 15:18 UTC by haagha

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-08-14 15:18 UTC, adxsdkps commented
Can one of the admins verify this patch?

2020-08-19 01:49 UTC, grizzlytheodore commented
needs changelog.md

2020-08-19 02:42 UTC, msJinLei commented
@haagha  Have you submitted a cmdlet review https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues?
If yes, could you provide the link?

2020-08-19 14:29 UTC, grizzlytheodore commented
@msJinLei  https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/639 
here is the design review. 
I added 'Do not merge' label, we need to demo to our stakeholders and make sure they are happy with what we implemented.

2020-08-19 23:22 UTC, grizzlytheodore commented on src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
> +        Assert-AreEqual $diskAccess.Id $disk.DiskAccessId;
$disk.DiskAccessID I am getting null for this value. not sure why it's passing. 

Assert-NotNull $disk.DiskAccessID may help before this

2020-08-19 23:30 UTC, grizzlytheodore commented on src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
> +        Assert-AreEqual $diskAccess.Id $disk.DiskAccessId;
@haagha

2020-08-19 23:32 UTC, grizzlytheodore commented on src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
> +
this part above isnt used so I think they can be taken out @Sandido

2020-08-19 23:46 UTC, grizzlytheodore commented on src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
> +        Assert-AreEqual $diskAccess.Id $disk.DiskAccessId;
nevermind. worked second time

2020-08-20 19:33 UTC, grizzlytheodore commented on src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
> +
@haagha correction

2020-08-20 19:44 UTC, grizzlytheodore commented on src/Compute/Compute.Test/ScenarioTests/DiskRPTests.ps1
> +
i removed it

2020-08-24 15:15 UTC, haagha commented
/azp run

2020-08-25 17:22 UTC, grizzlytheodore commented on src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
> +        public string NetworkAccessPolicy { get; set; }
add completer

2020-08-26 14:04 UTC, haagha commented on src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
> +                DiskAccessId = this.IsParameterBound(c => c.DiskAccessId) ? this.DiskAccessId : null
checked

2020-08-26 14:05 UTC, haagha commented on src/Compute/Compute/help/New-AzDiskConfig.md
> +Gets or sets ARM id of the DiskAccess resource for using private endpoints on.
edited

2020-08-26 14:05 UTC, haagha commented on src/Compute/Compute/Generated/Disk/Config/NewAzureRmDiskConfigCommand.cs
> +        public string NetworkAccessPolicy { get; set; }
added

2020-08-26 14:42 UTC, Sandido commented
@msJinLei , we have addressed the review comments. Please review this.

2020-08-28 02:12 UTC, msJinLei requested changes

2020-08-28 02:12 UTC, msJinLei commented on src/Compute/Compute/ChangeLog.md
> --->
You should add back -->

2020-08-28 02:12 UTC, msJinLei commented
@haagha 
- Please resolve the conflicts and fix the error in ChangeLog.md

2020-08-28 14:41 UTC, grizzlytheodore commented
@msJinLei thank you for catching that. your comment has been addressed

2020-08-28 14:53 UTC, Sandido commented on src/Compute/Compute/ChangeLog.md
> +* Added `SupportAutomaticPlacement` to New-AzHostGroup
"Added the optional parameter 'SupportAutomaticPlacement' to New-AzHostGroup"

2020-08-31 14:30 UTC, grizzlytheodore commented
@msJinLei please review and merge

2020-09-01 03:00 UTC, msJinLei requested changes

2020-09-01 03:00 UTC, msJinLei commented on src/Compute/Compute/Generated/Snapshot/Config/NewAzureRmSnapshotConfigCommand.cs
> +        public string NetworkAccessPolicy { get; set; }
Why NetworkAccessPolicy has no argument completer?

2020-09-01 03:09 UTC, msJinLei requested changes

2020-09-01 03:09 UTC, msJinLei commented on src/Compute/Compute/help/New-AzDiskEncryptionSetConfig.md
> +### -EncryptionType
It is very strange that argument completer is not generated here. Can you try to regenerate it here?

2020-09-01 16:16 UTC, grizzlytheodore commented
@msJinLei  your comments are addressed. We appreciate it. Please review and merge!

2020-09-03 04:04 UTC, msJinLei approved these changes

2020-09-03 04:06 UTC, msJinLei approved these changes

2020-09-03 06:08 UTC, msJinLei approved these changes

2020-09-03 06:10 UTC, msJinLei commented
@haagha please waiting for the sign of from @Sandido

2020-09-03 15:41 UTC, Sandido approved these changes

2020-09-03 20:02 UTC, Sandido commented
@msJinLei , I approved the PR.

2020-09-04 01:49 UTC, merged