Adding new optional parameter BackupStorageRedundancy to New-AzSqlInstance cmdlet
Azure/azure-powershell pull request #12802
Opened 2020-08-28 13:44 UTC by petrajkogit

## Description

Adding new optional parameter BackupStorageRedundancy to New-AzSqlInstance cmdlet. Rerecorded tests, since api version changed. Note that there is PR that is dependent on this review (https://github.com/Azure/azure-powershell/pull/12782), and it can be checked-in after this one is completed.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-08-28 13:48 UTC, petrajkogit commented on src/Sql/Sql/ServerActiveDirectoryAdministrator/Services/AzureSqlServerActiveDirectoryAdministratorCommunicator.cs
> +            return null;
This is temp solution just for build to pass, and it is fixed with https://github.com/Azure/azure-powershell/pull/12782 which must be checked-in after this one.

2020-09-01 01:37 UTC, msJinLei requested changes

2020-09-01 01:37 UTC, msJinLei commented on src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
> +        [PSArgumentCompleter("LRS", "ZRS", "RA-GRS")]
Powershell will supply argument completer when the parameter has a validate set automatically and so you can remove PSArgumentCompleter here.

2020-09-01 02:26 UTC, msJinLei approved these changes

2020-09-02 08:13 UTC, msJinLei approved these changes

2020-09-02 08:14 UTC, merged