Add ApiProperties support for Cognitive Services
Azure/azure-powershell pull request #12870
Opened 2020-09-04 21:06 UTC by yangyuan

## Description

* Add `New-AzCognitiveServicesAccountApiProperties` command.
* Support "ApiProperties" parameter for `New-AzCognitiveServicesAccount` and `Set-AzCognitiveServicesAccount`

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-09-08 04:02 UTC, msJinLei commented
@yangyuan Please fix the issue report in static analysis

```
  D:\a\1\s\artifacts//StaticAnalysisResults\SignatureIssues.csv Errors
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "D:\a\1\s\artifacts\Debug\Az.CognitiveServices\Microsoft.Azure.PowerShell.Cmdlets.CognitiveServices.dll","Microsoft.Azure.Commands.Management.CognitiveServices.NewAzureCognitiveServicesAccountCommand","New-AzCognitiveServicesAccount","1","8410","Parameter ApiProperties of cmdlet New-AzCognitiveServicesAccount does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name."
  "D:\a\1\s\artifacts\Debug\Az.CognitiveServices\Microsoft.Azure.PowerShell.Cmdlets.CognitiveServices.dll","Microsoft.Azure.Commands.Management.CognitiveServices.NewAzureCognitiveServicesAccountApiPropertiesCommand","New-AzCognitiveServicesAccountApiProperties","1","8400","New-AzCognitiveServicesAccountApiProperties uses the noun 'AzCognitiveServicesAccountApiProperties', which does not follow the enforced naming convention of using a singular noun for a cmdlet name.","Consider using a singular noun for the cmdlet name."
  "D:\a\1\s\artifacts\Debug\Az.CognitiveServices\Microsoft.Azure.PowerShell.Cmdlets.CognitiveServices.dll","Microsoft.Azure.Commands.Management.CognitiveServices.SetAzureCognitiveServicesAccountCommand","Set-AzCognitiveServicesAccount","1","8410","Parameter ApiProperties of cmdlet Set-AzCognitiveServicesAccount does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name."
  
  
  D:\a\1\s\artifacts//StaticAnalysisResults\SignatureIssues.csv:
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "D:\a\1\s\artifacts\Debug\Az.CognitiveServices\Microsoft.Azure.PowerShell.Cmdlets.CognitiveServices.dll","Microsoft.Azure.Commands.Management.CognitiveServices.NewAzureCognitiveServicesAccountCommand","New-AzCognitiveServicesAccount","1","8410","Parameter ApiProperties of cmdlet New-AzCognitiveServicesAccount does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name."
  "D:\a\1\s\artifacts\Debug\Az.CognitiveServices\Microsoft.Azure.PowerShell.Cmdlets.CognitiveServices.dll","Microsoft.Azure.Commands.Management.CognitiveServices.NewAzureCognitiveServicesAccountApiPropertiesCommand","New-AzCognitiveServicesAccountApiProperties","1","8400","New-AzCognitiveServicesAccountApiProperties uses the noun 'AzCognitiveServicesAccountApiProperties', which does not follow the enforced naming convention of using a singular noun for a cmdlet name.","Consider using a singular noun for the cmdlet name."
  "D:\a\1\s\artifacts\Debug\Az.CognitiveServices\Microsoft.Azure.PowerShell.Cmdlets.CognitiveServices.dll","Microsoft.Azure.Commands.Management.CognitiveServices.SetAzureCognitiveServicesAccountCommand","Set-AzCognitiveServicesAccount","1","8410","Parameter ApiProperties of cmdlet Set-AzCognitiveServicesAccount does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name."
```

2020-09-09 06:51 UTC, msJinLei requested changes

2020-09-09 06:51 UTC, msJinLei commented on src/CognitiveServices/CognitiveServices/Az.CognitiveServices.psd1
> +               'New-AzCognitiveServicesAccountApiProperties'
You should use singular for cmdlet name

2020-09-09 06:51 UTC, msJinLei commented on src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/SetAzureCognitiveServicesAccount.cs
> +        public CognitiveServicesAccountApiProperties ApiProperties { get; set; }
Please use singular name ApiProperty

2020-09-18 07:01 UTC, yangyuan commented
Hi @msJinLei sorry for late action. I just updated the PR and now cmdlet and parameters are singular now.

2020-09-21 02:22 UTC, msJinLei requested changes

2020-09-21 02:22 UTC, msJinLei commented on src/CognitiveServices/CognitiveServices/CognitiveServicesAccount/NewAzureCognitiveServicesAccountApiProperty.cs
> +            WriteObject(new CognitiveServicesAccountApiProperties());
if the cmdlet just create a local object, no need to support should process here.

2020-09-21 20:41 UTC, yangyuan commented
After removing `should process` I got error says `New-AzCognitiveServicesAccountApiProperty Does not support ShouldProcess but the cmdlet verb New indicates that it should.` any suggestions?

2020-09-22 02:10 UTC, msJinLei commented
> After removing `should process` I got error says `New-AzCognitiveServicesAccountApiProperty Does not support ShouldProcess but the cmdlet verb New indicates that it should.` any suggestions?

Please suppress it https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md#signature-issues

2020-09-22 05:14 UTC, msJinLei approved these changes

2020-09-22 06:19 UTC, yangyuan commented
@msJinLei looks all passed :)

2020-09-22 07:48 UTC, merged