Powershell for AAD Only Authentication on Managed Instance.
Azure/azure-powershell pull request #12890
Opened 2020-09-08 09:14 UTC by strehan1993

## Description

Added cmdlet `Get-AzSqlInstanceActiveDirectoryOnlyAuthentication`
Added cmdlet `Enable-AzSqlInstanceActiveDirectoryOnlyAuthentication`
Added cmdlet `Disable-AzSqlInstanceActiveDirectoryOnlyAuthentication`

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-09-09 05:31 UTC, msJinLei requested changes
@strehan1993
- Firstly, you should submit the cmdlet design review here https://github.com/Azure/azure-powershell-cmdlet-review-pr. 
- And for your PR, here is the comments
  - Disable-AzSqlInstanceActiveDirectoryOnlyAuthentication / Enable-AzSqlInstanceActiveDirectoryOnlyAuthentication
    Please provide the ByResourceId and ByInputObject parameter set
  - Get-AzSqlInstanceActiveDirectoryOnlyAuthentication
    Please provide the ByResourceId  parameter set

2020-09-10 03:39 UTC, msJinLei commented
> @strehan1993
> 
> * Firstly, you should submit the cmdlet design review here https://github.com/Azure/azure-powershell-cmdlet-review-pr.
> * And for your PR, here is the comments
>   
>   * Disable-AzSqlInstanceActiveDirectoryOnlyAuthentication / Enable-AzSqlInstanceActiveDirectoryOnlyAuthentication
>     Please provide the ByResourceId and ByInputObject parameter set
>   * Get-AzSqlInstanceActiveDirectoryOnlyAuthentication
>     Please provide the ByResourceId  parameter set
>   * Here is the reference of required parameter sets https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/design-guidelines/cmdlet-best-practices.md#required-parameter-sets

As we discussed by email,  @strehan1993 help to add missing required parameter sets in the future PR. We will have this PR merged now.

2020-09-10 03:39 UTC, msJinLei approved these changes

2020-09-10 03:39 UTC, merged

2020-09-10 03:45 UTC, strehan1993 commented
Thanks! I'll get back to you once we have a fix for the above.