Adding workload container name validation
Azure/azure-powershell pull request #13017
Opened 2020-09-19 14:16 UTC by hiaga

## Description

Adding container name validation for SQL workload

## Checklist

- [Yes] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [Yes] The title of the PR is clear and informative
- [N/A] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [Yes] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [N/A] If applicable, the changes made in the PR have proper test coverage
- [N/A] For public API changes to cmdlets:
    - [N/A] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [N/A] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-09-21 02:09 UTC, VeryEarly requested changes
please add change log

2020-09-21 04:56 UTC, hiaga commented
@VeryEarly :  added change log. Please review

2020-09-21 09:19 UTC, hiaga commented
@VeryEarly Can you please review this now?

2020-09-22 05:55 UTC, VeryEarly approved these changes

2020-09-22 05:55 UTC, merged