[Storage] Support share soft delete
Azure/azure-powershell pull request #13061
Opened 2020-09-24 09:34 UTC by blueww

## Description

design： Azure/azure-powershell-cmdlet-review-pr#559
the change has been in storage preview before with PR  https://github.com/Azure/azure-powershell/pull/11779

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-09-25 03:20 UTC, VeryEarly requested changes

2020-09-25 03:20 UTC, VeryEarly commented on src/Storage/Storage.Management/ChangeLog.md
> +* Support enable/disable/get share soft delete properties on file Service of a Storage account
```suggestion
* Supported enable/disable/get share soft delete properties on file Service of a Storage account
```

2020-09-25 03:20 UTC, VeryEarly commented
please fix test failures

2020-09-25 09:46 UTC, blueww commented
Tried to fix the CI failures.
And add a static exception for RetentionDays , the name has been discussed in
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/726

2020-09-27 01:51 UTC, blueww commented
/azp run

2020-09-27 08:07 UTC, blueww commented
@VeryEarly 
Would you please help to look at the test timeout on windows? (all other CI passed)

The hang happens seems in SQL test, which seems not related with my change.
Would you please help to check?

##### Test result:
 https://dev.azure.com/azure-sdk/public/_build/results?buildId=553654&view=logs&jobId=b17395f6-68a3-5682-0476-d3f6f1043109&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0

##### Test log: 
> 2020-09-27T02:37:43.3882233Z   [xUnit.net 00:08:37.15]     Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerDisasterRecoveryConfigurationTests.TestServerDisasterRecoveryConfiguration [SKIP]
> 2020-09-27T02:37:43.4295338Z     ! Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ServerDisasterRecoveryConfigurationTests.TestServerDisasterRecoveryConfiguration [1ms]
> 2020-09-27T02:39:13.0826785Z   [xUnit.net 00:10:06.85]     Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests.VulnerabilityAssessmentWithSettingsNotDefinedTest [SKIP]
> 2020-09-27T02:39:13.3020838Z     ! Microsoft.Azure.Commands.Sql.Test.ScenarioTests.VulnerabilityAssessmentTests.VulnerabilityAssessmentWithSettingsNotDefinedTest [1ms]
> 2020-09-27T05:09:42.1595873Z ##[error]The operation was canceled.
> 2020-09-27T05:09:42.1818638Z ##[section]Finishing: Test

2020-09-28 01:42 UTC, VeryEarly approved these changes

2020-09-28 01:42 UTC, merged