[Storage] Add breaking change type
Azure/azure-powershell pull request #13118
Opened 2020-09-30 10:24 UTC by blueww

## Description

Add some breaking change for output type, and remove the before added breaking change warning message

## Checklist

- [x ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x ] The title of the PR is clear and informative
- [x ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x ] If applicable, the changes made in the PR have proper test coverage
- [x ] For public API changes to cmdlets:
    - [ x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-10-09 07:30 UTC, isra-fel requested changes
Generally LGTM 
You'll need to suppress the detected breaking change errors, see https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes

2020-10-09 07:30 UTC, isra-fel commented on src/Storage/Storage.Management/ChangeLog.md
> +*Removed obsolete property RestorePolicy.LastEnabledTime
nit: format
```suggestion
* Removed obsolete property RestorePolicy.LastEnabledTime
```

2020-10-10 05:40 UTC, isra-fel approved these changes

2020-10-10 05:40 UTC, isra-fel commented
/azp run azure-powershell - powershell-core

2020-10-10 10:19 UTC, blueww commented
/azp run

2020-10-12 01:34 UTC, isra-fel commented
/azp run azure-powershell - powershell-core

2020-10-14 06:51 UTC, blueww commented
/azp run azure-powershell - powershell-core

2020-10-15 02:13 UTC, blueww commented
/azp run

2020-10-15 02:19 UTC, wyunchi-ms submitted a review, later dismissed

2020-10-15 05:38 UTC, wyunchi-ms approved these changes

2020-10-15 05:38 UTC, merged