[DataFactory] Add 2 New commands to ADF V2
Azure/azure-powershell pull request #13114
Opened 2020-09-30 01:28 UTC by arsunda

## Description

Adding 2 new commands: `Stop-AzDataFactoryV2TriggerRun` and `Invoke-AzDataFactoryV2TriggerRun`

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-09-30 14:20 UTC, isra-fel commented
Hi @arsunda as you've probably seen in PR template, before introducing new cmdlets you need to submit a cmdelt design review (and make sure it's accepted) here: https://github.com/Azure/azure-powershell-cmdlet-review-pr

2020-10-01 18:11 UTC, arsunda commented
> Hi @arsunda as you've probably seen in PR template, before introducing new cmdlets you need to submit a cmdelt design review (and make sure it's accepted) here: https://github.com/Azure/azure-powershell-cmdlet-review-pr

Hi @isra-fel , Ive added the Design Review here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/749
Will someone be able to look at it over the next few days?

2020-10-09 05:22 UTC, isra-fel commented
/azp run

2020-10-14 20:00 UTC, arsunda commented
@isra-fel The review has been accepted, can we check in this PR?

2020-10-16 06:28 UTC, arsunda commented
@isra-fel ping on this

2020-10-19 07:12 UTC, isra-fel requested changes
Please fix the online help issues detected by static analysis

2020-10-19 07:12 UTC, isra-fel commented on src/DataFactory/DataFactoryV2/help/Invoke-AzDataFactoryV2TriggerRun.md
> +online version:
```suggestion
online version: https://docs.microsoft.com/en-us/powershell/module/az.datafactory/invoke-azdatafactoryv2triggerrun
```

2020-10-19 07:12 UTC, isra-fel commented on src/DataFactory/DataFactoryV2/help/Stop-AzDataFactoryV2TriggerRun.md
> +online version:
```suggestion
online version: https://docs.microsoft.com/en-us/powershell/module/az.datafactory/stop-azdatafactoryv2triggerrun
```

2020-10-20 07:40 UTC, isra-fel approved these changes
LGTM

2020-10-20 09:19 UTC, isra-fel commented
Pending #13237

2020-10-20 09:54 UTC, VeryEarly commented
/azp run

2020-10-20 09:54 UTC, VeryEarly commented
> Pending #13237
> Needs to re-run CI after it's merged

this build didn't get the latest common module 1.3.28 for some reason, it's using 1.3.26 instead.
re-triggered CI.

2020-10-21 03:28 UTC, VeryEarly submitted a review, later dismissed

2020-10-21 04:07 UTC, VeryEarly approved these changes

2020-10-21 06:01 UTC, VeryEarly approved these changes

2020-10-21 06:03 UTC, merged