[Azure CDN] Cmdlets for Multi-Origin & Private Link Functionality
Azure/azure-powershell pull request #13156
Opened 2020-10-07 06:59 UTC by jorinmejia

## Description

This PR brings new and modified cmdlets for the Multi-Origin and Private Link functionality for the Azure CDN service.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/CDN/CDN/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

[Design Review](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/729)

2020-10-08 21:55 UTC, markcowl commented
/azp run

2020-10-09 01:22 UTC, markcowl commented
/azp run

2020-10-09 05:39 UTC, dingmeng-xue commented
/azp run

2020-10-09 07:17 UTC, dingmeng-xue commented
@jorinmejia , test case is failed. Please check the log 
https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/568042/logs/33

2020-10-10 05:15 UTC, isra-fel requested changes

2020-10-10 05:15 UTC, isra-fel commented on src/Cdn/Cdn/Endpoint/NewAzureRmCdnEndpoint.cs
> +        public int? OriginGroupProbeIntervalInSeconds { get; set; }
```suggestion
        public int OriginGroupProbeIntervalInSeconds { get; set; }
```
It's discuraged to type an *optional* parameter with a nullable type. Users may wonder if there's difference between not specifying it and specify a `$null`. If the SDK requires a nullable type, you need to do the conversion.

Please apply this to all the new parameters. Thanks

2020-10-14 18:39 UTC, jorinmejia commented
@dingmeng-xue / @isra-fel can I please get a follow up review for this PR?

2020-10-16 01:17 UTC, isra-fel commented on src/Cdn/Cdn/ChangeLog.md
> +## Version 1.4.4
What I meat is to remove the "## Version 1.4.4" line but keep your changelog line.
If you look at the first lines of changelog.md there's a great example:
```md
<!--
    Please leave this section at the top of the change log.

    Changes for the upcoming release should go under the section titled "Upcoming Release", and should adhere to the following format:

    ## Upcoming Release
    * Overview of change #1
        - Additional information about change #1
    * Overview of change #2
        - Additional information about change #2
        - Additional information about change #2
    * Overview of change #3
    * Overview of change #4
        - Additional information about change #4

    ## YYYY.MM.DD - Version X.Y.Z (Previous Release)
    * Overview of change #1
        - Additional information about change #1
-->
```

2020-10-16 01:19 UTC, isra-fel commented
And please remove the temp SDK packages `tools/LocalFeed/Microsoft.Azure.Management.Cdn.4.3.0-preview.nupkg` and `tools/LocalNugetFeed`. I don't think you are using them anymore.

2020-10-16 04:08 UTC, isra-fel approved these changes

2020-10-16 04:52 UTC, merged