[WindowsIoTServices] Init.
Azure/azure-powershell pull request #13564
Opened 2020-11-23 08:06 UTC by LucasYao93

## Description

+ Add test cases
+ Add examples

2020-11-23 09:24 UTC, LucasYao93 commented
/azp run

2020-11-24 08:18 UTC, msJinLei requested changes

2020-11-24 08:18 UTC, msJinLei commented on src/WindowsIotServices/readme.md
> +  - where:
duplicate with line 96

2020-11-25 02:00 UTC, LucasYao93 commented
Hi @msJinLei,
The pipeline has a error , because the swgger refer of the DesktopVirtualization is incorrect.

Thanks

2020-11-25 03:08 UTC, msJinLei commented
/azp run azure-powershell - gen-sign

2020-11-25 07:55 UTC, msJinLei approved these changes

2020-11-25 08:08 UTC, merged