[NetAppFiles] Anf 7405 update for api version 2020 07 01
Azure/azure-powershell pull request #13576
Opened 2020-11-24 13:49 UTC by audunn

## Description
This bumps NetAppFiles to API version 2020-07-01
- Added aesEncryption, ldapSigning properties to ActiveDirectory
- Fixed Tags in UpdateAzNetAppFilesBackupPolicy
- Return backupId in Backup and BackupPatch models

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-11-25 02:45 UTC, msJinLei requested changes

2020-11-25 02:45 UTC, msJinLei commented on src/NetAppFiles/NetAppFiles/ChangeLog.md
> +## Version 0.2.1
All changes should be under upcoming release before release

2020-11-25 06:53 UTC, msJinLei approved these changes

2020-11-25 06:53 UTC, merged

2020-12-01 16:23 UTC, audunn commented
@msJinLei  Hi do we have a milestone to see when this might be released?

2020-12-02 07:10 UTC, msJinLei commented
> @msJinLei Hi do we have a milestone to see when this might be released?

We are going to release it in 12/08 release.
BTW, please don't reply here since the PR is merged.  Your comment is probably missed. You can send email to us.