[WindowsIotServices]First preview release.
Azure/azure-powershell pull request #13609
Opened 2020-11-30 06:35 UTC by LucasYao93

## Description

First preview release.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-12-01 02:03 UTC, msJinLei commented
/azp run

2020-12-01 02:53 UTC, wyunchi-ms commented
/azp run

2020-12-01 07:00 UTC, wyunchi-ms reviewed
Please also modify `documentation/azure-powershell-modules.md`

2020-12-01 07:16 UTC, LucasYao93 commented
Have updated.

2020-12-01 07:17 UTC, LucasYao93 commented
> Have updated.

2020-12-01 07:17 UTC, LucasYao93 commented
> Please also modify `documentation/azure-powershell-modules.md`

Have updated.

2020-12-01 08:32 UTC, msJinLei requested changes

2020-12-01 08:36 UTC, LucasYao93 commented on src/WindowsIotServices/Changelog.md
> +## Version 0.1.0
We need to add  change log in Changelog.md ? so why remove it ?

2020-12-02 05:21 UTC, wyunchi-ms commented
/azp run

2020-12-02 05:45 UTC, dingmeng-xue commented on src/WindowsIotServices/Changelog.md
> +## Version 0.1.0
For the first release, it is fine.

2020-12-02 10:07 UTC, merged