[Az.RecoveryServices.Backup] Workload Recovery config, disallowing target item to be an availability group
Azure/azure-powershell pull request #13851
Opened 2020-12-28 05:50 UTC by hiaga

## Description
- Workload Recovery config, disallowing target item to be an availability group [bug fix]

## Checklist

- [Yes] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [Yes] The title of the PR is clear and informative
- [Yes] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [N/A] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [N/A] If applicable, the changes made in the PR have proper test coverage
- [N/A] For public API changes to cmdlets:
    - [N/A] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [N/A] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-12-28 10:38 UTC, hiaga commented
@msJinLei, @wyunchi-ms , @isra-fel : could someone please review this PR

2020-12-29 03:05 UTC, isra-fel requested changes

2020-12-29 03:05 UTC, isra-fel commented on src/RecoveryServices/RecoveryServices.Backup/Cmdlets/Restore/GetAzureRmRecoveryServicesBackupWorkloadRecoveryConfig.cs
> +                    if (string.Compare(((AzureWorkloadProtectableItem)TargetItem).ProtectableItemType,
please use `!string.Equals(...)` BTW

2020-12-29 03:05 UTC, isra-fel commented on src/RecoveryServices/RecoveryServices/ChangeLog.md
> +* Workload config, blocking target item to be an availability group.
How about
```suggestion
* Blocked getting workload config when target item is an availability group.
```

2020-12-30 09:12 UTC, isra-fel approved these changes
LGTM

2020-12-30 09:13 UTC, merged