General availability of module 'Az.ADDomainServices'
Azure/azure-powershell pull request #13856
Opened 2020-12-29 03:21 UTC by BethanyZhou

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2020-12-29 05:12 UTC, isra-fel commented
I notice the "General availability" in PR title. We are not going to GA (1.0.0) this module at first release, are we?

2020-12-29 05:22 UTC, BethanyZhou commented
It's a preview release.

2020-12-30 07:43 UTC, isra-fel requested changes

2020-12-30 10:31 UTC, Youri970410 commented on src/ADDomainService/readme.md
> +          }
Thanks for your suggestion~

2020-12-30 10:34 UTC, Youri970410 commented on src/ADDomainService/examples/New-AzADDomainService.md
> +New-AzADDomainService -name youriADdomain -ResourceGroupName youriAddomain -DomainName youriAddomain.com -ReplicaSet $NewAdDomain -debug
LGTM,thanks.

2020-12-30 10:39 UTC, Youri970410 commented on src/ADDomainService/readme.md
> +
Got it.Thanks~

2020-12-31 07:48 UTC, dolauli commented on src/ADDomainService/custom/New-AzADDomainService.ps1
> +.Example
Please clean empty examples

2020-12-31 07:51 UTC, dolauli commented on src/ADDomainService/custom/Update-AzADDomainService.ps1
> +PS C:\> {{ Add code here }}
The same as above

2020-12-31 07:55 UTC, dolauli requested changes
Generally looks good to me. And some minor changes are required.

2020-12-31 08:16 UTC, BethanyZhou commented
Thanks @dolauli 's advices, have updated codes.

2021-01-04 01:53 UTC, dolauli approved these changes
Looks good to me.

2021-01-04 04:54 UTC, isra-fel approved these changes

2021-01-04 04:55 UTC, merged