Generate code and test for HealthBot
Azure/azure-powershell pull request #13932
Opened 2021-01-12 06:57 UTC by Youri970410

## Description

Generate code and test for HealthBot

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-01-12 08:03 UTC, Youri970410 commented
/azp run

2021-01-12 08:12 UTC, Youri970410 commented
/azp run

2021-01-12 09:05 UTC, isra-fel requested changes

2021-01-12 09:05 UTC, isra-fel commented on src/HealthBot/examples/Get-AzHealthBot.md
> +```
Extra ```

2021-01-12 09:07 UTC, Youri970410 commented on src/HealthBot/examples/Get-AzHealthBot.md
> +```
Got it.thanks for your reminder.

2021-01-13 02:03 UTC, isra-fel commented
1. Please edit the base branch to `release-2021-01-19`
2. Please update this file as well: https://github.com/Azure/azure-powershell/blob/master/documentation/azure-powershell-modules.md

Otherwise LGTM.
 Thanks

2021-01-13 02:24 UTC, Youri970410 commented
@isra-fel Thanks,fixed.

2021-01-13 05:11 UTC, isra-fel approved these changes

2021-01-13 05:11 UTC, merged