[RecoveryServices.Backup] Added Zone Redundancy for Recovery Service Vaults
Azure/azure-powershell pull request #13962
Opened 2021-01-15 13:03 UTC by hiaga

## Description

Added Zone Redundancy for Recovery Service Vaults

## Checklist

- [Yes] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [Yes] The title of the PR is clear and informative
- [Yes] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [Yes] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [N/A] If applicable, the changes made in the PR have proper test coverage
- [Yes] For public API changes to cmdlets:
    - [Yes] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [N/A] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-01-16 11:20 UTC, hiaga commented
@isra-fel can you pls review.

2021-01-18 06:59 UTC, msJinLei requested changes

2021-01-18 06:59 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Backup.Test/RecoveryServices.Backup.Test.csproj
> +	<PackageReference Include="Microsoft.Azure.Management.RecoveryServices.Backup" Version="4.1.3-preview" />
Please revert the unnecessary change.

2021-01-18 06:59 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Test/RecoveryServices.Test.csproj
> +	<PackageReference Include="Microsoft.Azure.Management.RecoveryServices.Backup" Version="4.1.3-preview" />
Please revert the unnecessary change.

2021-01-18 06:59 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/Models/PSObjects.cs
> +        ZoneRedundant,
Please also update the related cmdlet help file.

2021-01-19 10:42 UTC, hiaga commented
@msJinLei : I've made the changes pls review again

2021-01-19 12:34 UTC, hiaga commented
@erich-wang: can you pls review

2021-01-20 02:57 UTC, msJinLei approved these changes

2021-01-21 07:30 UTC, merged