Register App Service Resources for Private Link Powershells
Azure/azure-powershell pull request #13967
Opened 2021-01-16 00:08 UTC by jiansong-msft

## Description
Register App Service Resources ('Microsoft.Web/sites', 'Microsoft.Web/hostingEnvironments') for Private Link Powershells

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-01-18 02:14 UTC, msJinLei commented
/azp run

2021-01-18 06:23 UTC, msJinLei requested changes

2021-01-18 06:23 UTC, msJinLei commented on src/Network/Network/ChangeLog.md
> +* Register App Service Resources ('Microsoft.Web/sites', 'Microsoft.Web/hostingEnvironments') for Private Link Powershells.
The private link registration is a special case where changelog description is no need.

2021-01-18 06:24 UTC, msJinLei requested changes
Please join https://github.com/Azure

2021-01-21 18:07 UTC, jiansong-msft commented
Hi Jin, wondering what should I do next? Is the CI running?

2021-01-21 23:23 UTC, msJinLei commented
/azp run

2021-01-22 03:19 UTC, msJinLei commented
/azp run azure-powershell - gen-security-tools

2021-01-22 03:20 UTC, msJinLei commented
/azp run

2021-01-22 04:14 UTC, msJinLei commented
/azp run azure-powershell - security-tools

2021-01-22 05:52 UTC, msJinLei approved these changes

2021-01-22 05:52 UTC, msJinLei commented
/azp run

2021-01-22 07:51 UTC, merged