Add WVD scalingPlan resource cmdlets
Azure/azure-powershell pull request #13991
Opened 2021-01-20 16:21 UTC by lordjeb

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-01-26 03:48 UTC, msJinLei requested changes
@lordjeb Please join the Azure organization https://github.com/Azure

2021-01-26 03:48 UTC, msJinLei commented on src/DesktopVirtualization/examples/Get-AzWvdScalingPlan.md
> +### Example 1: {{ Add title here }}
Please do not leave the example empty

2021-01-26 03:48 UTC, msJinLei commented on src/DesktopVirtualization/examples/New-AzWvdScalingPlan.md
> +PS C:\> {{ Add code here }}
Please do not leave the example empty

2021-01-26 03:48 UTC, msJinLei commented on src/DesktopVirtualization/examples/Remove-AzWvdScalingPlan.md
> +PS C:\> {{ Add code here }}
Please do not leave the example empty

2021-01-26 03:48 UTC, msJinLei commented on src/DesktopVirtualization/examples/Update-AzWvdScalingPlan.md
> +PS C:\> {{ Add code here }}
Please do not leave the example empty

2021-01-26 18:45 UTC, lordjeb commented
@msJinLei I have joined the Azure org and added the examples.

2021-01-28 07:50 UTC, msJinLei requested changes

2021-01-28 07:50 UTC, msJinLei commented on src/DesktopVirtualization/docs/Get-AzWvdScalingPlan.md
> +### Example 1: {{ Add title here }}
Please regenerate the code to update the docs

2021-01-28 07:50 UTC, msJinLei commented on src/DesktopVirtualization/docs/New-AzWvdScalingPlan.md
> +### Example 1: {{ Add title here }}
Please regenerate the code to update the docs

2021-01-28 07:50 UTC, msJinLei commented on src/DesktopVirtualization/docs/Remove-AzWvdScalingPlan.md
> +```powershell
Please regenerate the code to update the docs

2021-01-28 07:50 UTC, msJinLei commented on src/DesktopVirtualization/docs/Update-AzWvdScalingPlan.md
> +PS C:\> {{ Add code here }}
Please regenerate the code to update the docs

2021-01-28 16:49 UTC, lordjeb commented
@msJinLei Regenerated with examples included.

2021-02-01 05:48 UTC, msJinLei approved these changes

2021-02-01 05:48 UTC, merged