Azure Firewall - Data PIP removal for FT firewal
Azure/azure-powershell pull request #14138
Opened 2021-02-05 05:52 UTC by tinawu6

## Description

Feature: Enable firewall to be created and reconfigured without customer providing public IP.
This change relaxes the validation that enforces user to add a data PIP when creating a firewall. 
The new supported scenarios are: 
- Allowing user to create FT firewall without data PIP
- Allowing user to remove data PIP from FT firewall

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage

2021-03-02 22:25 UTC, iatodoro commented on src/Network/Network/AzureFirewall/NewAzureFirewallCommand.cs
> +            HelpMessage = "Allowing zero data Public IP for FT. The Public IP addresses must use Standard SKU and must belong to the same resource group as the Firewall.")]
The original help message is still accurate - the value of this parameter should be One or more PIPs

2021-03-02 22:26 UTC, iatodoro commented on src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
> +            if (publicIpAddresses != null && publicIpAddresses.Count() != 0)
Should be `> 0` to be entirely semantically correct.

2021-03-02 22:32 UTC, iatodoro commented on src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
> +                    Console.ForegroundColor = ConsoleColor.Yellow;
This message is not necessary - the Public IP is not associated with the subnet in any way.

2021-03-02 22:32 UTC, iatodoro commented on src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
> +                    Console.WriteLine($"Removing the Public IP Address associated with subnet {ipConfigToRemove.Subnet.Id}.");
This message is not necessary - the Public IP is not associated with the subnet in any way.

2021-03-02 22:36 UTC, iatodoro commented on src/Network/Network/Models/AzureFirewall/PSAzureFirewall.cs
> +                    this.ManagementIpConfiguration = null;
No longer needed as you're in the `else` part where ManagementIpConfiguration will always be null.

2021-03-12 02:20 UTC, isra-fel commented
/azp run

2021-03-12 02:28 UTC, isra-fel commented
As we talked in mail, please use the link https://aka.ms/AzureGithub to join Azure orgnization on Github. It marks you as a trusted developer so the CI pipelines can trigger automatically. @tinawu6

2021-03-15 02:25 UTC, isra-fel requested changes
Hi @tinawu6 , changing cmdlet syntax requires you to [regenerate help document](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)
In this case, you should expect [New-AzFirewall.md](https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzFirewall.md) to be updated after regeneration.
Other changes look good to me

2021-03-16 05:16 UTC, isra-fel approved these changes

2021-03-16 05:30 UTC, VeryEarly approved these changes

2021-03-16 06:40 UTC, merged