Support Reset connection for VNG and Vwan
Azure/azure-powershell pull request #14225
Opened 2021-02-18 08:37 UTC by akshatkale

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-02-22 06:15 UTC, VeryEarly requested changes
local SDK needed to be check into tools/localfeed.

There is another PR: https://github.com/Azure/azure-powershell/pull/14182

is going to check in local SDK, please make sure yours will be compatible with his.

2021-02-23 02:17 UTC, VeryEarly commented
please sync with network-november branch, you might not need to check in the local SDK..

2021-02-24 00:01 UTC, akshatkale commented
> please sync with network-november branch, you might not need to check in the local SDK..

@VeryEarly - Local SDK from https://github.com/Azure/azure-powershell/pull/14182 wasn't compatible with my changes so checked-in new Network SDK version.

2021-02-24 03:18 UTC, VeryEarly commented on src/Network/Network/Cortex/VpnConnection/ResetAzVpnSiteLinkConnectionCommand.cs
> +        DefaultParameterSetName = "ByName"),
```suggestion
        DefaultParameterSetName = "ByName",
        SupportsShouldProcess = true),
```

2021-02-24 03:18 UTC, VeryEarly commented on src/Network/Network/VirtualNetworkGatewayConnection/ResetAzureVirtualNetworkGatewayConnectionCommand.cs
> +    [Cmdlet("Reset", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "VirtualNetworkGatewayConnection", DefaultParameterSetName = "ByName"), OutputType(typeof(void))]
```suggestion
    [Cmdlet("Reset", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "VirtualNetworkGatewayConnection", DefaultParameterSetName = "ByName", SupportsShouldProcess = true), OutputType(typeof(void))]
```

2021-02-24 05:08 UTC, akshatkale commented on src/Network/Network/Cortex/VpnConnection/ResetAzVpnSiteLinkConnectionCommand.cs
> +        DefaultParameterSetName = "ByName"),
[Updated](https://github.com/Azure/azure-powershell/pull/14225/commits/cd04b1c4cc06f8a6a321139efa1037071f0ae76f#diff-29b5a4816afbb7a2db6e193d1ea4df4317c35a92a630490870336398d5927adbR15)

2021-02-24 05:08 UTC, akshatkale commented on src/Network/Network/VirtualNetworkGatewayConnection/ResetAzureVirtualNetworkGatewayConnectionCommand.cs
> +    [Cmdlet("Reset", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "VirtualNetworkGatewayConnection", DefaultParameterSetName = "ByName"), OutputType(typeof(void))]
[Updated](https://github.com/Azure/azure-powershell/pull/14225/commits/cd04b1c4cc06f8a6a321139efa1037071f0ae76f#diff-0d4fcb04a4e383d6b25257ec9d795c090e84df70b7b2bf97796549f3e23a13baR23)

2021-02-24 07:34 UTC, akshatkale commented
Hi @VeryEarly, can we get this PR checked in today if everything looks good?

2021-02-25 04:40 UTC, VeryEarly approved these changes

2021-02-25 04:40 UTC, merged