Vwan :update test add recording
Azure/azure-powershell pull request #14379
Opened 2021-03-01 23:17 UTC by neethirshetty

## Description

updated the p2sCrud test and added a recording. Also adding update command fix.
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-03-01 23:28 UTC, Nilambari commented on src/Network/Network/Cortex/VpnServerConfiguration/UpdateAzureRmVpnServerConfigurationCommand.cs
> +                    if (RadiusServerList != null && this.RadiusServerList.Count() > 0)
this.RadiusServerList

2021-03-02 00:12 UTC, Nilambari requested changes

2021-03-02 00:12 UTC, Nilambari commented
Please take a look at comments. Thanks!

2021-03-02 00:31 UTC, neethirshetty commented on src/Network/Network.Test/ScenarioTests/CortexTests.ps1
> +	$VpnServerConfigurationMultiAuthName = Get-ResourceName
actual file has the correct indentation. In the UI, because of the + symbol it seems like there is extra space

2021-03-02 00:34 UTC, neethirshetty commented on src/Network/Network/Cortex/VpnServerConfiguration/UpdateAzureRmVpnServerConfigurationCommand.cs
> +                    vpnServerConfigurationToUpdate.AadAuthenticationParameters = null;
yes

2021-03-02 00:36 UTC, neethirshetty commented on src/Network/Network/Cortex/VpnServerConfiguration/UpdateAzureRmVpnServerConfigurationCommand.cs
> +                        vpnServerConfigurationToUpdate.RadiusServers = null;
yes

2021-03-02 00:37 UTC, neethirshetty commented on src/Network/Network/Cortex/VpnServerConfiguration/UpdateAzureRmVpnServerConfigurationCommand.cs
> +                        vpnServerConfigurationToUpdate.RadiusServerAddress = null;
yes

2021-03-02 00:53 UTC, nilambarideshpande commented
LGTM.

2021-03-02 00:54 UTC, nilambarideshpande submitted a review, later dismissed

2021-03-02 23:04 UTC, Nilambari approved these changes

2021-03-04 02:30 UTC, VeryEarly commented
please target your feature to network-november branch

2021-03-04 05:15 UTC, neethirshetty commented
will create a new one to merge to network-november as suggested

2021-03-04 05:15 UTC, closed without merging