Remove-AzVmssDataDisk bug fix
Azure/azure-powershell pull request #14553
Opened 2021-03-15 22:00 UTC by grizzlytheodore

Addressing https://github.com/Azure/azure-powershell/issues/13368  

According to Jun Wang, to delete the last Data disk, we need to send an empty array as datadisks.

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-03-16 08:40 UTC, BethanyZhou commented on src/Compute/Compute/ChangeLog.md
> +* Fixing `Remove-AzVmssDataDisk` bug. Now the cmdlet will work when there is just one data disk attached to a Vmss.
Suggested to "Fixed a bug when 1 data disk attached to VMSS for `Remove-AzVmssDataDisk` [#13368]"

2021-03-16 09:15 UTC, BethanyZhou requested changes
Hi @grizzlytheodore , your change for Remove-AzVmssDataDisk results in a test case src/Compute/Compute.Test/ScenarioTests/VirtualMachineProfileTests.ps1 failed. Is that reasonable? Please check it. If yes, please re-record the test case.

2021-03-16 13:50 UTC, grizzlytheodore commented
@BethanyZhou no the test should pass. the update made in this PR should not affect that test at all. it is passing when I run it locally. let's see if it passes here if we run it again

2021-03-17 02:38 UTC, BethanyZhou approved these changes

2021-03-17 02:39 UTC, BethanyZhou commented
LGTM. Seems like the failed test is a random issue.

2021-03-17 02:41 UTC, merged