Apply credential factory to SilentAuthenticator
Azure/azure-powershell pull request #14567
Opened 2021-03-16 14:43 UTC by msJinLei

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-03-18 15:30 UTC, msJinLei commented on tools/ScenarioTest.ResourceManager/Mocks/MockTokenAuthenticationFactory.cs
> +            return new RenewingTokenCredential(Token);
Revert

2021-03-18 15:31 UTC, msJinLei commented on src/Aks/Aks.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Azure.Core", "..\..\..\azure-sdk-for-net\sdk\core\Azure.Core\src\Azure.Core.csproj", "{773A5AC7-3CD2-4D80-84A0-01AAA8C79947}"
Revert

2021-03-23 03:21 UTC, msJinLei commented
/azp run azure-powershell - powershell-core

2021-03-25 08:59 UTC, msJinLei commented
/azp run azure-powershell - windows-powershell

2021-03-26 04:03 UTC, erich-wang requested changes

2021-03-26 04:03 UTC, erich-wang commented on src/Accounts/Authentication/Factories/ClientFactory.cs
> +                    handlerList.AddRange(handlers);
Is this change necessary?

2021-03-26 04:03 UTC, erich-wang commented on src/Accounts/Authenticators/SilentAuthenticator.cs
> +            var cacheCredential = azureCredentialFactory.CreateCredentialsFromOptions();
Is this change necessary?

2021-03-26 04:12 UTC, erich-wang commented on src/Accounts/Authentication/Utilities/Base64UrlHelpers.cs
> +    public static class Base64UrlHelpers
use the one in common library

2021-03-26 04:25 UTC, erich-wang commented on src/Accounts/Authenticators/MsalAccessToken.cs
> +            //TODO: Credential may not support
check?

2021-03-26 07:15 UTC, msJinLei commented on src/Accounts/Authenticators/SilentAuthenticator.cs
> +            //AzureSession.Instance.TryGetComponent(nameof(PowerShellTokenCache), out PowerShellTokenCache tokenCache);
revert

2021-03-26 08:29 UTC, msJinLei commented on tools/ScenarioTest.ResourceManager/Mocks/MockTokenAuthenticationFactory.cs
> +            return new RenewingTokenCredential(new ExternalAccessToken(accessToken));
Check the change

2021-07-05 05:27 UTC, isra-fel commented
Let me move the pull request to draft state. Please feel free to mark it "Ready for review" when you feel comfortable. Thanks

2021-07-05 05:37 UTC, msJinLei commented
> Let me move the pull request to draft state. Please feel free to mark it "Ready for review" when you feel comfortable. Thanks

It is not because the feature is still in development that the PR is not merged. It is because the sever side is not ready that we cannot release the feature.

2021-07-05 07:23 UTC, isra-fel commented
> It is not because the feature is still in development that the PR is not merged. It is because the sever side is not ready that we cannot release the feature.

Got it. It's just easier for maintanence. Thanks for understanding 😀

2021-07-19 07:28 UTC, merged