Change default Size value in New-AzVM to Standard_D2S_v2
Azure/azure-powershell pull request #14622
Opened 2021-03-23 14:57 UTC by Sandido

Dingmeng saw an increase in failure rates for the New-AzVM cmdlet in the PS telemetry. Adam investigated and saw that the Size parameter has a hardcoded default value of Standard_Ds1_v2. This Size can be made unavailable in certain regions due to changes in activity in that region. If it is unavailable, the New-AzVM cmdlet fails if it is not provided a Size value. This occurs in its DiskFile and Simple parameter sets. 

After a discussion with the Compute PMs, PS Lead Dingmeng, and CLI team, we determined the best solution for now is to change the hardcoded value to a more widely available size, Standard_D2s_v2. 

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-03-24 05:28 UTC, BethanyZhou commented
Hi @Sandido , please re-record test cases for src\Compute\Compute.Test\ScenarioTests\VirtualMachineTests.cs

2021-03-26 05:27 UTC, BethanyZhou commented
@Sandido , It seems like there are some errors in the VM test cases. Could you configure it out so that the CI can be passed. I guess re-recording test cases for src\Compute\Compute.Test\ScenarioTests\VirtualMachineTests.cs would be work.

2021-03-26 19:09 UTC, Sandido commented
> @Sandido , It seems like there are some errors in the VM test cases. Could you configure it out so that the CI can be passed. I guess re-recording test cases for src\Compute\Compute.Test\ScenarioTests\VirtualMachineTests.cs would be work.

@BethanyZhou , looks like when I record the new test, it succeeds. But whenever I try to record a test then immediately running it in Playback, it fails bc it is unable to find a Get call on the Recorded file.

2021-03-29 02:02 UTC, BethanyZhou commented
Have you copy the new generated json files under bin/SessionRecords folder to the SessionRecords folder in Compute.Test.csproj?

2021-03-30 18:50 UTC, Sandido commented
Looks like I needed to provide a DomainNameLabel value in New-AzVM. It defaults to a value in Record, but then on Playback it defaults to another value. I added DomainNameLabel as a parameter to fix it.

2021-03-31 02:44 UTC, BethanyZhou requested changes

2021-03-31 02:44 UTC, BethanyZhou commented on src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
> +    $loc = "eastus";#Get-ComputeVMLocation;
Hi @Sandido , please remove uncommented codes.

2021-04-06 14:42 UTC, Sandido commented on src/Compute/Compute.Test/ScenarioTests/VirtualMachineTests.ps1
> +    $loc = "eastus";#Get-ComputeVMLocation;
updated.

2021-04-07 06:02 UTC, BethanyZhou approved these changes
LGTM

2021-04-07 14:56 UTC, Sandido commented
@BethanyZhou , I'm confused. This PR had no errors to Master, and now it has errors against the release branch. The error in the PR check does not look related to my changes. 
Why is this rebased to the release branch? 

Current PR check error:
/home/vsts/work/1/s/build.proj(182,5): error MSB3073: The command "dotnet sln /home/vsts/work/1/s/artifacts/Azure.PowerShell.sln add "/home/vsts/work/1/s/src/ApplicationInsights/ApplicationInsights/ApplicationInsights.csproj"" exited with code 139.
2021-04-07T06:08:55.5898848Z ##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
2021-04-07T06:08:55.5914545Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting

2021-04-07 14:56 UTC, Sandido commented
/azp run

2021-04-08 02:09 UTC, BethanyZhou commented
Hi @Sandido , this error is caused by the ADO environment, which is a random failure.
```
  Segmentation fault (core dumped)
/home/vsts/work/1/s/build.proj(182,5): error MSB3073: The command "dotnet sln /home/vsts/work/1/s/artifacts/Azure.PowerShell.sln add "/home/vsts/work/1/s/src/RecoveryServices/RecoveryServices.Backup.Providers/RecoveryServices.Backup.Providers.csproj"" exited with code 139.
```
Let's re-run all pipelines.

2021-04-08 02:09 UTC, BethanyZhou commented
/azp run

2021-04-08 02:17 UTC, BethanyZhou commented
/azp run

2021-04-08 04:01 UTC, erich-wang commented
Force merge due to known CI issue

2021-04-08 04:01 UTC, merged