Added deprecation message to Invoke-AzStorageSyncFileRecall
Azure/azure-powershell pull request #14637
Opened 2021-03-25 18:19 UTC by mikefrobbins

## Description

Added deprecation message to Invoke-AzStorageSyncFileRecall

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-03-26 08:49 UTC, BethanyZhou requested changes

2021-03-26 08:49 UTC, BethanyZhou commented on src/StorageSync/StorageSync/help/Invoke-AzStorageSyncFileRecall.md
> +> `Invoke-AzStorageSyncFileRecall` is deprecated. Please use [Invoke-StorageSyncFileRecall](/azure/storage/files/storage-sync-how-to-manage-tiered-files#how-to-recall-a-tiered-file-to-disk).
Hi @mikefrobbins , the link for Invoke-StorageSyncFileRecall seems broken, please replace it with a valid link.

2021-03-26 14:17 UTC, mikefrobbins commented
@BethanyZhou It's a relative link and works once published to docs [as shown in the 5.7.0 version](https://docs.microsoft.com/en-us/powershell/module/az.storagesync/invoke-azstoragesyncfilerecall?view=azps-5.7.0). Using a relative link is recommended because it also works in air-gapped environments.

2021-03-29 01:54 UTC, BethanyZhou commented
Got it. LGTM. Thanks.

2021-03-29 01:54 UTC, BethanyZhou approved these changes

2021-03-29 02:21 UTC, erich-wang commented
Force merge because of known CI issue.

2021-03-29 02:22 UTC, merged