Updating change log to include TrustedLaunch changes for April 2021 release
Azure/azure-powershell pull request #14677
Opened 2021-04-02 03:31 UTC by sirfamelin

## Description

Updating change log to include TrustedLaunch related cmdlets for April 2021 release

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-04-02 04:28 UTC, BethanyZhou approved these changes

2021-04-02 04:33 UTC, BethanyZhou requested changes
Please remove the content added into https://github.com/Azure/azure-powershell/blob/master/ChangeLog.md in previous pr: https://github.com/Azure/azure-powershell/pull/14479

2021-04-02 15:32 UTC, sirfamelin commented
> Please remove the content added into https://github.com/Azure/azure-powershell/blob/master/ChangeLog.md in previous pr: #14479

Removed.

2021-04-05 17:25 UTC, sirfamelin commented
/azp run

2021-04-06 01:47 UTC, BethanyZhou approved these changes

2021-04-06 02:44 UTC, merged