Changed output of ResourceGraph cmdlet to a custom class
Azure/azure-powershell pull request #14789
Opened 2021-04-20 11:52 UTC by fenwickt

## Description

Changed an output of Search-AzGraph cmdlet to a custom class PSResourceGraphResponse.
Previous cmdlet output is now under Data property.
An extra property SkipToken is added so that users can leverage it for getting paginated queries.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-04-20 19:08 UTC, dramuy commented on src/ResourceGraph/ResourceGraph/Models/PSResourceGraphResponse.cs
> +    public class PSResourceGraphResponse
>PSResourceGraphResponse [](http://example.com/codeflow?start=17&length=23)

now we have a response object; should we include total records and count fields as well.

2021-04-20 19:09 UTC, dramuy approved these changes
:shipit:

2021-04-22 02:23 UTC, VeryEarly requested changes

2021-04-22 02:23 UTC, VeryEarly commented on src/ResourceGraph/ResourceGraph/ChangeLog.md
> +* Output has changed to a PSResourceGraphResponse class. Previous output is now under Data property.
```suggestion
* Changed output of `Search-AzGraph` to PSResourceGraphResponse which wrapped previous output under Data property.
```

2021-04-22 02:23 UTC, VeryEarly commented
/azp run

2021-04-25 03:02 UTC, VeryEarly approved these changes

2021-04-26 02:19 UTC, merged