fix the issue that detected special commit incorrectly in use GenerateExternalContributors.ps1
Azure/azure-powershell pull request #14828
Opened 2021-04-26 06:28 UTC by LucasYao93

…eExternalContributors.ps1.

## Description

Fix #14724

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-04-26 08:00 UTC, dingmeng-xue requested changes

2021-04-26 08:00 UTC, dingmeng-xue commented on tools/GenerateExternalContributors.ps1
> +Write-Debug 'Output exteneral contributors infomation.'
```suggestion
Write-Debug 'Output external contributors information.'
```

2021-04-26 08:04 UTC, LucasYao93 commented on tools/GenerateExternalContributors.ps1
> +Write-Debug 'Output exteneral contributors infomation.'
Done

2021-04-26 08:23 UTC, wyunchi-ms approved these changes

2021-04-26 08:23 UTC, wyunchi-ms commented
/azp run

2021-04-26 10:06 UTC, dingmeng-xue submitted a review, later dismissed

2021-04-28 02:33 UTC, wyunchi-ms commented
/azp run

2021-04-28 02:42 UTC, wyunchi-ms commented
/azp run

2021-04-28 07:55 UTC, merged