Retrytime
Azure/azure-powershell pull request #14950
Opened 2021-05-11 07:16 UTC by msJinLei

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-05-12 03:15 UTC, wyunchi-ms commented
LGTM

2021-05-12 08:41 UTC, erich-wang requested changes

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +    static class ServiceClientExtension
Prefer to add access modifier **internal**

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +        class HttpRetryTimes
Prefer to add **private**

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +            static public int? AZURE_PS_HTTP_MAX_RETRIES
Prefer to use Pascal style for property name, e.g. AzurPsHttpMaxRetries.

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +            static private int? TryGetValue(GetEnvironmentVariable GetEnvVariable)
IMO, there is no need to use delegate here as it does not improve code readability . How about use TryGetValue(string environmentName)?

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +                    int _;
Prefer to use meaningful name instead of `_`

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +                TimeSpan DefaultBackoffDelta = new TimeSpan(0, 0, 10);
Please use camelCase for local variables

2021-05-12 08:41 UTC, erich-wang commented on src/Accounts/Authentication/Extensions/ClientFactoryExtension.cs
> +    static class ServiceClientExtension
If possible, we prefer to use class name same as file name

2021-05-14 00:56 UTC, erich-wang approved these changes

2021-05-14 00:56 UTC, merged