[Tools]Throw exception if a solution reference a not exist csproj.
Azure/azure-powershell pull request #15101
Opened 2021-05-25 08:48 UTC by wyunchi-ms

## Description

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-05-25 08:48 UTC, wyunchi-ms commented
/azp run

2021-05-25 08:55 UTC, wyunchi-ms commented
/azp run

2021-05-27 08:09 UTC, msJinLei requested changes

2021-05-27 08:09 UTC, msJinLei commented on tools/CreateFilterMappings.ps1
> +    $CommonProjectsToIgnore = @("ScenarioTest.ResourceManager", "TestFx", "Tests", "Test", "src", "tools" )
Can you use a more explicit condition to filter csproj wanted?

2021-06-09 05:54 UTC, msJinLei submitted a review, later dismissed

2021-06-18 09:10 UTC, BethanyZhou approved these changes
LGTM

2021-06-18 09:11 UTC, merged