cmdlets for new compute resource: SSH Public Key
Azure/azure-powershell pull request #15120
Opened 2021-05-26 19:42 UTC by grizzlytheodore

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-05-27 06:39 UTC, msJinLei commented
@grizzlytheodore Have you submitted a cmdlet review? Could you refer its ID here?
Please fix the failed test. It seems that you need to re-record that test case.

2021-05-27 21:34 UTC, grizzlytheodore commented
@MS-syh2qs  I am not sure why the test from the CI checks is failing. 
Error messages:
 Caught Exception: System.Management.Automation.CommandNotFoundException: The term 'Test-SshKey' is not recognized as the name of a cmdlet, function, script file, or operable program.
2021-05-27T20:20:34.7366006Z    Check the spelling of the name, or if a path was included, verify that the path is correct and try again.


I've double-checked spelling and even capitalization. I am not sure why the CI check does not recognize the 'Test-SshKey' in the sshKeyTests.ps1 file. It passed on Windows tests. But it is failing for Linux. 

Could you provide some insight?

2021-05-28 03:29 UTC, msJinLei commented
cmdlet review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/907

2021-05-31 08:17 UTC, msJinLei commented
> @MS-syh2qs I am not sure why the test from the CI checks is failing.
> Error messages:
> Caught Exception: System.Management.Automation.CommandNotFoundException: The term 'Test-SshKey' is not recognized as the name of a cmdlet, function, script file, or operable program.
> 2021-05-27T20:20:34.7366006Z Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> 
> I've double-checked spelling and even capitalization. I am not sure why the CI check does not recognize the 'Test-SshKey' in the sshKeyTests.ps1 file. It passed on Windows tests. But it is failing for Linux.
> 
> Could you provide some insight?

no idea yet...

2021-06-01 19:41 UTC, msJinLei commented
@grizzlytheodore Try to use SshKeyTests(capitalize s)

2021-06-02 02:05 UTC, msJinLei requested changes

2021-06-02 02:05 UTC, msJinLei commented on src/Compute/Compute/Usage/GetAzureSshKey.cs
> +        public string Name { get; set; }
Please also provide byResourceId parameter set for this cmdlet

2021-06-02 02:05 UTC, msJinLei commented on src/Compute/Compute/Usage/RemoveAzureSshKey.cs
> +        public string Name { get; set; }
Please also provide byResourceId and ByInputObject parameter sets for this cmdlet

2021-06-02 02:05 UTC, msJinLei commented on src/Compute/Compute/Usage/UpdateAzureSshKey.cs
> +        public string PublicKey { get; set; }
Please also provide byResourceId and ByInputObject parameter sets for this cmdlet

2021-06-02 18:02 UTC, grizzlytheodore commented
@msJinLei @dingmeng-xue if you are going to enforce parameter sets for byResourceId and byInputObject, I believe it should be enforced at the design spec level

2021-06-02 22:28 UTC, grizzlytheodore commented
new parameter sets were added

2021-06-03 17:42 UTC, msJinLei approved these changes

2021-06-03 17:42 UTC, merged