Add edge zone parameter to public ip address cmdlet
Azure/azure-powershell pull request #15230
Opened 2021-06-09 19:17 UTC by wdehrich

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-06-10 09:38 UTC, BethanyZhou requested changes

2021-06-10 09:38 UTC, BethanyZhou commented on src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.ps1
> +        Assert-AreEqual $publicIP.ExtendedLocation.Type 'EdgeZone'
Please correct indents.

2021-06-10 16:43 UTC, wdehrich commented on src/Network/Network.Test/ScenarioTests/PublicIpAddressTests.ps1
> +        Assert-AreEqual $publicIP.ExtendedLocation.Type 'EdgeZone'
fixed

2021-06-11 01:52 UTC, BethanyZhou requested changes
Hi @wdehrich , 

1. Please add change log for your change
2. Please update the PR title because it looks like it mismatches with what you are doing.
3. Please check all items in our checklist in PR board

2021-06-11 03:31 UTC, BethanyZhou approved these changes
LGTM

2021-06-11 04:38 UTC, BethanyZhou approved these changes

2021-06-11 06:07 UTC, merged