[SQL] Bug fix for UMI
Azure/azure-powershell pull request #15338
Opened 2021-06-23 16:44 UTC by viparek

## Description

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-06-28 07:33 UTC, BethanyZhou requested changes

2021-06-28 07:33 UTC, BethanyZhou commented on src/Sql/Sql/Common/ResourceIdentityHelper.cs
> +        {
Looks like this method is never used, please have a look

2021-06-28 07:33 UTC, BethanyZhou commented on src/Sql/Sql/ManagedInstance/Cmdlet/NewAzureSqlManagedInstance.cs
> +        public Object[] IdentityType { get; set; }
Object[] is not allowed in IdentityType either. Delete SystemAssignedUserAssigned will cause breaking change

2021-06-29 02:17 UTC, BethanyZhou reviewed
Hi @viparek , Can `New-AzSqlInstance -IdentityType` handle `SystemAssignedUserAssigned` now?  I mean even we don't provide `SystemAssignedUserAssigned` in `ArgumentCompleter` anymore, we should be able to handle it in our logic to avoid breaking change. e.g. previous PS script can work as before.

2021-06-29 02:17 UTC, BethanyZhou commented on src/Sql/Sql/Common/ResourceIdentityHelper.cs
> +            /*
Please remove commented lines

2021-06-29 02:57 UTC, viparek commented
> Hi @viparek , Can `New-AzSqlInstance -IdentityType` handle `SystemAssignedUserAssigned` now? I mean even we don't provide `SystemAssignedUserAssigned` in `ArgumentCompleter` anymore, we should be able to handle it in our logic to avoid breaking change. e.g. previous PS script can work as before.

It is by design that we are not supporting 'SystemAssignedUserAssigned`. We do not want to create confusion with the customers by adding both. Also like we discussed earlier, IdentityType is a brand new param added in the last PS release, and the feature it supports is also not released yet. So this change will not have any impact.

2021-06-29 03:11 UTC, BethanyZhou commented
> It is by design that we are not supporting 'SystemAssignedUserAssigned`. We do not want to create confusion with the customers by adding both. Also like we discussed earlier, IdentityType is a brand new param added in the last PS release, and the feature it supports is also not released yet. So this change will not have any impact.

Yes, I know we should respect the design in swagger, handle 'SystemAssignedUserAssigned' in PS logic is a workaround to avoid breaking change. Please reply email to track this discussion about the workaround, thanks.

One question, for "SystemAssigned,UserAssigned", is it should be "SystemAssigned, UserAssigned"? Is there any blank between ""SystemAssigned," and "UserAssigned" in swagger? I saw "SystemAssigned, UserAssigned" in other swaggers.

2021-06-29 09:20 UTC, BethanyZhou approved these changes

2021-06-29 09:32 UTC, BethanyZhou requested changes
Please update the description in [New-AzSqlServer.md](https://github.com/Azure/azure-powershell/blob/ab497db062ef15f3b8b07f0aa02055d780aea1a3/src/Sql/Sql/help/New-AzSqlServer.md#-identitytype) and [New-AzSqlInstance.md](https://github.com/Azure/azure-powershell/blob/ab497db062ef15f3b8b07f0aa02055d780aea1a3/src/Sql/Sql/help/New-AzSqlInstance.md#-identitytype) as well

2021-06-30 05:33 UTC, BethanyZhou submitted a review, later dismissed

2021-06-30 06:37 UTC, BethanyZhou approved these changes

2021-06-30 08:48 UTC, merged