[Storage] Support VLW
Azure/azure-powershell pull request #15545
Opened 2021-07-26 09:48 UTC by blueww

## Description

The design pass review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/959

it's based on updated Az.Storage-preview branch with https://github.com/Azure/azure-powershell/pull/15544
After #15544 merged , this PR should have only 1 commit.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-07-27 01:30 UTC, blueww commented
/azp run

2021-07-27 02:20 UTC, isra-fel commented
Hi Wei Wei, I'm not sure why this PR still has 2000+ changed files. I suggest open a new one and cherry-pick your commit.

2021-07-27 04:44 UTC, isra-fel commented
/azp run

2021-07-30 08:52 UTC, isra-fel requested changes

2021-07-30 09:02 UTC, blueww commented on src/Storage/Storage/Blob/Cmdlet/SetAzStorageBlobImmutabilityPolicy.cs
> +        [ValidateSet("Unlocked", "Locked", "Mutable", IgnoreCase = true)]
fixed

2021-08-03 05:59 UTC, VeryEarly approved these changes

2021-08-03 06:00 UTC, merged