Adding Azure Lab Services generated sdk
Azure/azure-powershell pull request #16096
Opened 2021-10-14 22:47 UTC by RogerBestMsft

## Description

Adding Lab Services to PowerShell SDK

## Checklist

- [x ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x ] The title of the PR is clear and informative
- [x ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - Azure/azure-powershell-cmdlet-review-pr#1052
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-10-15 07:41 UTC, BethanyZhou commented
Design doc: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1052

2021-10-19 02:32 UTC, BethanyZhou commented
/azp run

2021-10-21 04:40 UTC, BethanyZhou commented
Hi @RogerBestMsft , please check following issues:
```
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.LabServices","Add-AzLabServicesUserQuota","Add-AzLabServicesUserQuota","1","8100","Add-AzLabServicesUserQuota Does not support ShouldProcess but the cmdlet verb Add indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"
  "Az.LabServices","New-AzLabServicesSchedule","New-AzLabServicesSchedule","1","8410","Parameter Notes of cmdlet New-AzLabServicesSchedule does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name."
  "Az.LabServices","Redeploy-AzLabServicesVM","Redeploy-AzLabServicesVM","1","8300","Redeploy-AzLabServicesVM uses the verb 'Redeploy', which is not on the list of approved verbs for PowerShell commands. Use the cmdlet 'Get-Verb' to see the full list of approved verbs and consider renaming the cmdlet.","Consider renaming the cmdlet to use an approved verb for PowerShell."
  "Az.LabServices","Start-AzLabServicesUserVM","Start-AzLabServicesUserVM","1","8100","Start-AzLabServicesUserVM Does not support ShouldProcess but the cmdlet verb Start indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"
  "Az.LabServices","Stop-AzLabServicesUserVM","Stop-AzLabServicesUserVM","1","8100","Stop-AzLabServicesUserVM Does not support ShouldProcess but the cmdlet verb Stop indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"
  "Az.LabServices","Sync-AzLabServicesLabUsers","Sync-AzLabServicesLabUsers","1","8400","Sync-AzLabServicesLabUsers uses the noun 'AzLabServicesLabUsers', which does not follow the enforced naming convention of using a singular noun for a cmdlet name.","Consider using a singular noun for the cmdlet name."

```

2021-10-22 01:59 UTC, BethanyZhou commented
For Redeploy-AzLabServicesVM, which is not on the list of approved verbs for PowerShell commands. I recommend to rename it as Invoke-AzLabServicesVMRedeployment.

2021-11-08 09:36 UTC, isra-fel requested changes

2021-11-08 09:36 UTC, isra-fel commented on src/LabServices/readme.md
> +  - https://github.com/Azure/azure-rest-api-specs/blob/6d7653ffd37cdc781e16202306567e355b45ebf8/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/VirtualMach
Save some repeat
```suggestion
branch: 6d7653ffd37cdc781e16202306567e355b45ebf8
input-file:
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/Images.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/LabPlans.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/LabServices.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/Labs.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/OperationResults.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/Schedules.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/Users.json
  - $(repo)/specification/labservices/resource-manager/Microsoft.LabServices/preview/2021-10-01-preview/VirtualMachines.json
```

2021-11-09 09:01 UTC, isra-fel approved these changes
Looks good!

2021-11-09 09:02 UTC, merged

2021-11-09 09:08 UTC, isra-fel commented
BTW, could you give me a brief changelog text that describes the initial release? It'll appear on powershellgallery.com

Something like
```
This is the initial version of Az.LabServices. It contains the following features:
- xxx
- xxx
```