[Synapse] Spark Configuration cmdlets
Azure/azure-powershell pull request #16156
Opened 2021-10-21 09:02 UTC by yanjungao718

## Description

Add Synapse Spark Configuration related cmdlets:
`New-AzSynapseSparkConfiguration`
`Get-AzSynapseSparkConfiguration`
`Export-AzSynapseSparkConfiguration`
`Remove-AzSynapseSparkConfiguration`

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1057
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-10-21 23:57 UTC, BethanyZhou commented
@yanjungao718 , please fix  signature issue first:  
```
"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.Synapse","Microsoft.Azure.Commands.Synapse.ExportAzureSynapseSparkConfiguration","Export-AzSynapseSparkConfiguration","1","8100","Export-AzSynapseSparkConfiguration Does not support ShouldProcess but the cmdlet verb Export indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"
```

2021-11-10 16:04 UTC, isra-fel requested changes

2021-11-11 02:18 UTC, yanjungao718 commented on src/Synapse/Synapse/Az.Synapse.psd1
> +    - Added ''Set-AzSynapseSqlScript'' cmdlet
updated, please help to review, thanks.

2021-11-11 02:19 UTC, yanjungao718 commented on src/Synapse/Synapse/ChangeLog.md
> +	- Added `Remove-AzSynapseSparkConfiguration` cmdlet
updated, please help to review, thanks.

2021-11-11 02:54 UTC, isra-fel approved these changes
LGTM

2021-11-11 02:55 UTC, isra-fel commented
/azp run azure-powershell - security-tools

2021-11-11 06:16 UTC, merged