Compute Generation PR
Azure/azure-powershell pull request #16235
Opened 2021-10-26 22:48 UTC by haagha

## Description

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/756 (Partial implementation)

Set-AzVMRunCommand
Get-AzVMRunCommand
Remove-AzVMRunCommand
Set-AzVmssVMRunCommand   
Remove-AzVmssVMRunCommand
Get-AzVmssVMRunCommand

## Checklist

- [x ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x ] If applicable, the changes made in the PR have proper test coverage
- [x ] For public API changes to cmdlets:
    - [x ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-11-01 02:01 UTC, isra-fel requested changes

2021-11-01 02:01 UTC, isra-fel commented on src/Compute/Compute.Autorest/README.md
> +  - https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/runCommands.json
After this change please run autorest and build-module.ps1 again to make sure everything is OK

2021-11-02 00:07 UTC, haagha commented on src/Compute/Compute.Autorest/README.md
> +  #    subject: VirtualMachine|AvailabilitySet|DedicatedHost|Image|Operation|ProximityPlacementGroup|RestorePoint|RestorePointCollection|Usage|#CapacityReservationGroup|CapacityReservation
fixed

2021-11-02 00:07 UTC, haagha commented on src/Compute/Compute.Autorest/examples/Set-AzVmssVMRunCommand.md
> +### Example 1: {{ Add title here }}
fixed

2021-11-02 02:42 UTC, isra-fel approved these changes
Looks good

2021-11-02 02:58 UTC, isra-fel requested changes
Hold on for #16307

2021-11-02 05:13 UTC, isra-fel approved these changes
As discussed with @haagha we will not wait for #16311

2021-11-02 05:13 UTC, merged