Connect websocket for Invoke-AzContainerInstanceCommand
Azure/azure-powershell pull request #16350
Opened 2021-11-08 04:57 UTC by BethanyZhou

## Description
Connect websocket for Invoke-AzContainerInstanceCommand
- Added PassThru to return last execution result when the command succeeds
- Set default value for TerminalSizeCol and TerminalSizeRow
- Implement few customized features by directive

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-11-11 09:13 UTC, BethanyZhou commented
/azp run

2021-11-16 08:27 UTC, isra-fel requested changes
Please also fix the casing of "docs/new-AzContainerInstanceHttpHeaderObject.md"

2021-11-16 08:31 UTC, BethanyZhou commented on src/ContainerInstance/custom/InvokeAzContainerInstanceCommand_ExecuteExpanded.cs
> +                if (!string.IsNullOrEmpty(result) && PassThru.ToBool()) { WriteObject(result.TrimEnd()); }
It works in my local.

2021-11-16 08:44 UTC, BethanyZhou commented on src/ContainerInstance/custom/InvokeAzContainerInstanceCommand_ExecuteExpanded.cs
> +            socket.ConnectAsync(new System.Uri(containerExecResponse.WebSocketUri), _cancellationTokenSource.Token).ConfigureAwait(false).GetAwaiter().GetResult();
Since we can't get Token directly, _cancellationTokenSource.Token is the shortest way to get Token by far.

2021-11-16 08:48 UTC, isra-fel approved these changes

2021-11-17 02:14 UTC, BethanyZhou commented
/azp run azure-powershell - powershell-core

2021-11-17 04:35 UTC, dolauli commented
/azp run

2021-11-17 07:51 UTC, isra-fel commented
/azp run

2021-11-18 03:22 UTC, merged