Moving SQL Server and SQL Instance AAD from ActiveDirectoryClient to MicrosoftGraphClient
Azure/azure-powershell pull request #16439
Opened 2021-11-18 15:29 UTC by jaredwelsh

This PR moves authentication for AzureSqlServerActiveDirectoryAdministratorAdapter and AzureSqlInstanceActiveDirectoryAdministratorAdapter from using the ActiveDirectoryClient to the new MicrosoftGraphClient

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-11-22 10:24 UTC, isra-fel commented
Hey @jaredwelsh if you are Microsoft employee please visit https://aka.ms/AzureGitHub and join Azure orgnization. Thanks

2021-11-24 09:25 UTC, isra-fel requested changes

2021-11-24 09:25 UTC, isra-fel commented on src/Sql/Sql/ServerActiveDirectoryAdministrator/Services/AzureSqlServerActiveDirectoryAdministratorAdapter.cs
> +                    _microsoftGraphClient = AzureSession.Instance.ClientFactory.CreateArmClient<MicrosoftGraphClient>(Context, AzureEnvironment.Endpoint.Graph);
Please set the tenant ID for the client:

`_microsoftGraphClient.TenantId = Context.Tenant.Id;` (need validation)

2021-11-25 10:37 UTC, isra-fel commented
Another thing is, we want to inform the user we have migrated to MSGraphClient. Also mentioning how to troubleshoot issues related to MSGraph permissions. So please:

1. Copy this file [MSGraphMessageHelper.cs](https://github.com/Azure/azure-powershell/blob/main/src/KeyVault/KeyVault/Helpers/MSGraphMessageHelper.cs) to your solution (update the namespace).
2. Call `WriteMessageForCmdletsSwallowException()` or `WriteMessageForCmdletsSwallowException()` (call the right cmdlet according to whether your cmdlet throws or swallows exceptions thrown from MSGraphClient) at the beginning of the cmdlets that are affected by the migration.

Thanks!

2021-11-29 16:27 UTC, jaredwelsh commented
> Another thing is, we want to inform the user we have migrated to MSGraphClient. Also mentioning how to troubleshoot issues related to MSGraph permissions. So please:
> 
> 1. Copy this file [MSGraphMessageHelper.cs](https://github.com/Azure/azure-powershell/blob/main/src/KeyVault/KeyVault/Helpers/MSGraphMessageHelper.cs) to your solution (update the namespace).
> 2. Call `WriteMessageForCmdletsSwallowException()` or `WriteMessageForCmdletsSwallowException()` (call the right cmdlet according to whether your cmdlet throws or swallows exceptions thrown from MSGraphClient) at the beginning of the cmdlets that are affected by the migration.
> 
> Thanks!

hey Isra, for number 2, you posted the same function twice. Are there two different functions to call?

2021-11-30 02:23 UTC, isra-fel commented
```csharp
        internal static void WriteMessageForCmdletsSwallowException(Cmdlet cmdlet);
        internal static void WriteMessageForCmdletsThrowException(Cmdlet cmdlet);
```
These two, depending on how your code handles exception from the graph client - whether it is swallowed or thrown.

2021-12-01 06:44 UTC, isra-fel commented
/azp run azure-powershell - security-tools

2021-12-01 08:37 UTC, isra-fel commented
/azp run azure-powershell - security-tools

2021-12-01 09:33 UTC, isra-fel approved these changes

2021-12-01 09:33 UTC, merged