[Synapse] Add support for KQL script
Azure/azure-powershell pull request #16469
Opened 2021-11-23 06:30 UTC by wonner

## Description

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1076
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-11-30 05:25 UTC, isra-fel commented
/azp run azure-powershell - security-tools

2021-11-30 08:49 UTC, isra-fel requested changes
Please note that I updated the base branch to `release-2021-12-07` as we have begun the release process. Also, there are 2 conflicts after another Synapse PR is merged.

2021-11-30 10:15 UTC, wonner commented on src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
> +                {"Azure.Core", new Version("1.21.0.0")},
Done.

2021-12-01 02:13 UTC, isra-fel commented
/azp run azure-powershell - security-tools

2021-12-01 02:14 UTC, isra-fel approved these changes
LGTM

2021-12-01 03:13 UTC, merged