Add about_az.help.txt into en-US culture folder
Azure/azure-powershell pull request #16473
Opened 2021-11-23 08:48 UTC by BethanyZhou

## Description
![image](https://user-images.githubusercontent.com/19869716/142993736-91434bdb-6222-41fe-8cc8-065148afd721.png)

![image](https://user-images.githubusercontent.com/19869716/142993691-fb6a2520-d45d-42b6-8f3f-7033b5588549.png)

Please feel free to try it: https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.1_about.nupkg

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-11-24 02:06 UTC, BethanyZhou commented
/azp run azure-powershell - windows-powershell

2021-11-24 04:13 UTC, isra-fel requested changes

2021-11-24 04:13 UTC, isra-fel commented on build.proj
> +  <Target Name="Full" DependsOnTargets="Clean;Build;OnPremChecks;CopyAboutTopics;GenerateHelp;StaticAnalysis;Test" />
Or we should at least add comment at the beginning of this file to descriot this target.

2021-11-24 05:27 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2021-11-24 08:10 UTC, isra-fel commented on tools/Docs/GenerateAboutTopicTxt.ps1
> +$aboutFileOutputFullName = "C:\Azure\azure-powershell\src\Accounts\Accounts\help\About\about_az.help.txt"
We should add comment to explain when and how to use this script.
Also absolution path -> relative path

2021-11-24 08:10 UTC, isra-fel commented on src/Accounts/Accounts/help/About/about_az.md
> +about_Az
What is this section for?

2021-11-25 07:48 UTC, BethanyZhou commented
Retried in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1212233&view=results, can success in build task. Checked Az.Accounts in artifacts, it works as well.

2021-11-25 08:01 UTC, isra-fel approved these changes
LGTM

2021-11-25 08:02 UTC, merged