[Storage] Fixed get container access policy fail when permission in null [#15644]
Azure/azure-powershell pull request #16546
Opened 2021-12-01 03:32 UTC by blueww

## Description

Fix issue: https://github.com/Azure/azure-powershell/issues/16544

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-12-01 08:08 UTC, blueww commented
/azp run

2021-12-01 08:14 UTC, blueww commented
/azp run azure-powershell - security-tools

2021-12-01 08:17 UTC, VeryEarly commented
/azp run azure-powershell - security-tools

2021-12-01 10:04 UTC, isra-fel requested changes
Please sync with the release branch otherwise it cannot be merged.

2021-12-01 10:04 UTC, isra-fel commented on src/Storage/Storage.Management/ChangeLog.md
> +* Fixed get container access policy fail when permission in null [#15644]
```suggestion
* Fixed get container access policy fail when permission is null [#15644]
```

2021-12-02 02:29 UTC, blueww commented
/azp run azure-powershell - security-tools

2021-12-02 02:35 UTC, blueww commented
@isra-fel 
I have revised this as the your review comments, and rebases it on the release branch.

2021-12-02 03:07 UTC, isra-fel approved these changes

2021-12-02 07:32 UTC, merged