wip
Azure/azure-powershell pull request #16598
Opened 2021-12-08 09:31 UTC by BethanyZhou

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-12-10 06:34 UTC, BethanyZhou commented on src/KeyVault/KeyVault/help/Get-AzKeyVaultKeyRotationPolicy.md
> +[Update-AzKeyVaultManagedHsm](./Update-AzKeyVaultManagedHsm.md)
```suggestion
```

2021-12-14 02:21 UTC, msJinLei requested changes

2021-12-14 02:21 UTC, msJinLei commented on src/KeyVault/KeyVault/Commands/Key/KeyRotationPolicy/GetAzKeyVaultKeyRotationPolicy.cs
> +    [Cmdlet("Get", ResourceManager.Common.AzureRMConstants.AzurePrefix + "KeyVaultKeyRotationPolicy", SupportsShouldProcess = true, DefaultParameterSetName = ByVaultNameParameterSet)]
Is "SupportShouldProcess" needed for the cmdlet?

2021-12-14 05:59 UTC, msJinLei approved these changes

2021-12-14 06:17 UTC, BethanyZhou commented on src/KeyVault/KeyVault/Commands/Key/KeyRotationPolicy/UpdateAzKeyVaultKeyRotationPolicy.cs
> +        internal const string ByKeyRotationPolicyInputObjectParameterSet = " ByKeyRotationPolicyInputObject";
```suggestion
        internal const string ByKeyRotationPolicyInputObjectParameterSet = "ByKeyRotationPolicyInputObject";
```

2021-12-14 08:47 UTC, msJinLei approved these changes

2021-12-14 09:27 UTC, merged