fix issue 16565
Azure/azure-powershell pull request #16619
Opened 2021-12-10 07:48 UTC by yanjungao718

This pr is for fixing issue [16565 ](https://github.com/Azure/azure-powershell/issues/16565) and sync ps model properties with sdk

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-12-10 08:02 UTC, wonner requested changes

2021-12-10 08:02 UTC, wonner commented on src/Synapse/Synapse/Models/ManagementModels/Workspace/PSDataLakeStorageAccountDetails.cs
> -
It will be a breaking change, we often do not change the property name if it's not really needed

2021-12-10 08:02 UTC, wonner commented on src/Synapse/Synapse/Models/ManagementModels/Workspace/PSManagedIdentity.cs
> -
Same.

2021-12-10 08:02 UTC, wonner commented on src/Synapse/Synapse/Models/ManagementModels/Workspace/PSVirtualNetworkProfile.cs
> -
Same.

2021-12-14 04:50 UTC, msJinLei commented
@yanjungao718 please use a title more descriptive for the PR.

2021-12-15 07:17 UTC, yanjungao718 commented
Hi @msJinLei , the purpose of this change is to get a property of a workspace, now we have no cmdlet parameter to set it for workspace. It would be a certain value only if it is set on portal manually. and we've had other basic tests for workspace cmdlets.
As discussed with @wonner , I think it's not necessary to add test for this change.

2021-12-15 20:02 UTC, msJinLei commented
/azp run azure-powershell - security-tools

2021-12-16 06:41 UTC, msJinLei approved these changes

2021-12-16 06:43 UTC, merged