Added new parameter ApplicationSecurityGroups for Get-AzPrivateEndpoint and New-AzPrivateEndpoint
Azure/azure-powershell pull request #16643
Opened 2021-12-15 09:20 UTC by vidai-msft

…nt and Set-AzPrivateEndpoint

## Description

Added property ApplicationSecurityGroups for PSPrivateEndpoint object. This new property will be returned as the output for cmdlet Get-AzPrivateEndpoint as well as an optional input for cmdlet New-AzPrivateEndpoint

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-12-15 19:19 UTC, msJinLei requested changes
- Please also help the help doc for Get-AzPrivateEndpoint and New-AzPrivateEndpoint
- Please resolve the conflict

2021-12-15 19:19 UTC, msJinLei commented on src/Network/Network/PrivateEndpoint/NewAzurePrivateEndpointCommand.cs
> +        public PSApplicationSecurityGroup[] ApplicationSecurityGroups { get; set; }
Please use a singular name

2021-12-16 15:32 UTC, msJinLei commented on src/Network/Network/PrivateEndpoint/NewAzurePrivateEndpointCommand.cs
> +        public PSApplicationSecurityGroup[] ApplicationSecurityGroups { get; set; }
@vidai-msft forgot to mention. Please update the help doc for the cmdlet as you add a parameter

2021-12-22 01:47 UTC, msJinLei submitted a review, later dismissed

2021-12-22 02:33 UTC, msJinLei commented
@vidai-msft you can suppress the static analysis error since your new cmdlet doesn't need to support should process.

2021-12-22 07:18 UTC, vidai-msft commented
Suppressed ShouldProcess error raised by Static Analysis

2021-12-23 03:17 UTC, msJinLei approved these changes

2021-12-23 03:17 UTC, merged