Virtual Wan P2S MultiPool feature changes
Azure/azure-powershell pull request #17032
Opened 2022-02-07 23:09 UTC by Nilambari

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-03-01 05:40 UTC, BethanyZhou commented
CI failed: The type or namespace name 'IConfigurationPolicyGroupsOperations' could not be found (are you missing a using directive or an assembly reference?)  Please have a look.

2022-03-01 05:40 UTC, BethanyZhou commented on src/Network/Network.Test/ScenarioTests/CortexTests.ps1
> +        Assert-AreEqual "7.7.7.7" $P2SVpnGateway.CustomDnsServers[0]
```suggestion
        	Assert-AreEqual "7.7.7.7" $P2SVpnGateway.CustomDnsServers[0]
```

2022-03-01 05:40 UTC, BethanyZhou commented on src/Network/Network.Test/ScenarioTests/CortexTests.ps1
> +	    $actual = $job | Receive-Job
Please correct indents.

2022-03-01 05:40 UTC, BethanyZhou commented on src/Network/Network/Az.Network.psd1
> +               'Remove-AzVirtualHubVnetConnection', 'Update-AzVirtualHubVnetConnection',
Please correct indents.

2022-04-14 07:58 UTC, Nilambari commented
@isra-fel  Incorporate review comment. Please take a look.

2022-04-14 07:59 UTC, Nilambari commented
> CI failed: The type or namespace name 'IConfigurationPolicyGroupsOperations' could not be found (are you missing a using directive or an assembly reference?) Please have a look.

Waiting for latest network SDK generation.

2022-04-17 17:01 UTC, isra-fel commented
Generally looks good. Please regenerate help documents and resolve the conflicts.

2022-04-26 07:23 UTC, Nilambari commented
> Generally looks good. Please regenerate help documents and resolve the conflicts.

Done. @isra-fel Please take a look. Thanks!

2022-04-27 02:16 UTC, isra-fel requested changes
This file `src/Network/Network/help/Az.Network.md` is supposed to be updated when introducing new cmdlets.
Please make sure to use `-RefreshModulePage` when regenerating helps, see https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module

2022-04-27 04:56 UTC, nilambarideshpande commented
> This file `src/Network/Network/help/Az.Network.md` is supposed to be updated when introducing new cmdlets.
> Please make sure to use `-RefreshModulePage` when regenerating helps, see https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module

Let me update it. Thanks.

2022-04-27 06:56 UTC, Nilambari commented
> Let me update it. Thanks.

Incorporated review comments & included latest test recording as well. @isra-fel  Please take a look and help approve this PR. Thanks!

2022-04-27 09:59 UTC, isra-fel commented
/azp run azure-powershell - security-tools

2022-04-27 09:59 UTC, isra-fel approved these changes

2022-04-27 14:52 UTC, merged