Split Az.DataBoxEdge Examples
Azure/azure-powershell pull request #17053
Opened 2022-02-09 09:50 UTC by CaptainFanZzz

## Description

Split Az.DataBoxEdge Examples

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-02-23 05:53 UTC, ziyuezh576 requested changes

2022-02-23 05:53 UTC, ziyuezh576 commented on src/DataBoxEdge/DataBoxEdge/help/New-AzDataBoxEdgeShare.md
> +New-AzDataBoxEdgeShare -ResourceGroupName resourceGroupName -DeviceName deviceName -Name share-1 -SMB
add " `" to the end

2022-02-23 05:53 UTC, ziyuezh576 commented on src/DataBoxEdge/DataBoxEdge/help/New-AzDataBoxEdgeUser.md
> +New-AzDataBoxEdgeUser -ResourceGroupName resourceGroupName -DeviceName deviceName -Name username
add " `" to the end

2022-02-23 05:53 UTC, ziyuezh576 commented on src/DataBoxEdge/DataBoxEdge/help/New-AzDataBoxEdgeUser.md
> +New-AzDataBoxEdgeUser -ResourceGroupName resourceGroupName -DeviceName deviceName -Name username
add " `" to the end

2022-02-23 05:53 UTC, ziyuezh576 commented on src/DataBoxEdge/DataBoxEdge/help/Set-AzDataBoxEdgeStorageAccountCredential.md
> +Set-AzDataBoxEdgeStorageAccountCredential -ResourceGroupName resourceGroupName -DeviceName deviceName -Name storageAcountCredentialName
add " `" to the end

2022-02-23 05:53 UTC, ziyuezh576 commented on src/DataBoxEdge/DataBoxEdge/help/Set-AzDataBoxEdgeUser.md
> +Set-AzDataBoxEdgeUser -ResourceGroupName resourceGroupName -DeviceName deviceName -Name username
add " `" to the end

2022-02-23 06:59 UTC, CaptainFanZzz commented
@ziyuezh576 Changed. Plz check.

2022-02-24 10:06 UTC, ziyuezh576 approved these changes

2022-02-25 06:18 UTC, merged