[AppServices]: Fix #17184 :  `Get-AzWebApp` to return SiteConfig details in the response when requested the WebApps under subscreption
Azure/azure-powershell pull request #17269
Opened 2022-02-25 16:17 UTC by Kotasudhakarreddy

#17184 

## Description
`Get-AzWebApp` is not returning SiteConfig details in the response object when requested the WebApps under subscreption

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-02-28 07:31 UTC, BethanyZhou requested changes

2022-02-28 07:31 UTC, BethanyZhou commented on src/Websites/Websites/ChangeLog.md
> +* Fixed `Get-AzWebApp` to return SiteConfig details in the response when requested the WebApps under subscreption #17184
```suggestion
* Fixed `Get-AzWebApp` to return SiteConfig details in the response when requested the WebApps under subscription [#17184]

```

2022-02-28 07:32 UTC, BethanyZhou approved these changes

2022-02-28 17:02 UTC, closed without merging

2022-03-01 02:59 UTC, BethanyZhou commented
Just for sure, this PR closed as this feature should not be change, right? @panchagnula

2022-03-01 03:08 UTC, panchagnula commented
Correct - the current experience is by design & so we shouldn't make this change.