New NetworkManager PS Package
Azure/azure-powershell pull request #17532
Opened 2022-03-18 17:58 UTC by yanfa317

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-03-21 01:15 UTC, yanfa317 commented
Here is doc design https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1123

2022-03-21 07:26 UTC, BethanyZhou requested changes

2022-03-21 07:26 UTC, BethanyZhou commented on src/Network/Network/NetworkManager/NetworkGroup/RemoveAzNetworkGroupCommand.cs
> +                    if (PassThru)
```suggestion
                    if (PassThru.IsPresent)
```

2022-03-21 07:26 UTC, BethanyZhou commented on src/Network/Network/NetworkManager/NewAzNetworkManagerScopeCommand.cs
> +    public class NewPSNetworkManagerScopeCommand : NetworkManagerBaseCmdlet
```suggestion
    public class NewAzNetworkManagerScopeCommand : NetworkManagerBaseCmdlet
```

2022-03-21 07:37 UTC, Queenpuyu commented on src/Network/Network/Az.Network.psd1
> +        ReleaseNotes = '* Onboard Azure Virtual Network Manager Cmdlets for preview
Hi

2022-03-21 16:38 UTC, yanfa317 commented on src/Network/Network/NetworkManager/DeployAzNetworkManagerCommit.cs
> +    [Cmdlet("Deploy", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "NetworkManagerCommit", SupportsShouldProcess = true), OutputType(typeof(PSNetworkManagerCommit))]
It was added from last time https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1033

2022-03-22 01:52 UTC, BethanyZhou requested changes
Please resolve   "Az.Network","Microsoft.Azure.Commands.Network.NewAzNetworkManagerScopeCommand","New-AzNetworkManagerScope","1","8100","New-AzNetworkManagerScope Does not support ShouldProcess but the cmdlet verb New indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"

2022-03-22 01:52 UTC, BethanyZhou commented on src/Network/Network/ChangeLog.md
> +    - `Remove-AzNetworkManagerSecurityUserRule`
Please move all these messages to upcoming release section.

2022-03-22 01:52 UTC, BethanyZhou commented on src/Network/Network/ChangeLog.md
> -    - `New-AzNetworkWatcherFlowLog`
Please do not delete these messages.

2022-03-22 06:00 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2022-03-22 06:01 UTC, BethanyZhou approved these changes

2022-03-22 07:17 UTC, merged