Fix Az.MySql Syntax Errors
Azure/azure-powershell pull request #17696
Opened 2022-04-01 03:49 UTC by v-yuzhichen

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-04-02 08:41 UTC, ziyuezh576 approved these changes

2022-04-02 08:41 UTC, ziyuezh576 commented on src/MySql/help/Test-AzMySqlFlexibleServerConnect.md
> +Test-AzMySqlFlexibleServerConnect -ResourceGroupName PowershellMySqlTest -Name mysql-test -AdministratorLoginPassword $password -Query "SELECT * FROM test"
-QueryText

2022-04-02 08:41 UTC, ziyuezh576 commented on src/MySql/help/Test-AzMySqlFlexibleServerConnect.md
> +Get-AzMySqlFlexibleServer -ResourceGroupName PowershellMySqlTest -ServerName mysql-test | Test-AzMySqlFlexibleServerConnect -Query "SELECT * FROM test" -AdministratorLoginPassword $password
-QueryText

2022-04-02 08:43 UTC, ziyuezh576 requested changes
-QueryText

2022-04-22 07:54 UTC, ziyuezh576 approved these changes

2022-05-07 07:23 UTC, wyunchi-ms approved these changes

2022-05-07 07:23 UTC, merged