Fix Az.Network Syntax Errors
Azure/azure-powershell pull request #17701
Opened 2022-04-01 09:57 UTC by CaptainFanZzz

## Description

Fix Az.Network Syntax Errors

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-04-02 15:35 UTC, ziyuezh576 requested changes

2022-04-02 15:35 UTC, ziyuezh576 commented on src/Network/Network/help/Set-AzNetworkProfile.md
> -$networkProfile.ContainerNetworkInterfaceConfigurations = New-AzNetworkProfileContainerNicConfig -Name cnicconfig1
New-AzContainerNicConfig

2022-04-02 15:35 UTC, ziyuezh576 commented on src/Network/Network/help/Set-AzServiceEndpointPolicy.md
> +Set-AzServiceEndpointPolicy -ServiceEndpointPolicy $serviceEndpointPolicy
?

2022-04-02 15:35 UTC, ziyuezh576 commented on src/Network/Network/help/Update-AzVpnGatewayNatRule.md
> +$natRule = Update-AzVpnGatewayNatRule -InputObject $vpnConnection
?

2022-04-02 15:35 UTC, ziyuezh576 commented on src/Network/Network/help/Update-AzVirtualHub.md
> +Update-AzVirtualHub -InputObject $virtualHub -AddressPrefix "10.0.2.0/24"
?

2022-04-02 16:05 UTC, ziyuezh576 requested changes

2022-04-22 11:10 UTC, ziyuezh576 requested changes

2022-04-27 09:28 UTC, ziyuezh576 approved these changes

2022-05-07 07:15 UTC, wyunchi-ms approved these changes

2022-05-07 07:15 UTC, merged