Update Resources.ManagementGroups Module
Azure/azure-powershell pull request #17728
Opened 2022-04-06 20:40 UTC by git-thomasdolan

## Description

- Updated the ManagementGroups SDK to the latest version
- Added and updated tests to test the new changes

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-04-13 15:51 UTC, git-thomasdolan commented
@dingmeng-xue Can someone review this? Thanks!

2022-04-13 16:32 UTC, isra-fel requested changes
Hi @git-thomasdolan for a PR that adds new cmdlets, a cmdlet design review has to be approved first. So please submit an issue in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) and fill in the questionare.

Also in this PR you need to update the ChangeLog.md under src/Resources.

2022-04-13 16:32 UTC, isra-fel commented on src/Resources/Resources/Az.Resources.psd1
> +               'Get-AzHierarchySetting', 'Remove-AzHierarchySetting'
Inconsistent indentation

2022-04-13 21:06 UTC, git-thomasdolan commented
Created issue [here](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1180)

2022-05-06 19:55 UTC, git-thomasdolan commented
Hi,

Are there any other changes I need to make? I believe I made all the requested changes from earlier. Thanks!

2022-05-07 07:15 UTC, wyunchi-ms commented
/azp run azure-powershell - security-tools

2022-05-07 07:21 UTC, wyunchi-ms approved these changes

2022-05-07 07:22 UTC, wyunchi-ms commented
/azp run azure-powershell - security-tools

2022-05-07 08:15 UTC, wyunchi-ms approved these changes

2022-05-07 08:16 UTC, merged