Fix Az.TrafficManager Syntax Errors
Azure/azure-powershell pull request #17868
Opened 2022-04-21 06:45 UTC by v-yuzhichen

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-04-22 02:00 UTC, ziyuezh576 requested changes

2022-04-22 02:00 UTC, ziyuezh576 commented on src/TrafficManager/TrafficManager/help/Set-AzTrafficManagerProfile.md
> +$TrafficManagerProfile.ProfileStatus = Disable-AzTrafficManagerProfile -Name "ContosoProfile" -ResourceGroupName "ResourceGroup11"
$TrafficManagerProfile.ProfileStatus = "Disabled"

2022-04-22 08:50 UTC, ziyuezh576 approved these changes

2022-04-24 02:03 UTC, wyunchi-ms approved these changes

2022-04-24 02:03 UTC, merged