Add AdvisorTestRunner and replace TestController
Azure/azure-powershell pull request #17961
Opened 2022-04-22 08:36 UTC by ziyuezh576

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-04-24 02:05 UTC, vidai-msft requested changes
Please modify the AdvisorTestRunner as per the comments below.

2022-04-24 02:05 UTC, vidai-msft commented on src/Advisor/Advisor.Test/ScenarioTests/AdvisorTestRunner.cs
> +                ).WithManagementClients(
WithManagementClients is not necessary as both GetResourceGraphClient and GetSubscriptionClient instantiate the object like context.GetServiceClient<TClient>

2022-04-24 02:05 UTC, vidai-msft commented on src/Advisor/Advisor.Test/ScenarioTests/AdvisorTestRunner.cs
> +        private static IAdvisorManagementClient GetResourceGraphClient(MockContext context)
This method is not necessary. Please remove it.

2022-04-24 02:05 UTC, vidai-msft commented on src/Advisor/Advisor.Test/ScenarioTests/AdvisorTestRunner.cs
> +        private static SubscriptionClient GetSubscriptionClient(MockContext context)
This method is not necessary. Please remove it

2022-04-25 07:47 UTC, vidai-msft approved these changes
Looks good !

2022-04-25 08:12 UTC, isra-fel requested changes

2022-04-25 08:12 UTC, isra-fel commented on src/Advisor/Advisor.Test/ScenarioTests/AdvisorTestRunner.cs
> +﻿using System.Collections.Generic;
Please add license headers - you can copy it from other files

2022-04-27 02:02 UTC, isra-fel approved these changes

2022-04-27 02:02 UTC, merged