Add AnalysisServicesTestRunner and replace AzTestsBase
Azure/azure-powershell pull request #18056
Opened 2022-05-06 05:08 UTC by CaptainFanZzz

## Description

Add AnalysisServicesTestRunner and replace AzTestsBase

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-05-06 07:43 UTC, ziyuezh576 requested changes

2022-05-06 07:43 UTC, ziyuezh576 commented on src/AnalysisServices/AnalysisServices.Test/ScenarioTests/AnalysisServicesTestRunner.cs
> +                    helper.GetRMModulePath("AzureRM.AnalysisServices.psd1")
same as the line above, delete it.

2022-05-06 07:43 UTC, ziyuezh576 commented on src/AnalysisServices/AnalysisServices.Test/InMemoryTests/DataPlaneCommandTests.cs
> +        public DataPlaneCommandTests(ITestOutputHelper output) : base(output)
File name contains Data Plane, and the file doesn't look like a TestController, so I don't think the file needs to be edited.

2022-05-06 07:43 UTC, ziyuezh576 commented on src/AnalysisServices/AnalysisServices.sln
> +VisualStudioVersion = 17.1.32414.318
don't edit solution file

2022-05-06 07:43 UTC, ziyuezh576 commented on src/AnalysisServices/AnalysisServices.Test/ScenarioTests/AsTests.cs
> +
delete the empty line

2022-05-09 11:58 UTC, ziyuezh576 requested changes

2022-05-10 03:50 UTC, ziyuezh576 requested changes

2022-05-10 03:50 UTC, ziyuezh576 commented on src/AnalysisServices/AnalysisServices.Test/InMemoryTests/DataPlaneCommandTests.cs
> +        public DataPlaneCommandTests(ITestOutputHelper output) : base(output)
Sorry I didn't notice that AsTestsBase class had been removed.

2022-05-10 03:50 UTC, ziyuezh576 commented on src/AnalysisServices/AnalysisServices.Test/InMemoryTests/DataPlaneCommandTests.cs
>              XunitTracingInterceptor.AddToContext(new XunitTracingInterceptor(output));
Remove this line. It's removed in other test classes, and doing so will not fail any tests.

2022-05-10 04:46 UTC, ziyuezh576 approved these changes

2022-05-13 07:26 UTC, vidai-msft requested changes

2022-05-13 07:26 UTC, vidai-msft commented on src/AnalysisServices/AnalysisServices.Test/InMemoryTests/DataPlaneCommandTests.cs
> +    public class DataPlaneCommandTests : AnalysisServicesTestRunner
Please make it inherit from RMTestBase instead of TestRunner

2022-05-13 09:44 UTC, vidai-msft approved these changes

2022-05-17 03:34 UTC, merged