Fix Az.Monitor XML Comments
Azure/azure-powershell pull request #18438
Opened 2022-06-08 13:29 UTC by CaptainFanZzz

## Description

Fix Az.Monitor XML Comments

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-06-09 10:38 UTC, v-yuzhichen commented on src/Monitor/Monitor/OutputClasses/PSVoiceReceiver.cs
>          // <summary>Gets or sets the country code.</summary>
I think this should be "/// <summary>Gets or sets the country code.</summary>"

2022-06-14 06:02 UTC, v-yuzhichen commented on src/Monitor/Monitor/Monitor.csproj
> +    <GenerateDocumentationFile>True</GenerateDocumentationFile>
Please do not check in the changes in csproj file

2022-06-14 06:03 UTC, v-yuzhichen approved these changes

2022-06-16 02:45 UTC, BethanyZhou reviewed
Please try your best to utilize existing information rather than deleting them directly.

2022-06-16 02:45 UTC, BethanyZhou commented on src/Monitor/Monitor/OutputClasses/PSDynamicMetricCriteria.cs
> +        /// <param name="dynamicMetricCriteria"></param>
```suggestion
        /// <param name="dynamicMetricCriteria">The original dynamic metric criteria object</param>
```

2022-06-16 02:45 UTC, BethanyZhou commented on src/Monitor/Monitor/OutputClasses/PSMetricDimension.cs
> +        /// <param name="valuesToExclude"></param>
```suggestion
        /// <param name="dimensionName">Name of the dimension.</param>
        /// <param name="valuesToInclude">List dimension includeValues.</param>
        /// <param name="valuesToExclude">List of dimension excludeValues.</param>
```

2022-06-16 02:45 UTC, BethanyZhou commented on src/Monitor/Monitor/TransitionalClasses/MetricSettings.cs
> +        /// <param name="metricSettings"></param>
```suggestion
        /// <param name="metricSettings">The metric settings</param>
```

2022-06-16 02:45 UTC, BethanyZhou requested changes
Please have a look

2022-06-17 07:59 UTC, BethanyZhou approved these changes

2022-06-17 07:59 UTC, merged