Update New-AzApiManagement for issue #18439
Azure/azure-powershell pull request #18451
Opened 2022-06-09 09:09 UTC by CaptainFanZzz

## Description

Update New-AzApiManagement for issue #18439

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-06-09 21:28 UTC, ziyuezh576 requested changes

2022-06-09 21:28 UTC, ziyuezh576 commented on src/ApiManagement/ApiManagement/Commands/NewAzureApiManagement.cs
> +            HelpMessage = "The tier of the Azure API Management service. Valid values are : " +
Import-Module platyPS
Import-Module "azure-powershell\artifacts\Debug\Az.ApiManagement\Az.ApiManagement.psd1"
New-MarkdownHelp -Module Az.ApiManagement -OutputFolder .\docs

Generated markdown file is different with the one you manually edited below.

2022-06-10 06:31 UTC, ziyuezh576 approved these changes

2022-06-21 08:24 UTC, dingmeng-xue approved these changes

2022-06-22 08:29 UTC, merged