Remove KeyVaultManagementController.cs
Azure/azure-powershell pull request #18488
Opened 2022-06-13 11:08 UTC by ziyuezh576

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-06-13 11:13 UTC, ziyuezh576 commented on src/KeyVault/KeyVault.Test/ScenarioTests/KeyVaultManagementTests.cs
> +            TestRunner.RunTestScript("Test-GetVault");
This test case can successfully pass after removing "Initialize" function. Does it still needs to be skipped?

2022-06-14 02:11 UTC, vidai-msft requested changes

2022-06-14 02:17 UTC, vidai-msft requested changes
Remove the ItemGroup and see if it works for all tests.

2022-06-14 03:41 UTC, ziyuezh576 commented on src/KeyVault/KeyVault.Test/KeyVault.Test.csproj
>    <ItemGroup>
Yes, it can be copied. Its propery is "Copy if newer"

2022-06-17 11:18 UTC, closed without merging