Add DisableIntegrityMonitoring parameter to New-AzVM and change default behavior for a particular TrustedLaunch scenario
Azure/azure-powershell pull request #18739
Opened 2022-06-27 05:45 UTC by Sandido

## Description

This PR modifies the default behavior when this scenario occurs:
1) SecurityType on the VM is TrustedLaunch.
2) VTpmEnabled is true.
3) SecureBootEnabled is true. 
4) DisableIntegrityMonitoring (the new switch parameter) is not true. 
When this scenario occurs, the VM Extension 'Guest Attestation' is added to the new VM, and the VM Identity will be set to SystemAssigned. 

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1166 
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-06-27 12:51 UTC, VeryEarly submitted a review, later dismissed

2022-06-27 22:13 UTC, Sandido commented
@VeryEarly , not sure if these CI checks were failing before I added the vmss work, but the test failures look like a framework issue not something due to this pr. 
I even made another PR reverted to what you previously reviewed and the same errors are there: https://github.com/Azure/azure-powershell/pull/18763

2022-06-27 22:14 UTC, Sandido commented
I'm unable to run the tests locally due to a known issue, so please ensure this doesn't break anything else before merging.

2022-06-28 01:34 UTC, VeryEarly commented
/azp run

2022-06-28 04:20 UTC, VeryEarly requested changes

2022-06-28 04:20 UTC, VeryEarly commented on src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs
> +            if (this.DisableIntegrityMonitoring != true &&
test error thrown at this line

2022-06-29 10:31 UTC, VeryEarly approved these changes

2022-06-29 10:31 UTC, merged