{AzureCXP} fixes Azure/azure-powershell#18319
Azure/azure-powershell pull request #18746
Opened 2022-06-27 07:18 UTC by navba-MSFT

Examples New-AzRecoveryServicesAsrProtectionContainerMapping and Get-AzRecoveryServicesAsrReplicationProtectedItem use the variable $PrimaryContainer, but don't tell you how that variable is being set.

This PR mentions address this issue. Adds the below point to clear the confusion:

To get the ASR protection container in the Recovery Service Container run the [Get-AzRecoveryServicesAsrProtectionContainer](https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesasrprotectioncontainer?view=azps-8.0.0) PS command.

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2022-06-27 15:09 UTC, mikefrobbins requested changes
URL's should be relative so they work in air-gapped environments. They also shouldn't include specific culture or version information. I would also recommend avoiding the use of abbreviations such as _PS_ for PowerShell.

2022-06-27 15:09 UTC, mikefrobbins commented on src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesAsrReplicationProtectedItem.md
> +Specifies the ASR protection container object of the ASR protection container corresponding to the replication protected item. To get the ASR protection container in the Recovery Service Container ru
```suggestion
Specifies the ASR protection container object of the ASR protection container corresponding to the replication protected item. To get the ASR protection container in the Recovery Service Container run the [Get-AzRecoveryServicesAsrProtectionContainer](/powershell/module/az.recoveryservices/get-azrecoveryservicesasrprotectioncontainer) cmdlet.
```

2022-06-27 15:09 UTC, mikefrobbins commented on src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesAsrProtectionContainerMapping.md
> +Specifies the ASR protection container object for the  primary protection container to be used in the mapping. To get the ASR protection container in the Recovery Service Container run the [Get-AzRec
```suggestion
Specifies the ASR protection container object for the primary protection container to be used in the mapping. To get the ASR protection container in the Recovery Service Container run the [Get-AzRecoveryServicesAsrProtectionContainer](/powershell/module/az.recoveryservices/get-azrecoveryservicesasrprotectioncontainer) cmdlet.
```

2022-06-28 02:00 UTC, VeryEarly commented
please go to these cmdlets, update parameter descriptions there, and re-generate help markdown.
Otherwise your doc fix will be overwritten next time docs are generated

2022-06-28 12:59 UTC, navba-MSFT commented
@mikefrobbins Your suggested changes have been committed. Could you review and approve this PR ?

2022-06-28 13:06 UTC, mikefrobbins submitted a review, later dismissed
LGTM

2022-06-29 02:52 UTC, navba-MSFT commented
@mikefrobbins @VeryEarly Could you please merge this PR once you get a chance ?

2022-06-29 06:26 UTC, VeryEarly commented
> @mikefrobbins @VeryEarly Could you please merge this PR once you get a chance ?

Could you please resolve my comments?

2022-06-29 07:03 UTC, navba-MSFT commented
> > @mikefrobbins @VeryEarly Could you please merge this PR once you get a chance ?
> 
> Could you please resolve my comments?

@VeryEarly I just did. I updated the parameter descriptions in the cmdlets. Could you please Review and approve once you get a chance ?

2022-06-29 08:59 UTC, VeryEarly submitted a review, later dismissed

2022-06-29 15:46 UTC, mikefrobbins submitted a review, later dismissed
LGTM

2022-06-29 15:53 UTC, navba-MSFT commented
/azp run azure-powershell - security-tools

2022-06-30 04:45 UTC, VeryEarly commented
/azp run azure-powershell - security-tools

2022-06-30 05:12 UTC, VeryEarly approved these changes

2022-06-30 05:13 UTC, merged