Az.SecurityInsights Updates
Azure/azure-powershell pull request #19039
Opened 2022-07-25 14:52 UTC by dicolanl

Updates per design review and comment on https://github.com/Azure/azure-powershell/pull/18790#issuecomment-1188735810

## Checklist

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from the scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** change version of module in pull request

2022-07-25 14:52 UTC, dicolanl commented
@BethanyZhou per your comments https://github.com/Azure/azure-powershell/pull/18790#issuecomment-1188735810 I have updated the cmdlets and created a new PR

2022-07-26 01:10 UTC, BethanyZhou commented
Thank for your input! 
- Parameter Teams of cmdlet New/Update-AzSentinelDataConnector does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name. 

  - Please update Teams -> Team in New/Update-AzSentinelDataConnector as well.

- Please see tests in https://github.com/Azure/azure-powershell/blob/3ec00cc46e5e378eef84476924b5d8f90c0ff1bc/src/SecurityInsights/test/Update-AzSentinelIncidentRelation.Tests.ps1#L19
- https://github.com/Azure/azure-powershell/blob/3ec00cc46e5e378eef84476924b5d8f90c0ff1bc/src/SecurityInsights/test/Update-AzSentinelBookmarkRelation.Tests.ps1#L19

  - The Id is not contained in the syntax of New-AzSentinelBookmark and New-AzSentinelIncident could you check it?

- For `Update-AzSentinelSetting`, `Update-AzSentinelDataConnector`,  and `Update-AzSentinelEntityQuery`, please add SubscriptionId as its parameter.

-  I saw the test for Invoke-AzSentinelDataConnectorsCheckRequirement, but I didn't find it is a command included in current module. Could you check?

2022-07-28 05:59 UTC, BethanyZhou requested changes

2022-07-29 18:43 UTC, dicolanl commented
@BethanyZhou 
Updated code see comments below:

-Parameter Teams of cmdlet New/Update-AzSentinelDataConnector does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name.
--This parameter is referencing Microsoft Teams.  Changing it to Team will confuse customers.

-Please see tests in:
The Id is not contained in the syntax of New-AzSentinelBookmark, New-AzSentinelAutomationRule and New-AzSentinelIncident could you check it?
--Fixed
-I saw the test for Invoke-AzSentinelDataConnectorsCheckRequirement, but I didn't find it is a command included in current module. Could you check?
--Fixed.  We hide the command as its not useful in powershell, removed the test.

-Please check the Disable parameter in New-AzSentinelAlertRule.Tests.ps1 and
--Fixed

-A parameter cannot be found that matches parameter name 'EntityQueryId'.
--Fixed

-A parameter cannot be found that matches parameter name 'DataConnectorId'.
--Fixed

-A parameter cannot be found that matches parameter name 'Disabled'. 
--Fixed

-Cannot bind argument to parameter 'SubscriptionId' because it is null.
please add SubscriptionId as their parameter to resolve this issue.
--SubscrptionId is an optional parameter for all cmdlets.  Its uses 'Script = '(Get-AzContext).Subscription.Id' So its required to login before running the tests.

I also reran all tests in record mode so there was some new recording files.

2022-08-01 05:54 UTC, isra-fel commented
Memo (for myself):
1. When we think this PR is OK, run a "generation" pipeline from this branch to `share/SecurityInsights`
2. Submit a PR from `share/SecurityInsights` to `Az.SecurityInsights-preview` branch
3. If the CI fails, fix the issues in THIS PR, go to 1
4. Merge this PR and the PR in 2
5. Release the preview from `Az.SecurityInsights-preview` branch
6. (In Major release) merge preview branch to main

2022-08-05 08:37 UTC, wyunchi-ms commented
/azp run

2022-08-09 03:09 UTC, VeryEarly commented on src/SecurityInsights/custom/Update-AzSentinelAlertRule.ps1
>          [Switch]
```suggestion
        [System.Management.Automation.SwitchParameter]
```

2022-08-09 03:10 UTC, VeryEarly commented on src/SecurityInsights/custom/Update-AzSentinelAlertRule.ps1
> +        [Switch]
```suggestion
        [System.Management.Automation.SwitchParameter]
```

2022-08-09 03:11 UTC, VeryEarly commented on src/SecurityInsights/examples/New-AzSentinelDataConnector.md
>  ### Example 1: {{ Add title here }}
please add title

2022-08-09 03:12 UTC, VeryEarly commented on src/SecurityInsights/examples/Remove-AzSentinelIncidentRelation.md
>  ### Example 1: {{ Add title here }}
please add title

2022-08-09 03:13 UTC, VeryEarly reviewed
please update examples and re-generate docs

2022-08-09 16:54 UTC, dicolanl commented on src/SecurityInsights/examples/New-AzSentinelDataConnector.md
>  ### Example 1: {{ Add title here }}
fixed

2022-08-09 16:55 UTC, dicolanl commented on src/SecurityInsights/examples/Remove-AzSentinelIncidentRelation.md
>  ### Example 1: {{ Add title here }}
resloved.

2022-08-09 16:57 UTC, dicolanl commented
@VeryEarly i have fixed the items from comment here and per email , both are in the lastest commit.

2022-08-16 17:13 UTC, closed without merging