update Update-AzVm error message
Azure/azure-powershell pull request #19076
Opened 2022-07-27 21:50 UTC by grizzlytheodore

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from the scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** change version of module in pull request

2022-07-28 06:01 UTC, BethanyZhou requested changes

2022-07-28 06:01 UTC, BethanyZhou commented on src/Compute/Compute/ChangeLog.md
> +* Updated `Update-AzVm` to give constructive error messages when empty variables are passed in parameters.
Please insert your change log message between L22-L23

2022-07-28 15:15 UTC, grizzlytheodore commented
@BethanyZhou change made. ty

2022-07-28 23:58 UTC, BethanyZhou commented on src/Compute/Compute/ChangeLog.md
> +* Updated `Update-AzVm` to give constructive error messages when empty variables are passed in parameters.
```suggestion
* Updated `Update-AzVm` to give constructive error messages when empty variables are passed in parameters. [#15081]
```

2022-08-01 05:22 UTC, BethanyZhou commented
Please check following test cases:
- Microsoft.Azure.Commands.Compute.Test.ScenarioTests.PPGTests.TestPPGVM [FAIL] 
- Microsoft.Azure.Commands.Compute.Test.ScenarioTests.DedicatedHostTests.TestDedicatedHostVirtualMachine [

2022-08-01 07:27 UTC, isra-fel commented
Adding `ValidateNotNullOrEmpty` means null or empty values are now invalid. Please explain why it is not a breaking change @grizzlytheodore

2022-08-02 23:02 UTC, grizzlytheodore commented
@isra-fel  I've removed adding of [validatenotnullorempty] from other parameters except for IdentityId.

This one is not a breaking change because even tho documentation shows as optional, not using the parameter will error out. What we wanted to improve was if identityId is passed in null and the output error was ambiguous. Adding [validatenotnullorempty] gives better error message when the parameter is passed in null value 
![image](https://user-images.githubusercontent.com/10857691/182487947-01df37aa-717f-45a8-b5b7-96fc36dc1f5e.png)

2022-08-03 01:43 UTC, isra-fel approved these changes
Makes sense. Thank you.

2022-08-03 01:47 UTC, merged