Automation - Hybrid Runbook Worker Group operations related cmdlets added
Azure/azure-powershell pull request #19347
Opened 2022-08-29 10:10 UTC by krmanupa

## Description

Created new cmdlets for the Hybrid Worker Group related operations on Automation Resource. 
All the automation cmdlets have now been updated with the private autorest sdk, 

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-08-29 13:25 UTC, jagpreetstamber approved these changes

2022-08-30 06:32 UTC, isra-fel requested changes
1. `Get-AzAutomationHybridWorkerGroup` and `Remove-AzAutomationHybridWorkerGroup` were removed. This is a breaking change and cannot be merged until the next release.
2. Please fix failed test cases - they likely need to be recorded again
3. Please fix the issues with examples. See the log of CI for more details.

2022-08-30 06:32 UTC, isra-fel commented on src/Automation/Automation/help/Az.Automation.md
> +{{ Fill in the Synopsis }}
Please fill in the placeholders in this file

2022-09-01 02:54 UTC, isra-fel commented
Like I said, removing cmdlets is a breaking change. Please submit a new PR to do it so that it won't block this one.

2022-09-05 07:41 UTC, wyunchi-ms commented
The release branch is already released. Please retarget your PR to `main` branch.

2022-09-05 08:36 UTC, wyunchi-ms approved these changes

2022-09-05 08:36 UTC, wyunchi-ms commented
/azp run azure-powershell - security-tools

2022-09-05 09:03 UTC, wyunchi-ms approved these changes

2022-09-05 09:05 UTC, merged