CosmosDB Mongo API RBAC Release
Azure/azure-powershell pull request #19595
Opened 2022-09-23 05:39 UTC by ashwinisingh01

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-09-23 05:43 UTC, wyunchi-ms commented
Please update the changelog.md.

2022-10-11 07:13 UTC, wyunchi-ms commented
Kindly ping @ashwinisingh01 . Please update the changelog and fix the failed test cases and static analysis.

2022-10-25 16:10 UTC, pjohari-ms commented
/azp run

2022-10-25 16:12 UTC, pjohari-ms commented
@wyunchi-ms Can you restart the checks?

2022-10-26 00:49 UTC, dingmeng-xue commented on src/CosmosDB/CosmosDB.Sdk/README.md
> +  - https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2022-08-15-preview/rbac.json
The link of input-file should be permalink. Otherwise, it won't be easy to find which file is used for code generation when  file is changed.

2022-10-26 00:53 UTC, dingmeng-xue requested changes
I don't find the change in changelog.md. Do you want to release new version of Az.CosmosDB?

2022-10-26 00:58 UTC, dingmeng-xue commented on src/CosmosDB/CosmosDB/help/New-AzCosmosDBMongoDBPrivilege.md
> +online version: https://docs.microsoft.com/powershell/module/az.cosmosdb/new-azcosmosdbmongodbprivilegere
```suggestion
online version: https://docs.microsoft.com/powershell/module/az.cosmosdb/new-azcosmosdbmongodbprivilege
```

2022-10-26 01:00 UTC, dingmeng-xue commented on src/CosmosDB/CosmosDB/help/New-AzCosmosDBMongoDBPrivilege.md
> +online version: https://docs.microsoft.com/powershell/module/az.cosmosdb/new-azcosmosdbmongodbprivilegere
I corrected it.

2022-10-26 04:40 UTC, ashwinisingh01 commented on src/CosmosDB/CosmosDB/help/New-AzCosmosDBMongoDBPrivilege.md
> +online version: https://docs.microsoft.com/powershell/module/az.cosmosdb/new-azcosmosdbmongodbprivilegere
Thanks

2022-11-24 09:38 UTC, Nickcandy commented
@ashwinisingh01 Hi, there. Code freeze would be on 28/11/2022. If you wanna publish these codes in this release, please fix these pipeline issue ASAP.

2022-11-30 05:47 UTC, wyunchi-ms commented
/azp run

2022-11-30 05:47 UTC, wyunchi-ms commented
/azp run

2022-12-01 05:37 UTC, BethanyZhou commented
Hi @ashwinisingh01 , please check and fix below issues
```
"Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
  "Az.CosmosDB","New-AzCosmosDBAccount","2","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -SourceRestorableDatabaseAccountId is not a valid parameter name.","-SourceRestorableDatabaseAccountId","Check validity of the parameter -SourceRestorableDatabaseAccountId."
  "Az.CosmosDB","New-AzCosmosDBAccount","2","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -RestoreTimesampInUtc is not a valid parameter name.","-RestoreTimesampInUtc","Check validity of the parameter -RestoreTimesampInUtc."
  "Az.CosmosDB","New-AzCosmosDBAccount","3","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -SourceDatabaseAccountName is not a valid parameter name.","-SourceDatabaseAccountName","Check validity of the parameter -SourceDatabaseAccountName."
  "Az.CosmosDB","New-AzCosmosDBAccount","3","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -RestoreTimesampInUtc is not a valid parameter name.","-RestoreTimesampInUtc","Check validity of the parameter -RestoreTimesampInUtc."
  
```

2022-12-01 06:19 UTC, BethanyZhou commented
> Hi @ashwinisingh01 , please check and fix below issues
> 
> ```
> "Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
>   "Az.CosmosDB","New-AzCosmosDBAccount","2","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -SourceRestorableDatabaseAccountId is not a valid parameter name.","-SourceRestorableDatabaseAccountId","Check validity of the parameter -SourceRestorableDatabaseAccountId."
>   "Az.CosmosDB","New-AzCosmosDBAccount","2","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -RestoreTimesampInUtc is not a valid parameter name.","-RestoreTimesampInUtc","Check validity of the parameter -RestoreTimesampInUtc."
>   "Az.CosmosDB","New-AzCosmosDBAccount","3","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -SourceDatabaseAccountName is not a valid parameter name.","-SourceDatabaseAccountName","Check validity of the parameter -SourceDatabaseAccountName."
>   "Az.CosmosDB","New-AzCosmosDBAccount","3","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -RestoreTimesampInUtc is not a valid parameter name.","-RestoreTimesampInUtc","Check validity of the parameter -RestoreTimesampInUtc."
>   
> ```
Seems like these issues are false positive caused by dynamic parmeters. Our pipelines can't suppress these issues for the time being. Let's ignore them and ask for force merge if other comments are resolved.

2022-12-01 08:20 UTC, BethanyZhou commented
Looks good to me @dingmeng-xue please help force merge

2022-12-01 08:22 UTC, dingmeng-xue approved these changes

2022-12-01 08:22 UTC, merged