[KeyVault] Supported recovering MHSM`
Azure/azure-powershell pull request #19924
Opened 2022-10-24 11:35 UTC by BethanyZhou

## Description

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-10-24 12:57 UTC, BethanyZhou commented on src/KeyVault/KeyVault/Models/VaultManagementClient.cs
> +                // var deletedHsm = KeyVaultManagementClient.ManagedHsms.GetDeleted(parameters.Name, parameters.Location);
```suggestion
```

2022-10-25 01:37 UTC, isra-fel requested changes
LGTM except:
- Please update help/Az.KeyVault.md
- Q: how to use -Tag?

2022-10-25 01:48 UTC, BethanyZhou commented
Could you kindly approve this PR first? I will raise another PR to fix MD issues. Adding Tag is for keeping align with Undo-AzKeyVaultRemoval. This value can be updated as hashtable like -Tag @{"x"= "y"} during the process of recovering.

2022-10-25 01:51 UTC, isra-fel approved these changes

2022-10-25 01:51 UTC, merged