fix issue found for Set-AzVmssVMRunCommand
Azure/azure-powershell pull request #19993
Opened 2022-10-31 18:21 UTC by grizzlytheodore

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-10-31 18:28 UTC, grizzlytheodore commented
@dingmeng-xue , @VeryEarly  pls see the description.  The PR I made last week for this update has a bug and I want to address it before it goes out

2022-11-01 06:48 UTC, VeryEarly commented
please create OOB request, it's too late for current release

2022-11-10 06:12 UTC, Nickcandy commented
It looks good to me. Please help me double check @BethanyZhou

2022-11-10 07:24 UTC, BethanyZhou requested changes
Looks good to me with few changes required

2022-11-10 07:24 UTC, BethanyZhou commented on src/Compute/Compute.Autorest/docs/Set-AzVMRunCommand.md
> -```output
Please do not remove output block,

2022-11-10 07:24 UTC, BethanyZhou commented on src/Compute/Compute.Autorest/examples/Set-AzVmssVMRunCommand.md
> +Set-AzVmssVMRunCommand -ResourceGroupName MyRG0 -VMScaleSetName MyVMSS -InstanceId 1 -RunCommandName MyRunCommand3 -Location EastUS2EUAP -ScriptLocalPath "C:\MyScriptsDir\MyScript.ps1" -OutputBlobUri
Please add output block if applicable.

2022-11-17 23:24 UTC, grizzlytheodore commented
@BethanyZhou  added back output blocks. Please review/merge !

2022-11-22 18:27 UTC, grizzlytheodore commented
@Nickcandy  looks all good. Please review/merge! thank you

2022-11-23 01:09 UTC, BethanyZhou requested changes
Please add output for each example.

2022-11-24 02:20 UTC, BethanyZhou approved these changes
Looks good to me

2022-11-24 02:20 UTC, merged

2022-11-24 02:21 UTC, BethanyZhou commented
Hi @Nickcandy , could you help carry @grizzlytheodore 's changes to main branch?

2022-11-24 06:03 UTC, Nickcandy commented
@BethanyZhou Merged