[AppService]: Feature #19496 Added -Tag parameter support to New-AzWebApp & New-AzWebAppSlot
Azure/azure-powershell pull request #20019
Opened 2022-11-03 13:29 UTC by Kotasudhakarreddy

…pSlot

#19496 
## Description
In my organisation we are required to add tags for every Azure resource. The mentioned cmdlet doesn't have a -Tag parameter which effectively prevents me from creating a resource. Ont he other hand Azure Portal also doesn't allow me to supply the tag upon creation.

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-11-04 09:51 UTC, Nickcandy commented on src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
> +        Assert-AreEqual $tag.Values $actual.Tags.Values
Please fix the indents

2022-11-04 09:52 UTC, Nickcandy commented
It looks good to me except the indentation. Please help me double-check @BethanyZhou

2022-11-04 15:00 UTC, Kotasudhakarreddy commented on src/Websites/Websites.Test/ScenarioTests/WebAppTests.ps1
> +        Assert-AreEqual $tag.Values $actual.Tags.Values
Done!

2022-11-07 01:57 UTC, BethanyZhou requested changes

2022-11-07 01:57 UTC, BethanyZhou commented on src/Websites/Websites/ChangeLog.md
> +* Added Tag parameter for `New-AzWebApp` and `New-AzWebAppSlot`
```suggestion
* Added Tag parameter for `New-AzWebApp` and `New-AzWebAppSlot`

```
Leave a space before next section

2022-11-07 01:57 UTC, BethanyZhou commented on src/Websites/Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
>          public SwitchParameter AsJob { get; set; }
```suggestion
		public SwitchParameter AsJob { get; set; }
```
Correct indent please

2022-11-07 01:57 UTC, BethanyZhou commented on src/Websites/Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
>  			UpdateConfigIfNeeded(site);
Please keep the L186 and L187-188 with same indents.

2022-11-08 01:37 UTC, BethanyZhou approved these changes
Looks good to me

2022-11-08 01:38 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2022-11-08 05:09 UTC, merged

2023-03-30 01:16 UTC, BethanyZhou commented
Hi @Poolshark314 , could you append -Debug at the end of your command and paste the debug message here?

2023-03-30 13:40 UTC, Poolshark314 commented
@BethanyZhou Unfortunately the output looks the same when run with -Debug:

New-AzWebApp : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:11
+ $webApp = New-AzWebApp -Name $sitename -ResourceGroupName $RGName -Lo ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzWebApp], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.NewAzureWebAppCmdlet

2023-03-31 02:06 UTC, BethanyZhou commented
Hi @Poolshark314 , checked the syntax of New-AzWebApp, I find -Tag only exists in the first parameter set.

See 
```powershell
New-AzWebApp [[-ResourceGroupName] <String>] [-Name] <String> [[-Location] <String>]
 [[-AppServicePlan] <String>] [-ContainerImageName <String>] [-EnableContainerContinuousDeployment] [-AsJob]
 [-GitRepositoryPath <String>] [-Tag <Hashtable>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf]
 [-Confirm] [<CommonParameters>]

New-AzWebApp [-ResourceGroupName] <String> [-Name] <String> [[-Location] <String>] [[-AppServicePlan] <String>]
 -ContainerImageName <String> -ContainerRegistryUrl <String> -ContainerRegistryUser <String>
 -ContainerRegistryPassword <SecureString> [-EnableContainerContinuousDeployment] [-AsJob]
 [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

New-AzWebApp [-ResourceGroupName] <String> [-Name] <String> [-Location] <String> [[-AppServicePlan] <String>]
 [[-SourceWebApp] <PSSite>] [[-TrafficManagerProfile] <String>] [-EnableContainerContinuousDeployment]
 [-IgnoreSourceControl] [-IgnoreCustomHostNames] [[-AppSettingsOverrides] <Hashtable>] [[-AseName] <String>]
 [[-AseResourceGroupName] <String>] [-IncludeSourceWebAppSlots] [-AsJob]
 [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
```
Which means AseResourceGroupName and AseName (in last parameter set) can't work with Tag together in New-AzWebApp. @Kotasudhakarreddy  could you check is this behavior by design?

2023-03-31 07:48 UTC, Kotasudhakarreddy commented
@BethanyZhou - Yes, it is by design. 
@Poolshark314 please raise a new bug to extend this feature for all the `ParameterSetNames`.