[Web PubSub] Update to API version 2022-08-01-preview
Azure/azure-powershell pull request #20071
Opened 2022-11-09 11:20 UTC by Y-Sindo

## Description

Update to API version 2022-08-01-preview

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-11-15 06:27 UTC, BethanyZhou commented
@Nickcandy please help review

2022-11-15 08:25 UTC, Nickcandy commented
@BethanyZhou Hi Beisi, it looks good to me

2022-11-15 08:45 UTC, BethanyZhou requested changes

2022-11-15 08:48 UTC, Y-Sindo commented on src/SignalR/SignalR.Autorest/custom/scripts/New-AzWebPubSubEventHubEndpointObject.ps1
> +function New-AzWebPubSubEventHubEndpointObject
The cmdlets generated by autorest is `New-AzEventHubEndpointObject` (without *WebPubSub* prefix). Confirmed with @dolauli that we cannot customize the behaviour. So I have to implement it myself.

2022-11-15 09:15 UTC, BethanyZhou commented on src/SignalR/SignalR.Autorest/custom/scripts/New-AzWebPubSubEventHubEndpointObject.ps1
> +function New-AzWebPubSubEventHubEndpointObject
It surprised me. the generated cmdlets don't include prefix.

2022-11-15 09:15 UTC, BethanyZhou approved these changes

2022-11-15 09:16 UTC, merged

2022-11-24 09:50 UTC, Nickcandy commented
@Y-Sindo Hi there, there are several mistakes when I migrate SignalR to Main branch. As you can see in log : https://dev.azure.com/azclitools/public/_build/results?buildId=16993&view=logs&j=b9afb22f-0837-5d02-bc24-6c30aee08bcf&t=990f6f37-4a21-5927-092a-220f38a460e9
Please correct these error as soon as possible so that we can release ur change.