Update sdk source code
Azure/azure-powershell pull request #20164
Opened 2022-11-17 15:16 UTC by yibirnba

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-11-25 12:10 UTC, Nickcandy commented
@yibirnba Hi, there's still some error in your example:
 "Az.Security","Microsoft.Azure.Commands.Security.Cmdlets.SecurityContacts.GetSecurityContacts","Get-AzSecurityContact","0","3000","The type of property 'AlertNotifications' of type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact' has changed from 'System.String' to 'Microsoft.Azure.Commands.SecurityCenter.Models.SecurityContact.PSSecurityContactPropertiesAlertNotifications'.","Change the type of property 'AlertNotifications' back to 'System.String'."
  "Az.Security","Microsoft.Azure.Commands.Security.Cmdlets.SecurityContacts.GetSecurityContacts","Get-AzSecurityContact","0","3010","The property 'AlertsToAdmins' of type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact' has been removed.","Add the property 'AlertsToAdmins' back to type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact'."
  "Az.Security","Microsoft.Azure.Commands.Security.Cmdlets.SecurityContacts.RemoveSecurityContacts","Remove-AzSecurityContact","0","3000","The type of property 'AlertNotifications' of type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact' has changed from 'System.String' to 'Microsoft.Azure.Commands.SecurityCenter.Models.SecurityContact.PSSecurityContactPropertiesAlertNotifications'.","Change the type of property 'AlertNotifications' back to 'System.String'."
  "Az.Security","Microsoft.Azure.Commands.Security.Cmdlets.SecurityContacts.RemoveSecurityContacts","Remove-AzSecurityContact","0","3010","The property 'AlertsToAdmins' of type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact' has been removed.","Add the property 'AlertsToAdmins' back to type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact'."
  "Az.Security","Microsoft.Azure.Commands.Security.Cmdlets.SecurityContacts.SetSecurityContacts","Set-AzSecurityContact","0","3000","The type of property 'AlertNotifications' of type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact' has changed from 'System.String' to 'Microsoft.Azure.Commands.SecurityCenter.Models.SecurityContact.PSSecurityContactPropertiesAlertNotifications'.","Change the type of property 'AlertNotifications' back to 'System.String'."
  "Az.Security","Microsoft.Azure.Commands.Security.Cmdlets.SecurityContacts.SetSecurityContacts","Set-AzSecurityContact","0","3010","The property 'AlertsToAdmins' of type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact' has been removed.","Add the property 'AlertsToAdmins' back to type 'Microsoft.Azure.Commands.Security.Models.SecurityContacts.PSSecurityContact'."
 
Please correct them ASAP if you want to publish these code in this release. Code freeze would be at 28/11/2022

2022-11-29 02:42 UTC, BethanyZhou commented on src/Security/Security/Models/SecurityContact/PSSecurityContact.cs
> +        public PSSecurityContactPropertiesNotificationsByRole NotificationsByRole { get; set; }
As @Nickcandy mentioned, changing parameter type is regarded as breaking change. It wouldn't be allowed in regualer release. Please revert them. To work around the issue, how about adding two new parameters for these objects?

2023-01-10 05:50 UTC, isra-fel commented
Kindly ping @yibirnba

2023-01-27 14:48 UTC, isra-fel commented
Closing the PR for lack of activity. Feel free to reopen to continue working on it. Thanks 😀

2023-01-27 14:56 UTC, yibirnba commented
Hi @***@***.***>
Work is still in progress there, adding @***@***.***> who track it. We are waiting to the owning team to solve the breaking change there.
Tal, is there an update?

________________________________
מאת: Yeming Liu ***@***.***>
נשלח: יום שישי, 27 בינואר 2023, 16:48
אל: Azure/azure-powershell ***@***.***>
עותק: Yifat Birnbaum ***@***.***>; Assign ***@***.***>
נושא: Re: [Azure/azure-powershell] [Security] Update Security module based on .NET SDK track1, using source code (PR #20164)


Closing the PR for lack of activity. Feel free to reopen to continue working on it. Thanks 😀

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-powershell%2Fpull%2F20164%23issuecomment-1406607463&data=05%7C01%7CYifat.Birnbaum%40microsoft.com%7Cfdd99ab3848d410d3fdd08db00758bad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638104277189688981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=idUEjiTjkCBRFftDkyCfBtikOXyjpapzdOEBcZBd9PU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMNXSX6EH4CIDG5D7CA7NX3WUPN3TANCNFSM6AAAAAASDPUWI4&data=05%7C01%7CYifat.Birnbaum%40microsoft.com%7Cfdd99ab3848d410d3fdd08db00758bad%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638104277189688981%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1Y0CnI1iHOR6C81rc5WY9BKEfNgtvTg8%2B%2B5LyivY6wI%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-01-30 06:04 UTC, talhers commented
PR is still in progress

2023-02-08 02:00 UTC, BethanyZhou requested changes
Please add change log for your changes.

2023-02-09 01:00 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-09 01:00 UTC, BethanyZhou approved these changes
LGTM

2023-02-09 06:16 UTC, merged