Add new examples
Azure/azure-powershell pull request #20361
Opened 2022-12-02 16:21 UTC by timwarner-msft

Added examples to the `New-AzPolicyAssignment` and `New-AzPolicyDefinition` help files to show customers how to get the reader-friendly `DisplayName` property from those objects.

## Description

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-12-02 16:22 UTC, timwarner-msft commented
cc: @shanhix1, @mikefrobbins

2022-12-05 18:44 UTC, mikefrobbins requested changes
Use full parameter names instead of positional parameters. Couple of minor style issues, but otherwise looks good.

2022-12-05 18:44 UTC, mikefrobbins commented on src/Resources/Resources/help/Get-AzPolicyAssignment.md
> +Get-AzPolicyAssignment | Select-Object -ExpandProperty properties | Select-Object Scope, PolicyDefinitionID, DisplayName | Format-List
```suggestion
Get-AzPolicyAssignment | Select-Object -ExpandProperty properties | Select-Object -Property Scope, PolicyDefinitionID, DisplayName | Format-List
```

2022-12-05 18:44 UTC, mikefrobbins commented on src/Resources/Resources/help/Get-AzPolicyDefinition.md
> +Get-AzPolicyDefinition | Where-Object {$_.Properties.metadata.category -eq "Tag"}
```suggestion
Get-AzPolicyDefinition | Where-Object {$_.Properties.metadata.category -eq 'Tag'}
```

2022-12-05 18:44 UTC, mikefrobbins commented on src/Resources/Resources/help/Get-AzPolicyDefinition.md
> +Get-AzPolicyDefinition | Select-Object -ExpandProperty properties | Select-Object DisplayName, Description, PolicyType, Metadata | Format-List
```suggestion
Get-AzPolicyDefinition | Select-Object -ExpandProperty properties | Select-Object -Property DisplayName, Description, PolicyType, Metadata | Format-List
```

2022-12-05 18:44 UTC, mikefrobbins commented on src/Resources/Resources/help/Get-AzPolicyAssignment.md
> +This command is useful when you need to find the reader-friendly `DisplayName` property of an Azure
```suggestion
This command is useful when you need to find the reader-friendly **DisplayName** property of an Azure
```

2022-12-05 18:44 UTC, mikefrobbins commented on src/Resources/Resources/help/Get-AzPolicyDefinition.md
> +Policy definition. You can parse the `Metadata` property to discover the policy definition's version number and category assignment.
```suggestion
This command is useful when you need to find the reader-friendly **DisplayName** property of an Azure
Policy definition. You can parse the **Metadata** property to discover the policy definition's version number and category assignment.
```

2022-12-05 18:44 UTC, mikefrobbins commented on src/Resources/Resources/help/Get-AzPolicyAssignment.md
> +This command is useful when you need to find the reader-friendly `DisplayName` property of an Azure
```suggestion
This command is useful when you need to find the reader-friendly **DisplayName** property of an Azure
```

2022-12-07 01:21 UTC, msJinLei commented
/azp run azure-powershell - security-tools

2022-12-07 01:40 UTC, msJinLei approved these changes

2022-12-07 01:41 UTC, msJinLei approved these changes

2022-12-07 01:42 UTC, msJinLei commented
@mikefrobbins could you help to see whether all of your comments are addressed? thanks

2022-12-07 12:57 UTC, mikefrobbins approved these changes
LGTM

2022-12-07 13:53 UTC, merged