[Az.RecoveryServices.Backup] Added support for non-UTC timezones with standard policies
Azure/azure-powershell pull request #20483
Opened 2022-12-20 06:58 UTC by hiaga

## Description

Added support for non-UTC timezones with standard policy for workloadType IaasVM, MSSql, AzureFiles.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2022-12-26 03:15 UTC, msJinLei requested changes

2022-12-26 03:15 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
> +                    ((ServiceClientModel.AzureVmWorkloadProtectionPolicy)serviceClientResponse.Properties).Settings.TimeZone);
```suggestion
                    ((ServiceClientModel.AzureVmWorkloadProtectionPolicy)serviceClientResponse.Properties).Settings.TimeZone);
```

2022-12-26 03:15 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SchedulePolicyConversions.cs
> +                psPolicy.HourlySchedule.WindowStartTime = serviceClientPolicy.HourlySchedule.ScheduleWindowStartTime; // checkUTC: do we need to convert here too ?
Please do not leave a question here.

2022-12-26 03:15 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
> +                {
```suggestion
                {
```

2022-12-26 03:15 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
> +                {
```suggestion
                {
```

2022-12-26 03:15 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureWorkloadPsBackupProvider.cs
> +
```suggestion

```

2023-01-09 04:14 UTC, hiaga commented on src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/ConversionHelpers.cs
> +                    ((ServiceClientModel.AzureVmWorkloadProtectionPolicy)serviceClientResponse.Properties).Settings.TimeZone);
Done

2023-01-09 04:15 UTC, hiaga commented on src/RecoveryServices/RecoveryServices.Backup.Helpers/Conversions/SchedulePolicyConversions.cs
> +                psPolicy.HourlySchedule.WindowStartTime = serviceClientPolicy.HourlySchedule.ScheduleWindowStartTime; // checkUTC: do we need to convert here too ?
done

2023-01-09 04:18 UTC, hiaga commented on src/RecoveryServices/RecoveryServices.Backup.Models/CommonModels/PolicyScheduleObjects.cs
> +                {
Done

2023-01-09 04:36 UTC, msJinLei approved these changes

2023-01-09 04:36 UTC, msJinLei commented
/azp run azure-powershell - security-tools

2023-01-09 06:06 UTC, merged