[SQL] Add cmdlets for Per DB CMK
Azure/azure-powershell pull request #20550
Opened 2023-01-03 07:01 UTC by viparek

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-02-16 05:54 UTC, BethanyZhou commented
Hi @viparek ,

1. please online version for following help docs:
```
 
  Target      : Revalidate-AzSqlDatabaseTransparentDataEncryptionProtector.md
  Description : Online version in the header of the file is incorrect. The corresponding URL should be the following: htt
                ps://learn.microsoft.com/powershell/module/az.sql/revalidate-azsqldatabasetransparentdataencryptionprotec
                tor
  
  Target      : Revalidate-AzSqlInstanceTransparentDataEncryptionProtector.md
  Description : Online version in the header of the file is incorrect. The corresponding URL should be the following: htt
                ps://learn.microsoft.com/powershell/module/az.sql/revalidate-azsqlinstancetransparentdataencryptionprotec
                tor
  
  Target      : Revalidate-AzSqlServerTransparentDataEncryptionProtector.md
  Description : Online version in the header of the file is incorrect. The corresponding URL should be the following: htt
                ps://learn.microsoft.com/powershell/module/az.sql/revalidate-azsqlservertransparentdataencryptionprotecto
                r
  
  Target      : Revert-AzSqlDatabaseTransparentDataEncryptionProtector.md
  Description : Online version in the header of the file is incorrect. The corresponding URL should be the following: htt
                ps://learn.microsoft.com/powershell/module/az.sql/revert-azsqldatabasetransparentdataencryptionprotector

```
2. please re-record all test cases when API version changes.

2023-02-17 00:46 UTC, BethanyZhou commented
let me know if the pr is ready to review again by adding label `needs-review`

2023-02-17 04:44 UTC, BethanyZhou requested changes

2023-02-17 04:44 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
> +        public SwitchParameter Force { get; set; }
-Force here is unnecessary, if you add  SupportsShouldProcess, we will have -Confirm to allow to skip confirmation

2023-02-17 04:44 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
> +        public SwitchParameter AsJob { get; set; }
Could you confirm your operation whether is a LRO? only LRO needs AsJob.

2023-02-17 04:44 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureSqlServerTransparentDataEncryptionProtector.cs
> +        public SwitchParameter Force { get; set; }
please check -Force and AsJob

2023-02-17 04:44 UTC, BethanyZhou commented on src/Sql/Sql/Database Backup/Model/AzureSqlDeletedDatabaseBackupModel.cs
> +        public List<string> Keys { get; set; }
It's recommend using string array as the type of Keys

2023-02-17 04:44 UTC, BethanyZhou commented on src/Sql/Sql/Database/Cmdlet/NewAzureSqlDatabase.cs
> +        public List<string> UserAssignedIdentityId { get; set; }
Please use string array to type of UserAssignedIdentityId, see https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/design-guidelines/parameter-best-practices.md#array-vs-enumerable-types

2023-02-21 19:23 UTC, strehan1993 submitted a review, later dismissed

2023-02-23 04:28 UTC, BethanyZhou requested changes

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/Database/Cmdlet/RevalidateAzureSqlDatabaseTransparentDataEncryptionProtector.cs
> +        public SwitchParameter Force { get; set; }
Per my knowledge, validating doesn't change data/resource am I correct? Force is needed if we wan to skip confirmation to change resource.  Please check all cmdlets.

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/Database/Cmdlet/RevalidateAzureSqlDatabaseTransparentDataEncryptionProtector.cs
> +    public class RevalidateAzureSqlDatabaseTransparentDataEncryptionProtector : AzureSqlDatabaseCmdletBase<AzureSqlDatabaseModel>
Change the class name and file name to match invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/Database/Cmdlet/RevalidateAzureSqlDatabaseTransparentDataEncryptionProtector.cs
> +        protected override bool WriteResult() { return PassThru; }
```suggestion
        protected override bool WriteResult() { return PassThru.IsPresent; }
```

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/Database/Cmdlet/RevertAzureSqlDatabaseTransparentDataEncryptionProtector.cs
> +    public class RevertAzureSqlDatabaseTransparentDataEncryptionProtector : AzureSqlDatabaseCmdletBase<AzureSqlDatabaseModel>
Change the class name and file name to match invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevert

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
> +    public class RevalidateAzureRmSqlManagedInstanceTransparentDataEncryptionProtector : AzureSqlRmManagedInstanceTransparentDataEncryptionProtectorBase
Change the class name and file name to match invoke-AzSqlInstanceTransparentDataEncryptionProtectorRevalidation

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureSqlServerTransparentDataEncryptionProtector.cs
> +    public class RevalidateAzureSqlServerTransparentDataEncryptionProtector : AzureSqlServerTransparentDataEncryptionProtectorCmdletBase
Change class name and file name to match invoke-azSqlServerTransparentDataEncryptionProtectorRevalidation

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/Database/Cmdlet/RevertAzureSqlDatabaseTransparentDataEncryptionProtector.cs
> +        protected override bool WriteResult() { return PassThru; }
```suggestion
        protected override bool WriteResult() { return PassThru.IsPresent; }
```

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureRmSqlManagedInstanceTransparentDataEncryptionProtector.cs
> +        /// </summary>
Add PassThru to keep consistent with invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation

2023-02-23 04:28 UTC, BethanyZhou commented on src/Sql/Sql/TransparentDataEncryption/Cmdlet/RevalidateAzureSqlServerTransparentDataEncryptionProtector.cs
> +        /// <summary>
Add PassThru to keep consistent with invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation

2023-02-24 04:03 UTC, BethanyZhou commented
Please resolve conflicts first and fix a test case named TestDatabaseUpdateWithPerDBCMK, which is added by you. @viparek

2023-02-24 04:10 UTC, BethanyZhou requested changes

2023-02-27 05:31 UTC, BethanyZhou requested changes

2023-02-27 05:31 UTC, BethanyZhou commented on src/Sql/Sql.Sdk/Microsoft.Azure.Management.Sql.csproj
> +    <TargetFramework>netstandard2.0</TargetFramework>
This file should not be checked in.

2023-02-27 05:57 UTC, BethanyZhou commented on src/Sql/Sql/Az.Sql.psd1
> +			   'Invoke-AzSqlInstanceTransparentDataEncryptionProtectorRevalidation'
```suggestion
			   'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation',
			   'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevert',
			   'Invoke-AzSqlServerTransparentDataEncryptionProtectorRevalidation',
			   'Invoke-AzSqlInstanceTransparentDataEncryptionProtectorRevalidation'
```
```suggestion
               'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation',
               'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevert',
               'Invoke-AzSqlServerTransparentDataEncryptionProtectorRevalidation',
               'Invoke-AzSqlInstanceTransparentDataEncryptionProtectorRevalidation'
```

2023-02-27 05:58 UTC, BethanyZhou approved these changes
Looks good to me

2023-02-27 05:58 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-27 07:07 UTC, merged