[AppService]: fix #13109 - Assigning user assigned managed identity to app service slot
Azure/azure-powershell pull request #20961
Opened 2023-02-17 13:09 UTC by Kotasudhakarreddy

#13109 

## Description
For some reason, the identity of a web app deployment slot is not the same as the identity of the original app service. Given this, azure powershell has no method of assigning a user defined managed identity for a deployment slot. So if I have an app service that uses user defined managed identity, and use new-azwebappslot to create a new slot, I have no way of assigning the user defined managed identity to it using azure powershell. Currently I have to resort to an ARM template to assign the identity later.

There are several improvements possible and the best used is

an option in new-azwebappslot to also copy the identity settings

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-02-20 02:20 UTC, BethanyZhou submitted a review, later dismissed

2023-02-20 02:20 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-20 09:11 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-20 09:15 UTC, BethanyZhou requested changes

2023-02-20 09:15 UTC, BethanyZhou commented on src/Websites/Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
> +			CloningInfo cloningInfo = null;
```suggestion
            ManagedServiceIdentity sourceIdentity = null;
            CloningInfo cloningInfo = null;
```
Correct indents please

2023-02-20 09:49 UTC, Kotasudhakarreddy commented on src/Websites/Websites/Cmdlets/DeploymentSlots/NewAzureWebAppSlot.cs
> +			CloningInfo cloningInfo = null;
Done

2023-02-21 02:17 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-21 02:27 UTC, BethanyZhou commented
Please approve the PR I raised to fix indent issues in your branch first. https://github.com/Azure/azure-powershell/pull/20985/files

GitHub does differentiate space and tab, I'd suggest using VSCode to detect their differences.

2023-02-21 02:38 UTC, BethanyZhou approved these changes
LGTM

2023-02-21 02:38 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-21 02:38 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-21 05:49 UTC, BethanyZhou commented
/azp run azure-powershell - security-tools

2023-02-21 07:58 UTC, merged