Add all post call to get effective routes
Azure/azure-powershell pull request #21745
Opened 2023-05-10 18:19 UTC by zaynchen115

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-05-12 11:18 UTC, msJinLei commented
please fix the following static analysis issue
```
  D:\a\_work\1\s\artifacts//StaticAnalysisResults\HelpIssues.csv Errors
  "Assembly","HelpFile","Target","Severity","ProblemId","Description","Remediation"
  "Az.Network","","Get-AzVHubOutboundRoutes","1","6050","Help missing for cmdlet Get-AzVHubOutboundRoutes implemented by class Microsoft.Azure.Commands.Network.GetAzureRmVHubOutboundRoutesCommand","Add Help record for cmdlet Get-AzVHubOutboundRoutes to help file."
  
  D:\a\_work\1\s\artifacts//StaticAnalysisResults\ExampleIssues.csv Errors
  "Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
  "Az.Network","Get-AzVHubInboundRoutes","1","6","Invalid_Parameter_Name","5011","1","Get-AzVHubRouteTable -ResourceId is not a valid parameter name.","-ResourceId","Check validity of the parameter -ResourceId."
  "Az.Network","Get-AzVHubInboundRoutes","1","6","Invalid_Parameter_Name","5011","1","Get-AzVHubRouteTable -VirtualWanResourceType is not a valid parameter name.","-VirtualWanResourceType","Check validity of the parameter -VirtualWanResourceType."
```

2023-05-12 15:59 UTC, msJinLei requested changes

2023-05-12 15:59 UTC, msJinLei commented on src/Network/Network/help/Get-AzVHubEffectiveRoutes.md
> +# Get-AzVHubEffectiveRoutes
Please use singular for cmdlet name

2023-05-12 15:59 UTC, msJinLei commented on src/Network/Network/help/Get-AzVHubInboundRoutes.md
> +# Get-AzVHubInboundRoutes
Please use singular for cmdlet name

2023-05-12 15:59 UTC, msJinLei commented on src/Network/Network/ChangeLog.md
> +    - `Get-AzVHubOutboundRoutes`
Please also generate help doc for Get-AzVHubOutboundRoutes

2023-05-15 19:38 UTC, msJinLei requested changes
Please add test cases for the new added cmdlets.

2023-05-16 22:45 UTC, zaynchen115 commented
@msJinLei please help review, all tests added and passed. Lmk if any new branch needs to be merged

2023-05-17 02:35 UTC, msJinLei commented
> @msJinLei please help review, all tests added and passed. Lmk if any new branch needs to be merged

@zaynchen115 
You don't address all of the review comments.
We already code freeze.
I recommend you to split your PR.
One part is to make change to an unreleased cmdlet.
Please submit a new PR to just contain this part and target to branch release-2023-05-23.

And the other parts of this PR will be merged to main and target to the next regular release.

2023-05-17 16:47 UTC, zaynchen115 commented
@msJinLei what's the breaking changes are you mentioning. Can I merge to main?
I thought there's a regression in swagger, maybe I can CP if there's another fix another in PS also?

2023-05-17 16:59 UTC, zaynchen115 commented
create a PR to target main https://github.com/Azure/azure-powershell/pull/21850

2023-05-18 02:34 UTC, msJinLei commented
> @msJinLei what's the breaking changes are you mentioning. Can I merge to main? I thought there's a regression in swagger, maybe I can CP if there's another fix another in PS also?

**Please only keep the changes that relates to GetAzureRmVHubEffectiveRoutesCommand.cs in this PR.**

What you change to this cmdlet is the [breaking change] (https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md).  It is a new added cmdlet in this sprint. Currently the cmdlet is not released and so these changes are not identified as the breaking change.

2023-05-18 08:42 UTC, msJinLei commented
close due to be duplicate with https://github.com/Azure/azure-powershell/pull/21850

2023-05-18 08:43 UTC, closed without merging