Alecb/2022 10 14 preview powershell release
Azure/azure-powershell pull request #22132
Opened 2023-06-21 21:32 UTC by alec-baird

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-06-22 16:18 UTC, alec-baird commented
These tests seem to be failing due to a framework issue, as the tests themselves are passing locally and the missing request talked about seems to just be one number off, instead of a +2 in the recording it is a +3.

2023-06-23 05:21 UTC, vidai-msft requested changes

2023-06-23 05:21 UTC, vidai-msft commented on src/DesktopVirtualization/Az.DesktopVirtualization.psd1
> +  ModuleVersion = '2.2.0'
Please do NOT update the version. We will bump during release process.

2023-06-23 05:21 UTC, vidai-msft commented on src/DesktopVirtualization/README.md
> +module-version: 2.2.0
Please do NOT update the version. We will bump during release process.

2023-06-25 04:11 UTC, vidai-msft commented
/azp run

2023-06-26 03:31 UTC, vidai-msft commented
> These tests seem to be failing due to a framework issue, as the tests themselves are passing locally and the missing request talked about seems to just be one number off, instead of a +2 in the recording it is a +3.

@alec-baird this is not an issue but a limitation. The test framework for Autorest cmdlets does not support recording cross-module cmdlets. Can you please move the cmdlets invocation that do not belong to this module to the function setupEnv in utils.ps1?

2023-06-26 04:08 UTC, vidai-msft commented
@alec-baird please leave a comment here as change log for this PR.

2023-06-26 16:10 UTC, alec-baird commented
> @alec-baird please leave a comment here as change log for this PR.

Changelog:
Added Get-AzWvdPrivateLinkResource, Get-AzWvdPrivateLinkConnection, and Remove-AzWvdPrivateLinkConnection cmdlets.

2023-06-26 16:32 UTC, alec-baird commented
> > These tests seem to be failing due to a framework issue, as the tests themselves are passing locally and the missing request talked about seems to just be one number off, instead of a +2 in the recording it is a +3.
> 
> @alec-baird this is not an issue but a limitation. The test framework for Autorest cmdlets does not support recording cross-module cmdlets. Can you please move the cmdlets invocation that do not belong to this module to the function setupEnv in utils.ps1?

The issue with that implementation is that we only want the cross-module cmdlet to run on these few tests, as it is a lengthy cmdlet runtime (almost a minute per call). Can we get a test exception here instead?

2023-06-26 16:32 UTC, vidai-msft commented
@alec-baird please remember to fix the test issue in CI. Thanks!

2023-07-04 02:28 UTC, Nickcandy commented
/azp run

2023-07-04 07:34 UTC, Nickcandy commented
/azp run

2023-07-04 08:07 UTC, wyunchi-ms commented
/azp run

2023-07-04 08:33 UTC, Nickcandy commented
/azp run

2023-07-04 09:03 UTC, wyunchi-ms commented
/azp run azure-powershell - windows-powershell

2023-07-05 03:02 UTC, wyunchi-ms commented
/azp run

2023-07-05 07:17 UTC, wyunchi-ms commented
/azp run

2023-07-05 07:47 UTC, wyunchi-ms commented
/azp run

2023-07-05 08:07 UTC, wyunchi-ms commented
/azp run

2023-07-05 09:57 UTC, merged