[BULK] DocuTune - Updates to Azure AD rebranding guidance and DocuTune configuration (part 6)
Azure/azure-powershell pull request #22894
Opened 2023-10-02 21:36 UTC by alexbuckgit

Applying Azure AD rebranding changes as announced on July 11, 2023 and outlined in https://aka.ms/AzureADNewName. Changes are part of the Microsoft-wide rebranding effort.

CorrelationId: 2520d58e-25ff-469e-af14-2834d2a1505e
PointOfContact: @CelesteDG

#docutune

2023-10-02 21:36 UTC, alexbuckgit commented
#docutune-draft

2023-10-03 17:25 UTC, mikefrobbins submitted a review, later dismissed
LGTM

2023-10-06 17:52 UTC, CelesteDG commented
@mikefrobbins @alexbuckgit Has this build stalled? Do we need to close and reopen the PR?

2023-10-18 01:49 UTC, BethanyZhou commented
/azp run

2023-10-18 04:05 UTC, BethanyZhou requested changes

2023-10-18 04:05 UTC, BethanyZhou commented on src/Storage/Storage.Management/help/New-AzStorageAccount.md
> +
```suggestion
```

2023-10-18 04:06 UTC, BethanyZhou commented on src/Storage/Storage.Management/help/Set-AzStorageAccount.md
> +
```suggestion
```

2023-10-18 04:06 UTC, BethanyZhou commented on src/Ssh/Ssh/help/Export-AzSshConfig.md
> +
```suggestion
```

2023-10-20 20:09 UTC, mikefrobbins commented
/azp run

2023-10-20 20:58 UTC, mikefrobbins approved these changes
LGTM

2023-10-23 07:13 UTC, BethanyZhou commented
FPs are reported. please help force-merge
```
 "Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
  "Az.Ssh","Enter-AzVM","1","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","2","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine -LocalUser azureuser -PrivateKeyFile ./id_rsa -CertificateFile ./cert","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","3","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine -LocalUser azureuser -PrivateKeyFile ./id_rsa","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","4","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine -LocalUser azureuser","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","5","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -Ip 1.2.3.4","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","6","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine -ResourceType Microsoft.HybridCompute/machines","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","7","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine -PrivateKeyFile ./id_rsa -PublicKeyFile ./id_rsa.pub","Check the spell of Enter-AzVM."
  "Az.Ssh","Enter-AzVM","8","1","Invalid_Cmdlet","5000","1","Enter-AzVM is not a valid command name.","Enter-AzVM -ResourceGroupName myRg -Name myMachine -LocalUser username -Rdp","Check the spell of Enter-AzVM."
  "Az.Ssh","Export-AzSshConfig","1","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -ResourceGroupName myRg -Name myMachine -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","2","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -Ip 1.2.3.4 -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","3","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -ResourceGroupName myRg -Name myVm -LocalUser azureuser -CertificateFile ./cert -PrivateKeyFile ./id_rsa -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","4","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -ResourceGroupName myRg -Name myVm -LocalUser azureuser -PrivateKeyFile ./id_rsa -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","5","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -ResourceGroupName myRg -Name myVm -LocalUser azureuser -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","6","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -ResourceGroupName myRg -Name myVm -KeysDestinationFolder /home/user/mykeys -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","7","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -Ip * -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.Ssh","Export-AzSshConfig","8","1","Invalid_Cmdlet","5000","1","Export-AzSshConfig is not a valid command name.","Export-AzSshConfig -ResourceGroupName myRg -Name myVm -ResourceType Microsoft.Compute/virtualMachines -ConfigFilePath ./sshconfig.config","Check the spell of Export-AzSshConfig."
  "Az.TimeSeriesInsights","New-AzTimeSeriesInsightsAccessPolicy","1","1","Invalid_Cmdlet","5000","1","New-AzTimeSeriesInsightsAccessPolicy is not a valid command name.","New-AzTimeSeriesInsightsAccessPolicy -EnvironmentName tsitest001 -ResourceGroupName testgroup -PrincipalObjectId ce74a389-b5e8-4f16-89c7-787031ddd903 -Role Contributor -Name policy001","Check the spell of New-AzTimeSeriesInsightsAccessPolicy."

```

2023-10-23 07:25 UTC, BethanyZhou approved these changes

2023-10-23 07:46 UTC, merged