[BULK] DocuTune - Updates to Azure AD rebranding guidance and DocuTune configuration (part 2)
Azure/azure-powershell pull request #22890
Opened 2023-10-02 21:35 UTC by alexbuckgit

Applying Azure AD rebranding changes as announced on July 11, 2023 and outlined in https://aka.ms/AzureADNewName. Changes are part of the Microsoft-wide rebranding effort.

CorrelationId: 2520d58e-25ff-469e-af14-2834d2a1505e
PointOfContact: @CelesteDG

#docutune

2023-10-02 21:35 UTC, alexbuckgit commented
#docutune-draft

2023-10-03 17:10 UTC, mikefrobbins requested changes
Please see my comments.

2023-10-03 17:10 UTC, mikefrobbins commented on src/Compute/Compute/help/Get-AzVMADDomainExtension.md
> +The **Get-AzVMADDomainExtension** cmdlet gets information about the specified Microsoft Entra ID \(AD) domain extension.
The added backslash `\` is unnecessary and `(AD)` should be removed.

2023-10-03 17:10 UTC, mikefrobbins commented on src/Compute/Compute/help/Set-AzVMADDomainExtension.md
> +The **Set-AzVMADDomainExtension** cmdlet adds a Microsoft Entra ID \(AD) domain virtual machine extension to a virtual machine.
Same issue. The added backslash `\` is unnecessary and `(AD)` should be removed.

2023-10-06 17:50 UTC, CelesteDG commented
@alexbuckgit This PR needs your attention

2023-10-18 04:18 UTC, BethanyZhou commented
/azp run

2023-10-18 05:48 UTC, BethanyZhou commented on src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
> +
```suggestion
```

2023-10-18 05:49 UTC, BethanyZhou commented on src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
> +<a name='example-4-enable-encryption-using-azure-ad-client-id-and-client-certification-thumbprint'></a>
```suggestion
```

2023-10-18 05:49 UTC, BethanyZhou commented on src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
> +<a name='example-5-enable-encryption-using-azure-ad-client-id-client-secret-and-wrap-disk-encryption-key-by-using-key-encryption-key'></a>
```suggestion
```

2023-10-18 05:50 UTC, BethanyZhou commented on src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
> +
```suggestion
```

2023-10-18 05:51 UTC, BethanyZhou commented on src/Compute/Compute/help/Set-AzVMDiskEncryptionExtension.md
> +
```suggestion
```

2023-10-19 03:47 UTC, CelesteDG requested changes

2023-10-19 03:47 UTC, CelesteDG commented on src/Compute/Compute/help/Get-AzVMADDomainExtension.md
> +The **Get-AzVMADDomainExtension** cmdlet gets information about the specified Microsoft Entra ID \(AD) domain extension.
```suggestion
The **Get-AzVMADDomainExtension** cmdlet gets information about the specified Microsoft Entra domain extension.
```

2023-10-19 03:47 UTC, CelesteDG commented on src/Compute/Compute/help/Set-AzVMADDomainExtension.md
> +The **Set-AzVMADDomainExtension** cmdlet adds a Microsoft Entra ID \(AD) domain virtual machine extension to a virtual machine.
```suggestion
The **Set-AzVMADDomainExtension** cmdlet adds a Microsoft Entra domain virtual machine extension to a virtual machine.
```

2023-10-23 07:10 UTC, BethanyZhou commented
```
```

2023-10-23 07:11 UTC, BethanyZhou commented
false positive report for example issues. won't suppress them to allow further debug. require force merge.
```
  "Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
  "Az.Compute","Set-AzVMDiskEncryptionExtension","1","4","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","3","6","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","5","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","36","Invalid_Cmdlet","5000","1","Set-AzKeyVaultSecret is not a valid command name.","Set-AzKeyVaultSecret -VaultName $VaultName -Name $KeyVaultSecretName -SecretValue $Secret","Check the spell of Set-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","37","Invalid_Cmdlet","5000","1","Set-AzKeyVaultAccessPolicy is not a valid command name.","Set-AzKeyVaultAccessPolicy -VaultName $VaultName -ResourceGroupName $RGName -EnabledForDeployment","Check the spell of Set-AzKeyVaultAccessPolicy."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","40","Invalid_Cmdlet","5000","1","Get-AzKeyVaultSecret is not a valid command name.","Get-AzKeyVaultSecret -VaultName $VaultName -Name $KeyVaultSecretName","Check the spell of Get-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","41","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","5","8","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","5","14","Invalid_Cmdlet","5000","1","Add-AzKeyVaultKey is not a valid command name.","Add-AzKeyVaultKey -VaultName $VaultName -Name $KEKName -Destination 'Software'","Check the spell of Add-AzKeyVaultKey."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","5","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","9","Invalid_Cmdlet","5000","1","Add-AzKeyVaultKey is not a valid command name.","Add-AzKeyVaultKey -VaultName $VaultName -Name $KEKName -Destination 'Software'","Check the spell of Add-AzKeyVaultKey."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","38","Invalid_Cmdlet","5000","1","Set-AzKeyVaultSecret is not a valid command name.","Set-AzKeyVaultSecret -VaultName $VaultName-Name $KeyVaultSecretName -SecretValue $Secret","Check the spell of Set-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","39","Invalid_Cmdlet","5000","1","Set-AzKeyVaultAccessPolicy is not a valid command name.","Set-AzKeyVaultAccessPolicy -VaultName $VaultName -ResourceGroupName $RGName -EnabledForDeployment","Check the spell of Set-AzKeyVaultAccessPolicy."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","42","Invalid_Cmdlet","5000","1","Get-AzKeyVaultSecret is not a valid command name.","Get-AzKeyVaultSecret -VaultName $VaultName -Name $KeyVaultSecretName","Check the spell of Get-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","43","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  
```

2023-10-23 07:13 UTC, BethanyZhou approved these changes
LGTM. Analyzer is reporting false positive for example issues. Analyzer can't recognize cmdlet from KeyVault module. Won't suppress them to allow further debug. needs to force merge.
could you help force-merge the PR? @isra-fel.

```
"Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
  "Az.Compute","Set-AzVMDiskEncryptionExtension","1","4","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","3","6","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","5","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","36","Invalid_Cmdlet","5000","1","Set-AzKeyVaultSecret is not a valid command name.","Set-AzKeyVaultSecret -VaultName $VaultName -Name $KeyVaultSecretName -SecretValue $Secret","Check the spell of Set-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","37","Invalid_Cmdlet","5000","1","Set-AzKeyVaultAccessPolicy is not a valid command name.","Set-AzKeyVaultAccessPolicy -VaultName $VaultName -ResourceGroupName $RGName -EnabledForDeployment","Check the spell of Set-AzKeyVaultAccessPolicy."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","40","Invalid_Cmdlet","5000","1","Get-AzKeyVaultSecret is not a valid command name.","Get-AzKeyVaultSecret -VaultName $VaultName -Name $KeyVaultSecretName","Check the spell of Get-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","4","41","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","5","8","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","5","14","Invalid_Cmdlet","5000","1","Add-AzKeyVaultKey is not a valid command name.","Add-AzKeyVaultKey -VaultName $VaultName -Name $KEKName -Destination 'Software'","Check the spell of Add-AzKeyVaultKey."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","5","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","9","Invalid_Cmdlet","5000","1","Add-AzKeyVaultKey is not a valid command name.","Add-AzKeyVaultKey -VaultName $VaultName -Name $KEKName -Destination 'Software'","Check the spell of Add-AzKeyVaultKey."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","38","Invalid_Cmdlet","5000","1","Set-AzKeyVaultSecret is not a valid command name.","Set-AzKeyVaultSecret -VaultName $VaultName-Name $KeyVaultSecretName -SecretValue $Secret","Check the spell of Set-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","39","Invalid_Cmdlet","5000","1","Set-AzKeyVaultAccessPolicy is not a valid command name.","Set-AzKeyVaultAccessPolicy -VaultName $VaultName -ResourceGroupName $RGName -EnabledForDeployment","Check the spell of Set-AzKeyVaultAccessPolicy."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","42","Invalid_Cmdlet","5000","1","Get-AzKeyVaultSecret is not a valid command name.","Get-AzKeyVaultSecret -VaultName $VaultName -Name $KeyVaultSecretName","Check the spell of Get-AzKeyVaultSecret."
  "Az.Compute","Set-AzVMDiskEncryptionExtension","6","43","Invalid_Cmdlet","5000","1","Get-AzKeyVault is not a valid command name.","Get-AzKeyVault -VaultName $VaultName -ResourceGroupName $RGName","Check the spell of Get-AzKeyVault."

```

2023-10-23 07:46 UTC, merged