Service Fabric Migration
Azure/azure-powershell pull request #23061
Opened 2023-10-24 06:01 UTC by mwesigwaguma

## Description

Migrating from .Net sdk dependency to autorest generated sdk. Since Powershell does not support Track 2 .Net sdk , we have decided to migrate autorest.powershell generated sdk.
## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-10-24 06:12 UTC, VeryEarly commented
What is the purpose of this PR? What are differences from: https://github.com/Azure/azure-powershell/pull/22860

2023-10-24 06:21 UTC, mwesigwaguma commented
> What is the purpose of this PR? What are differences from: #22860

They are two different sdks. Service Fabric and Service Fabric Managed Clusters
If you look in https://github.com/mwesigwaguma/azure-sdk-for-net/tree/main/sdk, you will find both Service Fabric and Service Fabric Managed Clusters. I am migrating both from .Net dependency

2023-10-24 06:57 UTC, mwesigwaguma commented
> What is the purpose of this PR? What are differences from: #22860

Can I get this merged if nothing else

2023-10-24 07:43 UTC, VeryEarly requested changes

2023-10-24 07:43 UTC, VeryEarly commented on src/ServiceFabric/ServiceFabric.Management.sdk/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.Azure.PowerShell.Cmdlets.ServiceFabric.Test")]
remove this line

2023-10-24 07:43 UTC, VeryEarly commented on src/ServiceFabric/ServiceFabric/ServiceFabric.csproj
> +    <ProjectReference Include="..\ServiceFabric.Management.Sdk\ServiceFabric.Management.sdk.csproj" />
indentation

2023-10-24 14:54 UTC, mwesigwaguma commented on src/ServiceFabric/ServiceFabric/ServiceFabric.csproj
> +    <ProjectReference Include="..\ServiceFabric.Management.Sdk\ServiceFabric.Management.sdk.csproj" />
updated

2023-10-24 14:54 UTC, mwesigwaguma commented on src/ServiceFabric/ServiceFabric.Management.sdk/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Microsoft.Azure.PowerShell.Cmdlets.ServiceFabric.Test")]
updated

2023-10-25 02:08 UTC, VeryEarly approved these changes

2023-10-25 02:08 UTC, VeryEarly commented
/azp run azure-powershell - security-tools

2023-10-25 03:06 UTC, VeryEarly approved these changes

2023-10-25 03:16 UTC, VeryEarly commented
/azp run azure-powershell - security-tools

2023-10-25 06:35 UTC, VeryEarly commented
/azp run azure-powershell - security-tools

2023-10-25 06:48 UTC, VeryEarly approved these changes

2023-10-25 06:48 UTC, merged