Remove deprecated workspace collection cmdlets
Azure/azure-powershell pull request #23099
Opened 2023-10-30 10:01 UTC by ayeshurun

## Description

## Checklist

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-11-01 11:22 UTC, VeryEarly requested changes

2023-11-01 11:22 UTC, VeryEarly commented on src/PowerBIEmbedded/PowerBIEmbedded/Az.PowerBIEmbedded.psd1
> +ModuleVersion = '2.0.0'
revert this line

2023-11-01 11:22 UTC, VeryEarly commented on src/PowerBIEmbedded/PowerBIEmbedded/ChangeLog.md
> +## Version 2.0.0
move line 23 to line 21 and remove line 22

2023-11-01 11:22 UTC, VeryEarly commented on src/PowerBIEmbedded/PowerBIEmbedded.Test/PowerBIEmbedded.Test.csproj
> +  <ItemGroup>
please remove this section

2023-11-01 12:12 UTC, ayeshurun commented
@VeryEarly resolved all comments. would appreciate a review

2023-11-02 02:31 UTC, VeryEarly commented on src/PowerBIEmbedded/PowerBIEmbedded/Az.PowerBIEmbedded.psd1
> +ModuleVersion = '2.0.0'
please do revert this line

2023-11-02 02:32 UTC, VeryEarly commented
> @VeryEarly resolved all comments. would appreciate a review

please revert version change in [src/PowerBIEmbedded/PowerBIEmbedded/Az.PowerBIEmbedded.psd1](https://github.com/Azure/azure-powershell/pull/23099/files/9ba9199a6ba66dbead418688b670c39f3f65799b#diff-7b23a994a2b6de33fc11d52d16d19aa72df9743b8edbc80861b546fffe081a75)

2023-11-02 07:38 UTC, ayeshurun commented
@VeryEarly resolved comments. hopefully last iteration. please review :)

2023-11-05 10:54 UTC, ayeshurun commented
@a1exwang / @VeryEarly would appreciate your feedback.

2023-11-05 10:54 UTC, VeryEarly approved these changes

2023-11-05 10:54 UTC, merged