update to Changed-module build
Azure/azure-powershell pull request #23331
Opened 2023-11-09 09:39 UTC by Nickcandy

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-11-10 07:03 UTC, Nickcandy commented
@isra-fel  @wyunchi-ms 
Hi, please help me review the above changes about the module build

Here is the test bump version: https://github.com/Azure/azure-powershell/pull/23332/files
Here is the test daily build: https://dev.azure.com/azclitools/internal/_build/results?buildId=105648&view=results
Here is the test sign: https://dev.azure.com/azclitools/release/_build/results?buildId=105643&view=results

2023-11-13 02:00 UTC, VeryEarly reviewed
is the empty changelog.md intended?

2023-11-14 05:17 UTC, isra-fel requested changes

2023-11-21 06:57 UTC, Nickcandy commented
@isra-fel  @wyunchi-ms 
Hi, please help me review the above changes about the module build

Here is the test bump version: https://github.com/Azure/azure-powershell/pull/23332/files
Here is the test daily build: https://dev.azure.com/azclitools/internal/_build/results?buildId=109250&view=results
Here is the test sign: https://dev.azure.com/azclitools/release/_build/results?buildId=109297&view=results

2023-11-23 08:52 UTC, wyunchi-ms commented on tools/BuildScripts/CheckChangelogs.ps1
> +    [string] $outputFile = "artifacts/ChangedModule.txt",
change default value to `artifacts/ModifiedModule.txt`

2023-11-24 07:46 UTC, wyunchi-ms commented on tools/BuildScripts/BuildModules.ps1
> +        $csprojFiles += Include-CsprojFiles -Path "$RepoRoot/src" -Filter "Authenticators.csproj"
These code can be reused with line 57 - line 70

2023-11-24 10:49 UTC, Nickcandy commented on .azure-pipelines/code-sign.yml
> +  displayName: Build Module List(Split by ':')
Yes I know that. But It seems like `;` or `,` cannot use in dotnet cli after I test.

2023-11-30 07:41 UTC, wyunchi-ms commented on build.proj
> +
```suggestion
    <Exec Condition="$(PullRequestNumber) == '' AND $(TargetModule) == '' AND $(ModifiedModuleBuild) == 'false'"
      Command="$(PowerShellCoreCommandPrefix) &quot;.\tools\BuildScripts\BuildModules.ps1 -RepoRoot $(RepoRoot) -Configuration $(Configuration) -TestsToRun $(TestsToRun) -CoreTests $(CoreTests) -RepoArtifacts $(RepoArtifacts) &quot;"
    />
    <Exec Condition="$(PullRequestNumber) != ''"
      Command="$(PowerShellCoreCommandPrefix) &quot;.\tools\BuildScripts\BuildModules.ps1 -RepoRoot $(RepoRoot) -Configuration $(Configuration) -TestsToRun $(TestsToRun) -CoreTests $(CoreTests) -RepoArtifacts $(RepoArtifacts) -BuildCsprojList '@(BuildCsprojList)' -TestCsprojList '@(TestCsprojList)'&quot;"
    />
    <Exec Condition="$(ModifiedModuleBuild) != 'false'"
      Command="$(PowerShellCoreCommandPrefix) &quot;.\tools\BuildScripts\BuildModules.ps1 -RepoRoot $(RepoRoot) -Configuration $(Configuration) -TestsToRun $(TestsToRun) -CoreTests $(CoreTests) -RepoArtifacts $(RepoArtifacts) -ModifiedModuleBuild $(ModifiedModuleBuild) &quot;"
    />
    <Exec Condition="$(TargetModule) != ''"
      Command="$(PowerShellCoreCommandPrefix) &quot;.\tools\BuildScripts\BuildModules.ps1 -RepoRoot $(RepoRoot) -Configuration $(Configuration) -TestsToRun $(TestsToRun) -CoreTests $(CoreTests) -RepoArtifacts $(RepoArtifacts) -TargetModule $(TargetModule)&quot;"
    />
```

2023-11-30 08:00 UTC, wyunchi-ms commented on tools/BuildScripts/BuildModules.ps1
> +
```suggestion
function Add-TestProjects {
    param (
        [string[]] $csprojFiles,
        [string]$TestsToRun,
        [string]$CoreTests,
        [string]$modulePath
    )
        $csprojFiles += Include-CsprojFiles -Path "$modulePath" -Exclude "*.Test.csproj;Authenticators.csproj" -Filter "*.csproj"
        if ($Configuration -ne 'Release') {
            if ($TestsToRun -eq 'All') {
                $csprojFiles += Include-CsprojFiles -Path $modulePath -Filter "*.Test.csproj"
            } elseif ($TestsToRun -eq 'NonCore') {
                $csprojFiles += Include-CsprojFiles -Path $modulePath -Exclude $CoreTests -Filter "*.Test.csproj"
            } elseif ($TestsToRun -eq 'Core') {
                $csprojFiles += Include-CsprojFiles -Path $modulePath -Include $CoreTests
            }
        }

        if ($env:OS -eq "Windows_NT") {
            $csprojFiles += Include-CsprojFiles -Path "$modulePath" -Filter "Authenticators.csproj"
        }
}
```

2023-12-04 06:05 UTC, wyunchi-ms approved these changes

2023-12-04 06:09 UTC, merged