Az Alb 2023-11-01 (Reorg)
Azure/azure-powershell pull request #23479
Opened 2023-11-17 19:15 UTC by malpaniHMC

## Description

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

2023-11-20 07:17 UTC, dolauli requested changes
Except issues mentioned in my comments. Another issue that a wrong folder tmp/Alb was checked in.

2023-11-20 17:49 UTC, malpaniHMC commented on src/Alb/Alb.Autorest/README.md
> -    transform: $ = $.replace('((Microsoft.Azure.PowerShell.Cmdlets.Alb.Models.Api20230501Preview.IAssociationPropertiesInternal)Property).AssociationType = value;', '((Microsoft.Azure.PowerShell.Cmdl
It seems like it may not be required anymore since it doesn't use codegen v4

2023-11-21 02:51 UTC, dolauli commented on src/Alb/Alb.Autorest/README.md
> -  - $(this-folder)/../../readme.azure.noprofile.md
This change is in correct.

2023-11-21 02:53 UTC, dolauli commented on src/Alb/Alb.Autorest/docs/New-AzAlb.md
> +### -SystemDataCreatedAt
These are something that should be not generated. I use the same README.md as you, but those parameters are not generated. Would you please do following things.

1. Sync your code with latest main
2. run 'autorest --reset' to upgrade autorest.powershell
3. Regenerate the code with autorest.powershell

2023-11-29 01:14 UTC, malpaniHMC commented on src/Alb/Alb.Autorest/README.md
> -  - $(this-folder)/../../readme.azure.noprofile.md
reverted

2023-12-01 00:57 UTC, dolauli requested changes
Instead of skipping all the tests and removing the recording files, you should update the tests and re-recording them.

2023-12-06 02:48 UTC, dolauli commented
@malpaniHMC After my change, you should be able to record the now. Please record the test with 'test-module.ps1 -Record' and resolve the conflict.

2023-12-06 06:27 UTC, dolauli commented
/azp run

2023-12-06 13:01 UTC, wyunchi-ms commented
/azp run

2023-12-08 00:14 UTC, dolauli commented
@microsoft-github-policy-service rerun

2023-12-08 00:34 UTC, merged