[NetAppFiles] Generate SDK to api-version 2023-05-01
Azure/azure-powershell pull request #23710
Opened 2023-12-11 13:29 UTC by audunn

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2023-12-12 03:16 UTC, dolauli commented
@audunn Please resolve the conflicts.

2023-12-13 01:53 UTC, dolauli commented
@audunn There are some issues detected in the `Analyze`. Please resolve them.

2023-12-14 01:41 UTC, dolauli requested changes

2023-12-14 01:41 UTC, dolauli commented on src/NetAppFiles/NetAppFiles/ChangeLog.md
> +* Added new cmdLets `Get-AzNetAppFilesNetworkSiblingSet` and `Update-AzNetAppFilesNetworkSiblingSet` to query and update update the network features of a network sibling set
`update update` - one update is redundant.

2023-12-14 01:41 UTC, dolauli commented on src/NetAppFiles/NetAppFiles/ChangeLog.md
> +* Added new cmdLets `Get-AzNetAppFilesNetworkSiblingSet` and `Update-AzNetAppFilesNetworkSiblingSet` to query and update update the network features of a network sibling set
line#24 and line#25 are the same. Please remove one

2023-12-19 03:19 UTC, dolauli approved these changes

2023-12-19 03:20 UTC, merged

2023-12-21 15:57 UTC, audunn commented
Note we are be adding a fix for NetApp Account Identity in https://github.com/Azure/azure-powershell/pull/23808