[Az.KeyVault] User mi support for backup/restore hsm
Azure/azure-powershell pull request #23916
Opened 2024-01-09 16:38 UTC by NoriZC

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-01-10 02:19 UTC, wyunchi-ms submitted a review, later dismissed

2024-01-10 11:40 UTC, NoriZC commented
Do NOT MERGE because it still have below error:
client assembly: Azure.Security.KeyVault.Administration
DEBUG: Azure-Core: [Warning] Error response [ac408663-93a3-44b2-a90b-00d4994693f0] 500 Internal Server Error (00.6s)

2024-01-15 06:50 UTC, wyunchi-ms submitted a review, later dismissed

2024-01-16 03:12 UTC, BethanyZhou requested changes

2024-01-16 03:12 UTC, BethanyZhou commented on src/KeyVault/KeyVault/Commands/FullBackupRestore/FullBackupRestoreCmdletBase.cs
> +                throw new AzPSArgumentException("Parameter SasToken and UseUserManagedIdentity can not exist at the same time. Please choose either one as authentication method.", ErrorKind.UserError
If customer provides sastoken and UseUserManagedIdentity at the same time, I'd suggest using sastoken by default to follow the design of [swagger](https://github.com/Azure/azure-rest-api-specs/blob/05c4049bc22f0ec65acc18f9835132397049cb9e/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.5-preview.1/backuprestore.json#L356).

Needs to check if sastoken and UseUserManagedIdentity both are not provided.

2024-01-16 07:23 UTC, BethanyZhou approved these changes
Looks good to me

2024-01-16 07:23 UTC, merged