[Az.RecoveryServices.Backup] Added support for setting snapshot consistency type in backup policy
Azure/azure-powershell pull request #24169
Opened 2024-02-18 07:07 UTC by hiaga

## Description

* Added option to set snapshot consistency type in policy cmdlets for creating or updating enhanced AzureVM policies.
* Fixed an issue while setting soft delete vault property. 

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-02-19 09:36 UTC, msJinLei requested changes
Please fix the failed test cases

2024-02-19 09:36 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesBackupProtectionPolicy.md
> +{{ Fill ProgressAction Description }}
```suggestion
```

2024-02-19 09:36 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
> +{{ Fill ProgressAction Description }}
```suggestion
```

2024-02-19 09:36 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
> +{{ Fill ProgressAction Description }}
```suggestion
```

2024-02-23 03:24 UTC, msJinLei requested changes

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesBackupProtectionPolicy.md
> + [-VaultId <String>] [-DefaultProfile <IAzureContextContainer>] [-ProgressAction <ActionPreference>] [-WhatIf]
```suggestion
 [-VaultId <String>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf]
```

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/New-AzRecoveryServicesBackupProtectionPolicy.md
> +### -ProgressAction
Remove ProgressAction

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
> + [-ProgressAction <ActionPreference>] [-WhatIf] [-Confirm] [<CommonParameters>]
```suggestion
 [-WhatIf] [-Confirm] [<CommonParameters>]
```

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesBackupProtectionPolicy.md
> +### -ProgressAction
Remove ProgressAction

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
> + [-Token <String>] [-ProgressAction <ActionPreference>] [-WhatIf] [-Confirm] [<CommonParameters>]
```suggestion
 [-Token <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
> + [-UseSystemAssignedIdentity <Boolean>] [-UserAssignedIdentity <String>] [-ProgressAction <ActionPreference>]
```suggestion
 [-UseSystemAssignedIdentity <Boolean>] [-UserAssignedIdentity <String>]
```

2024-02-23 03:24 UTC, msJinLei commented on src/RecoveryServices/RecoveryServices/help/Set-AzRecoveryServicesVaultProperty.md
> +### -ProgressAction
Remove ProgressAction

2024-02-27 11:27 UTC, hiaga commented
updated as per review comments

2024-03-04 07:44 UTC, msJinLei commented
/azp run azure-powershell - security-tools

2024-03-04 07:44 UTC, msJinLei approved these changes

2024-03-04 07:59 UTC, merged