Move Policy CRUD cmdlets to autorest generation: fixes (#23518)
Azure/azure-powershell pull request #24221
Opened 2024-02-23 00:50 UTC by mentat9

* Set all tests to -LiveOnly Add back some test infrastructure fixes that were lost Improve parameter handling for Remove-AzPolicySetDefinition

* Move to supported way of sharing Helpers.psm1 file

* Switch to recommended approach for shared functions

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [X] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-02-23 02:38 UTC, msJinLei requested changes
Please resolve the conflicts

2024-02-23 02:38 UTC, msJinLei commented on src/Resources/Policy.Autorest/custom/Remove-AzPolicySetDefinition.ps1
> +    [Parameter(ParameterSetName='ManagementGroupName', Mandatory)]
It is a breaking change to change from optional to mandatory

2024-04-24 06:49 UTC, YanaXu commented
/azp run

2024-05-07 05:28 UTC, VeryEarly commented
/azp run

2024-05-08 01:34 UTC, wyunchi-ms commented
/azp run

2024-05-08 02:52 UTC, VeryEarly approved these changes

2024-05-08 02:53 UTC, merged