PowerShell Support for Email Services Control Plane CRUD operations
Azure/azure-powershell pull request #24230
Opened 2024-02-23 11:53 UTC by v-vprasannak

## Description
## Version 0.1.0
* First preview release for module Az.EmailService

## Mandatory Checklist
[ChangeLog.md](https://github.com/Azure/azure-powershell/files/14384825/ChangeLog.md)

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-02-27 04:33 UTC, msJinLei requested changes
The folder name should be consistent with module name.
Please change folder name to emailservice or module name to communication

2024-02-27 05:47 UTC, v-vprasannak commented
> The folder name should be consistent with module name. Please change folder name to emailservice or module name to communication
@msJinLei Could you please suggest, is there any particular pattern to be followed? or can we go ahead with the below pattern?
- src
     - Communication
            - Communication.Autorest
     - EmailService
           - EmailService.Autorest

2024-02-27 08:41 UTC, msJinLei commented
> > The folder name should be consistent with module name. Please change folder name to emailservice or module name to communication
> > @msJinLei Could you please suggest, is there any particular pattern to be followed? or can we go ahead with the below pattern?
> 
> * src
>   
>   * Communication
>     - Communication.Autorest
>   * EmailService
>     - EmailService.Autorest

Please add 
```
root-module-name: $(prefix).Communication
``
to the readme.md of EmailService

2024-02-28 05:34 UTC, msJinLei approved these changes

2024-02-28 05:34 UTC, msJinLei commented on src/Communication/EmailService.Autorest/README.md
> +use-extension:
```suggestion
```

2024-02-28 05:34 UTC, msJinLei commented on src/Communication/EmailService.Autorest/README.md
> +  "@autorest/powershell": "4.x"
```suggestion
```

2024-02-28 05:38 UTC, msJinLei approved these changes

2024-02-28 05:59 UTC, merged