post autogeneration
Azure/azure-powershell pull request #24422
Opened 2024-03-20 22:47 UTC by hvedati

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-03-21 01:36 UTC, vidai-msft requested changes
Please fix the test errors on CI.

2024-03-21 01:36 UTC, vidai-msft commented on src/StackHCIVM/StackHCIVM.Autorest/Az.StackHCIVM.psd1
> +  ModuleVersion = '2.0.0'
Do NOT update the module version here.

2024-03-21 01:36 UTC, vidai-msft commented on src/StackHCIVM/StackHCIVM.Autorest/README.md
> +module-version: 2.0.0
Do NOT update the version

2024-03-22 02:57 UTC, vidai-msft commented
/azp run

2024-03-22 03:46 UTC, vidai-msft commented
/azp run

2024-03-22 04:17 UTC, vidai-msft commented
@hvedati The build issue has been resolved. Please fix the test issue.

2024-03-22 05:23 UTC, vidai-msft commented
@hvedati Can you please select the target release for this PR in the Mandatory Checklist section?

2024-03-23 02:58 UTC, vidai-msft commented
@hvedati Please leave a comment here as the change log message.

2024-03-24 18:59 UTC, hvedati commented
Updating API to 2024-01-01 version.

2024-03-25 07:24 UTC, vidai-msft approved these changes
LGTM

2024-03-25 07:24 UTC, merged