Use ZipDeploy API when deploying functions apps
Azure/azure-powershell pull request #24702
Opened 2024-04-22 18:23 UTC by dannysongg

## Description

Adding logic to use ZipDeploy instead of OneDeploy when deploying functions apps. This change also adds a switch to deploy using ZipDeploy.

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [X] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-04-23 16:18 UTC, patelchandni requested changes

2024-04-23 16:18 UTC, patelchandni commented on src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
NIT: remove empty line between if else

2024-04-23 16:18 UTC, patelchandni commented on src/Websites/Websites/help/Publish-AzWebApp.md
> + [-DefaultProfile <IAzureContextContainer>] [-ProgressAction <ActionPreference>] [-WhatIf] [-Confirm]
I think ProgressAction is removed on "main" branch. Was this added back intentionally or just need to rebase your branch on main.

2024-04-23 16:18 UTC, patelchandni commented on src/Websites/Websites/help/Publish-AzWebApp.md
> +### -ProgressAction
I think ProgressAction is removed on "main" branch. Was this added back intentionally or just need to rebase your branch on main.

2024-04-23 18:16 UTC, dannysongg commented on src/Websites/Websites/help/Publish-AzWebApp.md
> + [-ProgressAction <ActionPreference>] [-WhatIf] [-Confirm] [<CommonParameters>]
This was automatically added when I regenerated the help.md. I will remove

2024-04-25 06:13 UTC, YanaXu commented on src/Websites/Websites/ChangeLog.md
> +* `Publish-AzWebApp` now uses ZipDeploy to publish Function Apps
```suggestion
* Supported the parameter `ZipDeploy` in cmdlet `Publish-AzWebApp` to publish Function Apps
```

2024-04-25 06:14 UTC, YanaXu commented on src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs
> +            var appKind = WebsitesClient.GetWebApp(ResourceGroupName, Name, null).Kind;
Please add tests for this update.

2024-04-25 06:25 UTC, YanaXu commented
Please suppress the "Invalid_Cmdlet" errors.

2024-04-25 19:59 UTC, closed without merging