[Account] Adding warning message to discourage username/password
Azure/azure-powershell pull request #25435
Opened 2024-07-02 06:30 UTC by lijinpei2008

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-07-02 08:18 UTC, msJinLei requested changes
Please describe the change in the change log

2024-07-02 08:18 UTC, msJinLei commented on src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
> +                WriteWarning("Authentication with a username and password at the command line is strongly discouraged. Use one of the recommended authentication methods based on your requirements. Fo
Please use a resource string instead.

2024-07-03 02:17 UTC, lijinpei2008 commented
Add Breaking Change Notification to Change Access Token from String to Secure String
https://github.com/Azure/azure-powershell/pull/25419

2024-07-03 03:36 UTC, msJinLei requested changes

2024-07-03 03:36 UTC, msJinLei commented on src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs
> +                WriteWarning(warningMessage);
Please add the string to Resources.resx

2024-07-03 03:36 UTC, msJinLei commented on src/Accounts/Accounts/ChangeLog.md
> +* In `Connect-AzAccount` add warning message to discourage username/password flow
```suggestion
* In `Connect-AzAccount` add warning message to deprecate username/password flow
```

2024-07-03 03:36 UTC, msJinLei commented on src/Accounts/Accounts/ChangeLog.md
> +* In `Get-AzAccessToken` add Breaking Change Notification to Change Access Token from String to Secure String
```suggestion
* In `Get-AzAccessToken` add Breaking Change notification to change AccessToken property from String to Secure String
```

2024-07-03 03:36 UTC, msJinLei commented on src/Accounts/Accounts/ChangeLog.md
Move the change log just under upcoming release

2024-07-03 06:11 UTC, msJinLei approved these changes

2024-07-03 06:11 UTC, msJinLei commented
LGTM

2024-07-03 06:56 UTC, isra-fel requested changes

2024-07-03 06:56 UTC, isra-fel commented on src/Accounts/Accounts/ChangeLog.md
> +* In `Get-AzAccessToken` add Breaking Change notification to change AccessToken property from String to Secure String
```suggestion
* Added a warning message in `Connect-AzAccount` to discourage the use of the username/password (a.k.a ROPC) login flow.
* Preannounced a breaking change in `Get-AzAccessToken` to change `Token` property from `String` to `SecureString`.
``

2024-07-03 08:39 UTC, isra-fel approved these changes

2024-07-03 08:39 UTC, merged