[cdn]function Cdn migration to afd added
Azure/azure-powershell pull request #25506
Opened 2024-07-11 07:09 UTC by Ptnan7

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-07-19 02:25 UTC, t-bzhan commented
@Ptnan7 , can you correcte the grammar in the PR title and clearly expressed the intention to add cmdlets to support classical CDN migration.

2024-07-19 02:56 UTC, t-bzhan requested changes

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/custom/Move-AzCdnProfileToAFD.ps1
> +function Move-AzCdnProfileToAFD {
Could you please sync with the PS team to determine whether this name is suitable for our migration purpose? I remember we used to have a process to review command names/parameters in advance, but I’m not sure if it’s still needed.

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/custom/Invoke-AzCdnCommitProfileToAFDMigration.ps1
> +        Write-Host("This process will disable your Front Door (classic) profile and move all your traffic and configurations to the new Front Door profile.")
Copy typo, this is not for Classical Front Door.

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/custom/Move-AzCdnProfileToAFD.ps1
> +            throw "The IdentityType is invalid. The supported types are 'SystemAssigned,UserAssigned' when the front door has Customer Certificates during migration."
Copy typo

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/docs/Invoke-AzCdnCommitProfileToAFDMigration.md
> +Commit the migrated Azure Front Door(Standard/Premium) profile..
Could you please provide more details regarding what this step means? Additionally, what are the consequences if a customer conducts this step?

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/examples/Invoke-AzCdnCommitProfileToAFDMigration.md
> +### Example 2: Commit the migrated Azure Front Door(Standard/Premium) profile, when the subscription of the profile is different from the local subscrition
That is somewhat confusing. Are we allowed to migrate to another subscription?

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/test/Get-AzCdnKeyGroup.Tests.ps1
> +{
KeyGroup support is not ready yet, suggest to remove it.

2024-07-19 02:56 UTC, t-bzhan commented on src/Cdn/Cdn.Autorest/Az.Cdn.psd1
Please update the changelog

2024-07-23 01:24 UTC, VeryEarly commented
API has been changed to a preview version, is it intended or this PR is targeting a preview release?

2024-07-25 06:46 UTC, Ptnan7 commented
> API has been changed to a preview version, is it intended or this PR is targeting a preview release?

Yes, this PR is a preview release

2024-07-26 06:20 UTC, VeryEarly commented
> > API has been changed to a preview version, is it intended or this PR is targeting a preview release?
> 
> Yes, this PR is a preview release

do you understand what preview in Azure-PowersShell means? please read the link in the checklist of this PR

2024-07-30 02:31 UTC, Ptnan7 commented
> > > API has been changed to a preview version, is it intended or this PR is targeting a preview release?
> > 
> > 
> > Yes, this PR is a preview release
> 
> do you understand what preview in Azure-PowersShell means? please read the link in the checklist of this PR

Out team want to release a preview api, could you help us to create a preview branch for us?

2024-07-31 06:34 UTC, merged