[Storage] Add live test to cover File/Table, and cover StorageContext generate in different ways
Azure/azure-powershell pull request #26069
Opened 2024-09-10 03:26 UTC by blueww

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-09-11 06:50 UTC, vidai-msft requested changes

2024-09-11 06:50 UTC, vidai-msft commented on src/Storage/Storage.Management/ChangeLog.md
> +* Add live test to cover File and Table services, and cover Storage context created from both Storage account and manully.
No need to add change log here since only test files were modified.

2024-09-11 07:03 UTC, vidai-msft approved these changes
LGTM

2024-09-30 05:28 UTC, blueww commented
@vidai-msft 

Would you please help to merge this PR is nor other issue.
Feel free to ping me if any action needed from me.

2024-09-30 09:17 UTC, merged