Alecb/generation api upgrade preannounce
Azure/azure-powershell pull request #26249
Opened 2024-10-09 03:57 UTC by alec-baird

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-10-09 19:06 UTC, msJinLei requested changes

2024-10-09 19:06 UTC, msJinLei commented on documentation/breaking-changes/upcoming-breaking-changes.md
> +    - All cmdlets with SystemData properties have their property-type switched from struct to string.
Please refer to https://github.com/Azure/azure-powershell/blob/3dfb95de6647a49c2ed584abe18195f3975dc33e/tools/StaticAnalysis/Exceptions/Az.DesktopVirtualization/BreakingChangeIssues.csv to preannounce all the non-v4-upgrading breaking changes

2024-10-09 19:06 UTC, msJinLei commented on documentation/breaking-changes/upcoming-breaking-changes.md
>  # Upcoming Breaking Changes
```suggestion
# Upcoming Breaking Changes of Az.DesktopVirtualization
```

2024-10-09 19:06 UTC, msJinLei commented on documentation/breaking-changes/upcoming-breaking-changes.md
> +    ## Release 13.0.0 - November 2024
```suggestion
    ## Release Az 13.0.0 - November 2024
```

2024-10-09 19:06 UTC, msJinLei commented on documentation/breaking-changes/upcoming-breaking-changes.md
> +    The following cmdlets were affected this release:
```suggestion
    The cmdlets contain the following properties in their inputs and outputs are affected by the release :
```

2024-10-09 19:06 UTC, msJinLei commented on documentation/breaking-changes/upcoming-breaking-changes.md
> +    **All Cmdlets**
```suggestion
```

2024-10-09 19:12 UTC, alec-baird commented on src/DesktopVirtualization/DesktopVirtualization.Autorest/README.md
> +      verb: (.*)
You said you were doing the preannouncement for v4 upgrade, so I didn't include it here.

2024-10-09 19:13 UTC, alec-baird commented on documentation/breaking-changes/upcoming-breaking-changes.md
> +    ```
You said your team was handling the preannouncement for the v4 upgrade.

2024-10-13 19:39 UTC, msJinLei requested changes
Please change the link in preannouncement to https://go.microsoft.com/fwlink/?linkid=2292409

2024-10-13 19:39 UTC, msJinLei commented on src/DesktopVirtualization/DesktopVirtualization.Autorest/README.md
> +        preview-message: This release will contain numerous breaking changes, please view the preannouncement here (https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/
```suggestion
        preview-message: This release will contain numerous breaking changes, please view the preannouncement here (https://go.microsoft.com/fwlink/?linkid=2292409)
```

2024-10-21 12:53 UTC, msJinLei commented on documentation/breaking-changes/upcoming-breaking-changes.md
Could you remove the file as the content is moved to the new PR https://github.com/Azure/azure-powershell/pull/26269

2024-10-21 12:57 UTC, msJinLei reviewed
Please remove the "upcoming-breaking-changes.md" and regenerate the module and commit all the necessary changes

2024-10-22 01:15 UTC, msJinLei approved these changes

2024-10-22 01:15 UTC, merged