Fixing a bug for setting a registry type correctly
Azure/azure-powershell pull request #26697
Opened 2024-11-14 19:54 UTC by ankushbindlish2

## Description

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2024-11-14 21:03 UTC, stefong99 commented on src/StorageSync/StorageSync/Interop/Clients/SyncServerRegistrationClientBase.cs
>              Guid? applicationId = GetApplicationIdOrNull();
will always calling this cause problems on older agent versions?

2024-11-14 21:07 UTC, stefong99 requested changes
I think I saw 3 places where we had isCertificateRegistration across SyncServerRegistrationClient and SyncServerRegistrationClientBase

can we update to add those checks back? using assignIdentity is fine too

For instance, we should not call "EnsureServerCertificate" if assignIdentity is true.

2024-11-14 22:54 UTC, stefong99 approved these changes

2024-11-15 05:07 UTC, VeryEarly commented
Hi,
I remember you mentioned this feature is targeting ignite, why is still open?

2024-11-15 17:39 UTC, closed without merging