Update BicepUtility.cs
Azure/azure-powershell pull request #26782
Opened 2024-11-28 08:59 UTC by SimonWahlin

## Description

Parameter --documentationUri is deprecated, please use --documentation-uri instead.

![image](https://github.com/user-attachments/assets/dbe0b2d8-05bb-40e3-b1c3-3b05f1a4a8c9)

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2025-01-07 07:37 UTC, YanaXu commented
Hi @SimonWahlin,

Please join your github account to Azure org.

- Link your GitHub Account with Microsoft Account on this page: [Open Source Management Portal / Account link](https://repos.opensource.microsoft.com/link)
- Join below organizations on this page: [Open Source Management Portal / Organizations](https://repos.opensource.microsoft.com/orgs)
  - Azure

2025-01-07 08:15 UTC, SimonWahlin commented
@YanaXu I am not a Microsoft employee.

2025-01-08 08:30 UTC, YanaXu commented
/azp run azure-powershell - security-tools

2025-01-08 13:47 UTC, anthony-c-martin commented on src/Resources/ResourceManager/Utilities/BicepUtility.cs
> +                bicepPublishCommand += $" --documentation-uri {GetQuotedFilePath(documentationUri)}";
To avoid breaking users of older versions of Bicep, we'll need to only use the new format if the version of Bicep is greater than or equal to [0.24.24](https://github.com/Azure/bicep/blob/v0.24.24/src/Bicep.Cli/Arguments/PublishArguments.cs), and retain the old logic if not.

You could probably use a check similar to https://github.com/Azure/azure-powershell/blob/d20265b6a4c6d82c3048c8728b2fb97992772cfe/src/Resources/ResourceManager/Utilities/BicepUtility.cs#L191 to accomplish this.

2025-01-08 13:47 UTC, anthony-c-martin requested changes
See comment on back-compatibility

2025-01-08 20:16 UTC, SimonWahlin commented
Great point @anthony-c-martin 

I've added a method that checks for a minimal version and returns a bool to make it reusable, I hope it fulfills the requirements.

2025-01-08 21:06 UTC, anthony-c-martin approved these changes
Looks great, thanks!

2025-01-09 03:32 UTC, YanaXu commented
/azp run azure-powershell - security-tools

2025-01-10 01:09 UTC, YanaXu approved these changes

2025-01-10 01:09 UTC, merged