Adding ApplicationId parameter to get- and remove-azRoleAssignment cmdlets
Azure/azure-powershell pull request #26890
Opened 2024-12-17 14:12 UTC by SebastianClaesson

## Description

Adding ApplicationId parameter, with aliases; 
- SPN
- ServicePrincipalName

Related to issue; #26889 

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [X] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

2025-01-07 07:35 UTC, YanaXu commented
Hi @SebastianClaesson,

Please join your github account to Azure org.

- Link your GitHub Account with Microsoft Account on this page: [Open Source Management Portal / Account link](https://repos.opensource.microsoft.com/link)
- Join below organizations on this page: [Open Source Management Portal / Organizations](https://repos.opensource.microsoft.com/orgs)
  - Azure

2025-01-21 04:18 UTC, notyashhh commented
@SebastianClaesson The changes look good, a few things from my side,

Can you please confirm the reason for adding an additional alias `ApplicationId`?


1. Instead of updating the parameter, `ApplicationId` can be added as an alias, this will maintain consistency. (See my suggested changes)

2. Need to run Update-Markdown to re-generate Help docs to reflect changes made to the params. See: [here](https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md#updating-a-single-markdown-file)

3. Change log in Resources needs to be updated to reflect this change.

2025-01-21 04:23 UTC, notyashhh requested changes
Could you please make the changes?

2025-01-21 04:23 UTC, notyashhh commented on src/Resources/Resources/RoleAssignments/GetAzureRoleAssignmentCommand.cs
> +        public string ApplicationId { get; set; }
Following code maintains code consistency.
```
[Alias("SPN", "ApplicationId")]
public string ServicePrincipalName { get; set; }
```

2025-01-21 04:23 UTC, notyashhh commented on src/Resources/Resources/RoleAssignments/RemoveAzureRoleAssignmentCommand.cs
> +        public string ApplicationId { get; set; }
Following code maintains code consistency.
```
[Alias("SPN", "ApplicationId")]
public string ServicePrincipalName { get; set; }
```

2025-01-31 09:37 UTC, SebastianClaesson commented
> @SebastianClaesson The changes look good, a few things from my side,
> 
> Can you please confirm the reason for adding an additional alias `ApplicationId`?
> 
> 1. Instead of updating the parameter, `ApplicationId` can be added as an alias, this will maintain consistency. (See my suggested changes)
> 2. Need to run Update-Markdown to re-generate Help docs to reflect changes made to the params. See [here](https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md#updating-a-single-markdown-file)
> 3. Change log in Resources needs to be updated to reflect this change.

The reason for adding the alias 'ApplicationId' is to maintain consistency with the published 'New-AzRoleAssignment' cmdlet 
https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azroleassignment?view=azps-13.1.0#-applicationid

1) I've updated so that Applicationid is an alias - however in New-AzRoleAssignment the aliases are 'SPN' & 'ServicePrincipalName' - Perhaps it should be aligned to avoid confusion from developers.

2) Do you want me to re-generate the help docs (Guess I'll have to compile the module) 

3) In what release would this be included in ? 7.9.0?

2025-02-05 02:25 UTC, YanaXu commented
/azp run

2025-02-10 07:28 UTC, VeryEarly commented
/azp run

2025-02-20 14:35 UTC, VeryEarly approved these changes

2025-02-20 14:36 UTC, merged